import type { Meta, StoryObj } from '@storybook/react-vite';

import type { defaultProps as BaseTriggerExampleProps } from './examples/base-trigger-ellipsis';
import BaseTriggerEllipsisExample from './examples/base-trigger-ellipsis';
import type { defaultProps as ButtonTriggerExampleProps } from './examples/button-trigger-ellipsis';
import ButtonTriggerEllipsisExample from './examples/button-trigger-ellipsis';
import type { defaultProps as FilterTriggerExampleProps } from './examples/filter-trigger-ellipsis';
import FilterTriggerEllipsisExample from './examples/filter-trigger-ellipsis';
import FilterTriggerSelectWithEllipsisExample from './examples/filter-trigger-select-with-ellipsis';
import FilterTriggerWithCounterExample from './examples/filter-trigger_with_counter';
import type { defaultProps as LinkTriggerExampleProps } from './examples/link-trigger-ellipsis';
import LinkTriggerEllipsisExample from './examples/link-trigger-ellipsis';
const meta: Meta = {
  title: 'Components/Base Trigger/Advanced',
};
const commonArgTypes = {
  hintProps: {
    control: 'select',
    options: ['default', 'false'],
    mapping: {
      default: undefined,
      false: false,
    },
  },
  hintPlacement: {
    control: { type: 'select' },
    options: ['top', 'bottom', 'left', 'right'],
  },
} as const;
export const LinkTriggerEllipsis: StoryObj<typeof LinkTriggerExampleProps> = {
  render: LinkTriggerEllipsisExample,
  argTypes: {
    ...commonArgTypes,
  },
  parameters: { sourceCode: 'import { LinkTrigger } from \'@semcore/ui/base-trigger\';\nimport DropdownMenu from \'@semcore/ui/dropdown-menu\';\nimport React from \'react\';\n\ntype LinkTriggerEllipsisProps = {\n  hintPlacement?: \'top\' | \'bottom\' | \'left\' | \'right\';\n  hintProps?: false;\n};\n\nconst Demo = (props: LinkTriggerEllipsisProps) => {\n  return (\n    <>\n      <DropdownMenu>\n        <DropdownMenu.Trigger tag={LinkTrigger} size={400}>\n          <LinkTrigger.Text\n            w={150}\n            display=\'inline-flex\'\n            hint={props.hintProps}\n            hint:placement={props.hintPlacement}\n            ellipsis:cropPosition=\'middle\'\n          >\n            Few Tags Tags Tags\n          </LinkTrigger.Text>\n        </DropdownMenu.Trigger>\n        <br />\n        <br />\n        <br />\n        <DropdownMenu.Trigger tag={LinkTrigger} size={400}>\n          <LinkTrigger.Text\n            w={150}\n            ellipsis:cropPosition=\'middle\'\n            hint={props.hintProps}\n            hint:placement={props.hintPlacement}\n            data-test-id=\'ellipsis-middle\'\n          >\n            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores atque autem\n            commodi, doloribus ex harum inventore modi praesentium quam ratione reprehenderit rerum\n            tempore voluptas. Aliquam eos expedita illo quasi unde!\n          </LinkTrigger.Text>\n        </DropdownMenu.Trigger>\n        <br />\n        <br />\n        <br />\n        <DropdownMenu.Trigger tag={LinkTrigger} size={400}>\n          <LinkTrigger.Text\n            w={150}\n            ellipsis={true}\n            hint={props.hintProps}\n            hint:placement={props.hintPlacement}\n          >\n            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores atque autem\n            commodi, doloribus ex harum inventore modi praesentium quam ratione reprehenderit rerum\n            tempore voluptas. Aliquam eos expedita illo quasi unde!\n          </LinkTrigger.Text>\n        </DropdownMenu.Trigger>\n        <DropdownMenu.Menu>\n          <DropdownMenu.Item>Save</DropdownMenu.Item>\n          <DropdownMenu.Item>Rename</DropdownMenu.Item>\n          <DropdownMenu.Item>Download</DropdownMenu.Item>\n          <DropdownMenu.Item>Delete</DropdownMenu.Item>\n        </DropdownMenu.Menu>\n      </DropdownMenu>\n\n    </>\n  );\n};\n\nexport const defaultProps: LinkTriggerEllipsisProps = {\n};\n\nexport default Demo;\n' },
};
export const BaseTriggerEllipsis: StoryObj<typeof BaseTriggerExampleProps> = {
  render: BaseTriggerEllipsisExample,
  argTypes: {
    ...commonArgTypes,
  },
  parameters: { sourceCode: 'import BaseTrigger from \'@semcore/ui/base-trigger\';\nimport DropdownMenu from \'@semcore/ui/dropdown-menu\';\nimport React from \'react\';\n\ntype BaseTriggerEllipsisProps = {\n  hintPlacement?: \'top\' | \'bottom\' | \'left\' | \'right\';\n  hintProps?: false;\n};\n\nconst Demo = (props: BaseTriggerEllipsisProps) => {\n  return (\n    <>\n      <DropdownMenu>\n        <DropdownMenu.Trigger tag={[BaseTrigger, \'h1\']}>\n          <BaseTrigger.Text w={150} tag=\'h2\' size={400}>\n            No ellipsis Few Tags Tags Tags\n          </BaseTrigger.Text>\n        </DropdownMenu.Trigger>\n        <br />\n        <br />\n        <br />\n        <DropdownMenu.Trigger tag={BaseTrigger}>\n          <BaseTrigger.Text\n            w={150}\n            size={400}\n            ellipsis:cropPosition=\'middle\'\n            hint={props.hintProps}\n            hint:placement={props.hintPlacement}\n          >\n            This is first trigger with a very very long text!\n          </BaseTrigger.Text>\n        </DropdownMenu.Trigger>\n        <br />\n        <br />\n        <DropdownMenu.Trigger tag={BaseTrigger}>\n          <BaseTrigger.Text\n            w={150}\n            size={400}\n            ellipsis={true}\n            hint={props.hintProps}\n            hint:placement={props.hintPlacement}\n          >\n            This is second trigger with a very very long text!\n          </BaseTrigger.Text>\n        </DropdownMenu.Trigger>\n        <DropdownMenu.Menu>\n          <DropdownMenu.Item>Save</DropdownMenu.Item>\n          <DropdownMenu.Item>Rename</DropdownMenu.Item>\n          <DropdownMenu.Item>Download</DropdownMenu.Item>\n          <DropdownMenu.Item>Delete</DropdownMenu.Item>\n        </DropdownMenu.Menu>\n      </DropdownMenu>\n\n      <br />\n      <br />\n      <BaseTrigger w={100} data-test-id=\'active-trigger\'>\n        <BaseTrigger.Text\n          ellipsis={true}\n          hint={props.hintProps}\n          hint:placement={props.hintPlacement}\n        >\n          This is third trigger with a very very long text!\n        </BaseTrigger.Text>\n      </BaseTrigger>\n    </>\n  );\n};\nexport const defaultProps: BaseTriggerEllipsisProps = {\n};\n\nexport default Demo;\n\nexport const App = () => <Demo />;\n' },
};
export const FilterTriggerSelectWithEllipsis: StoryObj = {
  render: FilterTriggerSelectWithEllipsisExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { FilterTrigger } from \'@semcore/ui/base-trigger\';\nimport Select from \'@semcore/ui/select\';\nimport React from \'react\';\n\nconst Demo = () => {\n  const [material, setMaterial] = React.useState([]);\n  const [color, setColor] = React.useState([]);\n\n  return (\n    <>\n      <Flex gap={2}>\n        <Select onChange={setMaterial} multiselect>\n          <Select.Trigger\n            tag={FilterTrigger}\n            placeholder=\'Material\'\n            aria-label=\'Material\'\n          >\n            <FilterTrigger.Text\n              wMax={80}\n              ellipsis:cropPosition=\'middle\'\n              key={material.length}\n            >\n              <span aria-hidden=\'true\'>Material: </span>\n              {material.length === 1 ? material : `${material.length} selected`}\n            </FilterTrigger.Text>\n          </Select.Trigger>\n\n          <Select.Menu aria-label=\'Material\'>\n            {materials.map((option, idx) => (\n              <Select.Option value={option} key={idx}>\n                <Select.Option.Checkbox />\n                {option}\n              </Select.Option>\n            ))}\n          </Select.Menu>\n        </Select>\n\n        <Select onChange={setColor} multiselect>\n          <Select.Trigger\n            tag={FilterTrigger}\n            placeholder=\'Color\'\n            aria-label=\'Color\'\n          >\n            <FilterTrigger.Text\n              wMax={40}\n              ellipsis\n              key={color.length}\n            >\n              <span aria-hidden=\'true\'>Color: </span>\n              {color.length === 1 ? color : `${color.length} selected`}\n            </FilterTrigger.Text>\n          </Select.Trigger>\n          <Select.Menu aria-label=\'Color\'>\n            {colors.map((option, idx) => (\n              <Select.Option value={option} key={idx}>\n                <Select.Option.Checkbox />\n                {option}\n              </Select.Option>\n            ))}\n          </Select.Menu>\n        </Select>\n      </Flex>\n    </>\n  );\n};\n\nconst materials = [\'Glass 123\', \'Metal 123\', \'Paper\', \'Wood\'];\nconst colors = [\'Red\', \'Blue 123\', \'Green\', \'Yellow 123\'];\n\nexport default Demo;\n' },
};
export const ButtonTriggerEllipsis: StoryObj<typeof ButtonTriggerExampleProps> = {
  render: ButtonTriggerEllipsisExample,
  argTypes: {
    ...commonArgTypes,
  },
  parameters: { sourceCode: 'import { ButtonTrigger } from \'@semcore/ui/base-trigger\';\nimport DropdownMenu from \'@semcore/ui/dropdown-menu\';\nimport React from \'react\';\n\ntype ButtonTriggerEllipsisProps = {\n  hintPlacement?: \'top\' | \'bottom\' | \'left\' | \'right\';\n  hintProps?: false;\n};\n\nconst Demo = (props: ButtonTriggerEllipsisProps) => {\n  return (\n    <>\n      <DropdownMenu>\n        <DropdownMenu.Trigger tag={[ButtonTrigger, \'h1\']}>\n          <ButtonTrigger.Text\n            w={150}\n            tag=\'h2\'\n            size={400}\n            ellipsis:cropPosition=\'middle\'\n            hint={props.hintProps}\n            hint:placement={props.hintPlacement}\n          >\n            Few Tags Tags Tags\n          </ButtonTrigger.Text>\n        </DropdownMenu.Trigger>\n        <br />\n        <br />\n        <DropdownMenu.Trigger tag={ButtonTrigger}>\n          <ButtonTrigger.Text\n            w={150}\n            size={400}\n            data-test-id=\'ellipsis-middle\'\n            ellipsis:cropPosition=\'middle\'\n            hint={props.hintProps}\n            hint:placement={props.hintPlacement}\n          >\n            This is first trigger with a very very long text!\n          </ButtonTrigger.Text>\n        </DropdownMenu.Trigger>\n        <br />\n        <br />\n        <DropdownMenu.Trigger tag={ButtonTrigger}>\n          <ButtonTrigger.Text\n            w={150}\n            size={400}\n            ellipsis={true}\n            hint={props.hintProps}\n            hint:placement={props.hintPlacement}\n          >\n\n            This is second trigger with a very very long text!\n          </ButtonTrigger.Text>\n        </DropdownMenu.Trigger>\n        <DropdownMenu.Menu>\n          <DropdownMenu.Item>Save</DropdownMenu.Item>\n          <DropdownMenu.Item>Rename</DropdownMenu.Item>\n          <DropdownMenu.Item>Download</DropdownMenu.Item>\n          <DropdownMenu.Item>Delete</DropdownMenu.Item>\n        </DropdownMenu.Menu>\n      </DropdownMenu>\n\n      <br />\n      <br />\n      <ButtonTrigger w={100} data-test-id=\'active-trigger\'>\n        <ButtonTrigger.Text\n          ellipsis={true}\n          hint={props.hintProps}\n          hint:placement={props.hintPlacement}\n        >\n          This is third trigger with a very very long text!\n        </ButtonTrigger.Text>\n      </ButtonTrigger>\n\n    </>\n  );\n};\n\nexport const defaultProps: ButtonTriggerEllipsisProps = {\n};\n\nexport default Demo;\n' },
};
export const FilterTriggerEllipsis: StoryObj<typeof FilterTriggerExampleProps> = {
  render: FilterTriggerEllipsisExample,
  argTypes: {
    ...commonArgTypes,
  },
  parameters: { sourceCode: 'import { FilterTrigger } from \'@semcore/ui/base-trigger\';\nimport DropdownMenu from \'@semcore/ui/dropdown-menu\';\nimport React from \'react\';\n\ntype ButtonTriggerEllipsisProps = {\n  hintPlacement?: \'top\' | \'bottom\' | \'left\' | \'right\';\n  hintProps?: false;\n};\n\nconst Demo = (props: ButtonTriggerEllipsisProps) => {\n  return (\n    <>\n      <DropdownMenu>\n        <DropdownMenu.Trigger tag={[FilterTrigger, \'h1\']}>\n          <FilterTrigger.Text\n            w={150}\n            tag=\'h1\'\n            size={400}\n            ellipsis:cropPosition=\'middle\'\n            hint={props.hintProps}\n            hint:placement={props.hintPlacement}\n          >\n            Few tags tags\n          </FilterTrigger.Text>\n        </DropdownMenu.Trigger>\n        <br />\n        <br />\n        <DropdownMenu.Trigger tag={FilterTrigger}>\n          <FilterTrigger.Text\n            w={150}\n            size={400}\n            data-test-id=\'ellipsis-middle\'\n            ellipsis:cropPosition=\'middle\'\n            hint={props.hintProps}\n            hint:placement={props.hintPlacement}\n          >\n            This is first trigger with a very very long text!\n          </FilterTrigger.Text>\n        </DropdownMenu.Trigger>\n        <br />\n        <br />\n        <DropdownMenu.Trigger tag={FilterTrigger}>\n          <FilterTrigger.Text w={150} size={400} ellipsis={true}>\n            This is second trigger with a very very long text!\n          </FilterTrigger.Text>\n        </DropdownMenu.Trigger>\n        <DropdownMenu.Menu>\n          <DropdownMenu.Item>Save</DropdownMenu.Item>\n          <DropdownMenu.Item>Rename</DropdownMenu.Item>\n          <DropdownMenu.Item>Download</DropdownMenu.Item>\n          <DropdownMenu.Item>Delete</DropdownMenu.Item>\n        </DropdownMenu.Menu>\n      </DropdownMenu>\n\n      <br />\n      <br />\n      <FilterTrigger w={100} data-test-id=\'active-trigger\'>\n        <FilterTrigger.Text\n          ellipsis={true}\n          hint={props.hintProps}\n          hint:placement={props.hintPlacement}\n        >\n          This is third trigger with a very very long text!\n        </FilterTrigger.Text>\n      </FilterTrigger>\n    </>\n  );\n};\n\nexport const defaultProps: ButtonTriggerEllipsisProps = {\n};\n\nexport default Demo;\n' },
};
export const FilterTriggerWithCounter: StoryObj = {
  render: FilterTriggerWithCounterExample,
  parameters: { sourceCode: 'import { FilterTrigger } from \'@semcore/ui/base-trigger\';\nimport Button from \'@semcore/ui/button\';\nimport Dropdown from \'@semcore/ui/dropdown\';\nimport React from \'react\';\n\nconst Demo = () => {\n  const [filters, setFilters] = React.useState(0);\n  const [visible, setVisible] = React.useState(false);\n\n  return (\n    <Dropdown visible={visible} onVisibleChange={(v: any) => setVisible(v)}>\n      <Dropdown.Trigger\n        placeholder=\'Advanced filters\'\n        aria-label=\'Advanced filters\'\n        active={visible}\n        empty={!filters}\n        onClear={() => {\n          setFilters(0);\n          setVisible(false);\n        }}\n        tag={FilterTrigger}\n      >\n        <FilterTrigger.Text aria-hidden>Advanced filters</FilterTrigger.Text>\n        {!!filters && <FilterTrigger.Counter>{filters}</FilterTrigger.Counter>}\n      </Dropdown.Trigger>\n      <Dropdown.Popper aria-label=\'Advanced filters\' p={5}>\n        <Button onClick={() => setFilters(filters + 1)}>Add a filter</Button>\n      </Dropdown.Popper>\n    </Dropdown>\n  );\n};\n\nexport default Demo;\n' },
};
export default meta;
