# https://support.crowdin.com/cli-tool ver.3
"project_id": "367533"
# https://crowdin.com/settings#api-key
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"preserve_hierarchy" : true
"files": [
  {
    "source": "/semcore/base-trigger/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
  {
    "source": "/semcore/breadcrumbs/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
  {
    "source": "/semcore/carousel/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
  {
    "source": "/semcore/color-picker/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
  {
      "source": "/semcore/d3-chart/src/translations/en.json",
      "translation": "/%original_path%/%two_letters_code%.json",
  },
  {
    "source": "/semcore/d3-chart/src/a11y/translations/module/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
  {
    "source": "semcore/data-table/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
  {
    "source": "/semcore/time-picker/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
  {
    "source": "/semcore/widget-empty/src/Error/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
  {
    "source": "/semcore/widget-empty/src/NoData/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
  {
    "source": "/semcore/wizard/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  }
]
