# https://support.crowdin.com/cli-tool ver.3
"project_id": "367533"
# https://crowdin.com/settings#api-key
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"preserve_hierarchy" : true
"files": [
  {
    "source": "/semcore/base-trigger/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/breadcrumbs/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/color-picker/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/date-picker/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/drag-and-drop/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/dropdown/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/dropdown-menu/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/errors/src/AccessDenied/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/errors/src/Maintenance/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/errors/src/PageError/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/errors/src/PageNotFound/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/errors/src/ProjectNotFound/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/inline-edit/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/inline-input/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/input-number/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/modal/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/notice/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/notice-bubble/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/notice-global/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/pagination/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/select/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/tag/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/time-picker/src/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/widget-empty/src/Error/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
{
    "source": "/semcore/widget-empty/src/NoData/translations/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
  {
    "source": "/semcore/d3-chart/src/a11y/translations/module/en.json",
    "translation": "/%original_path%/%two_letters_code%.json",
  },
  {
    "source": "semcore/d3-chart/src/a11y/translations/view/en.csv",
    "first_line_contains_header": true,
    "scheme" : "identifier,source_phrase,context,translation",
    "translation": "/%original_path%/%two_letters_code%.csv",
  },
]
