import { DataTable } from '@semcore/ui/data-table';
import type { Meta, StoryObj } from '@storybook/react-vite';

import EmptyStateSortableExample from './examples/table-states-tests/empty-sortable';
import LoadingPaginationExample from './examples/table-states-tests/loading-in-pagination';
import LoadingScrollExample from './examples/table-states-tests/loading-in-scroll';
import LoadingWithScrollAndButtonExample from './examples/table-states-tests/loading-with-button-and-scroll';
import NothingFoundWithFixedColumnWidthExample from './examples/table-states-tests/nothing-found-with-fixed-column-width';
import WidgetEmptyInCellExample from './examples/table-states-tests/widget-empty-in-cell';
const meta: Meta<typeof DataTable> = {
  title: 'Components/DataTable/Tests/TableStates',
  component: DataTable,
};
export default meta;
type Story = StoryObj<typeof DataTable>;
export const WidgetEmptyInCell: Story = {
  render: WidgetEmptyInCellExample,
  parameters: { sourceCode: 'import Button from \'@semcore/ui/button\';\nimport { DataTable } from \'@semcore/ui/data-table\';\nimport { NoData } from \'@semcore/ui/widget-empty\';\nimport React from \'react\';\n\nconst data = [\n  {\n    \'keyword/kd/cpc/vol\': \'\',\n  },\n];\n\nconst Demo = () => {\n  return (\n    <DataTable\n      data={data}\n      aria-label=\'Empty table example\'\n      columns={[\n        { name: \'keyword\', children: \'keyword\' },\n        { name: \'kd\', children: \'KD,%\' },\n        { name: \'cpc\', children: \'CPC\' },\n        { name: \'vol\', children: \'Vol.\' },\n      ]}\n      renderCell={() => (\n        <NoData type=\'nothing-found\' my={7} mx=\'auto\'>\n          <Button mt={4}>Clear filters</Button>\n        </NoData>\n      )}\n    />\n  );\n};\n\nexport default Demo;\n' },
};
export const NothingFoundWithFixedColumnWidth: Story = {
  render: NothingFoundWithFixedColumnWidthExample,
  parameters: { sourceCode: 'import { Box } from \'@semcore/ui/base-components\';\nimport Button from \'@semcore/ui/button\';\nimport { DataTable } from \'@semcore/ui/data-table\';\nimport { NoData } from \'@semcore/ui/widget-empty\';\nimport React from \'react\';\n\nconst Demo = () => {\n  return (\n    <Box w=\'100%\' position=\'absolute\' left={0}>\n      <DataTable\n        data={[]}\n        aria-label=\'Empty table example\'\n        w=\'100%\'\n        columns={[\n          { name: \'keyword\', children: \'keyword\', gtcWidth: \'minmax(150px, 1fr)\' },\n          { name: \'kd\', children: \'KD,%\', gtcWidth: \'minmax(150px, 1fr)\' },\n          { name: \'cpc\', children: \'CPC\', gtcWidth: \'minmax(150px, 1fr)\' },\n          { name: \'vol\', children: \'Vol.\', gtcWidth: \'minmax(150px, 1fr)\' },\n        ]}\n        renderEmptyData={() => (\n          <NoData type=\'nothing-found\' my={7} mx=\'auto\'>\n            <Button mt={4}>Clear filters</Button>\n          </NoData>\n        )}\n      />\n    </Box>\n  );\n};\n\nexport default Demo;\n' },
};
export const EmptyStateSortable: Story = {
  render: EmptyStateSortableExample,
  parameters: { sourceCode: 'import type { DataTableSort } from \'@semcore/ui/data-table\';\nimport { DataTable } from \'@semcore/ui/data-table\';\nimport React from \'react\';\n\ntype DataRow = {\n  keyword: string;\n  kd: string;\n  cpc: string;\n  vol: string;\n};\n\ntype SortableColumn = Exclude<keyof DataRow, never>;\n\nconst Demo = () => {\n  const [sort, setSort] = React.useState<DataTableSort<keyof DataRow>>([\'keyword\', \'desc\']);\n\n  return (\n    <DataTable\n      data={[]}\n      sort={sort}\n\n      aria-label=\'Sorting\'\n      columns={[\n        { name: \'keyword\', children: \'Keyword\', sortable: true },\n        { name: \'kd\', children: \'KD,%\', sortable: true },\n        { name: \'cpc\', children: \'CPC\', sortable: true },\n        { name: \'vol\', children: \'Vol.\' },\n      ]}\n    />\n  );\n};\n\nexport default Demo;\n' },
};
export const LoadingWithScrollAndButton: Story = {
  render: LoadingWithScrollAndButtonExample,
  parameters: { sourceCode: 'import { ScreenReaderOnly } from \'@semcore/ui/base-components\';\nimport Button from \'@semcore/ui/button\';\nimport { DataTable } from \'@semcore/ui/data-table\';\nimport React from \'react\';\n\nconst Demo = (): any => {\n  const [loading, setLoading] = React.useState(true);\n  const [message, setMessage] = React.useState(\'\');\n\n  React.useEffect(() => {\n    const timer = setTimeout(() => {\n      setMessage(\'\');\n    }, 300);\n    return () => {\n      clearTimeout(timer);\n    };\n  }, [message]);\n\n  const toggleLoading = () => {\n    setLoading(!loading);\n    setMessage(loading ? \'Data loaded\' : \'Loading started\');\n  };\n\n  return (\n    <>\n      <ScreenReaderOnly role=\'status\' aria-live=\'polite\'>\n        {message}\n      </ScreenReaderOnly>\n      <DataTable\n        data={data}\n        aria-label=\'Loading using SpinContainer\'\n        loading={loading}\n        h={150}\n        columns={[\n          { name: \'keyword\', children: \'Keyword\' },\n          { name: \'kd\', children: \'KD,%\' },\n          { name: \'cpc\', children: \'CPC\' },\n          { name: \'vol\', children: \'Vol.\' },\n        ]}\n      />\n      <Button onClick={toggleLoading} mt={3}>\n        {loading ? \'Stop loading\' : \'Start loading\'}\n      </Button>\n    </>\n  );\n};\n\nconst data = [\n  {\n    keyword: \'ebay buy\',\n    kd: \'77.8\',\n    cpc: \'$1.25\',\n    vol: \'32,500,000\',\n  },\n  {\n    keyword: \'www.ebay.com\',\n    kd: \'11.2\',\n    cpc: \'$3.4\',\n    vol: \'65,457,920\',\n  },\n  {\n    keyword: \'www.ebay.com\',\n    kd: \'10\',\n    cpc: \'$0.65\',\n    vol: \'47,354,640\',\n  },\n  {\n    keyword: \'ebay buy\',\n    kd: \'-\',\n    cpc: \'$0\',\n    vol: \'n/a\',\n  },\n  {\n    keyword: \'ebay buy\',\n    kd: \'75.89\',\n    cpc: \'$0\',\n    vol: \'21,644,290\',\n  },\n];\n\nexport default Demo;\n' },
};
export const LoadingPagination: Story = {
  render: LoadingPaginationExample,
  parameters: { sourceCode: 'import { DataTable } from \'@semcore/ui/data-table\';\nimport Pagination from \'@semcore/ui/pagination\';\nimport React from \'react\';\n\nconst Demo = () => {\n  const [currentPage, setCurrentPage] = React.useState(0);\n  const numberFormat = React.useMemo(() => new Intl.NumberFormat(\'en-US\'), []);\n  const currencyFormat = React.useMemo(\n    () => new Intl.NumberFormat(\'en-US\', { currency: \'USD\', style: \'currency\' }),\n    [],\n  );\n\n  const limit = 2;\n  const tableData = data.slice(currentPage * limit, currentPage * limit + limit);\n\n  return (\n    <>\n      <DataTable\n        data={tableData}\n        aria-label=\'Pagination\'\n        h=\'auto\'\n        loading\n        columns={[\n          { name: \'keyword\', children: \'Keyword\', justifyContent: \'left\' },\n          { name: \'kd\', children: \'KD,%\', justifyContent: \'right\', gtcWidth: \'minmax(fit-content, 68px)\' },\n          { name: \'cpc\', children: \'CPC\', gtcWidth: \'minmax(fit-content, 60px)\' },\n          { name: \'vol\', children: \'Vol.\', gtcWidth: \'minmax(fit-content, 120px)\', justifyContent: \'left\' },\n        ]}\n        renderCell={(props) => {\n          if (props.columnName === \'keyword\') {\n            return props.defaultRender();\n          }\n\n          const value = props.defaultRender();\n\n          return typeof value === \'number\' && value !== -1 ? numberFormat.format(value) : \'n/a\';\n        }}\n      />\n      <Pagination\n        mt={4}\n        totalPages={Math.ceil(data.length / limit)}\n        currentPage={currentPage + 1}\n        onCurrentPageChange={(page) => setCurrentPage(page - 1)}\n      />\n    </>\n  );\n};\n\nexport default Demo;\n\nconst data = [\n  {\n    keyword: \'ebay buy\',\n    kd: 77.8,\n    cpc: 1.25,\n    vol: 32500000,\n  },\n  {\n    keyword: \'www.ebay.com\',\n    kd: 11.2,\n    cpc: 3.4,\n    vol: 65457920,\n  },\n  {\n    keyword: \'www.ebay.com\',\n    kd: 10,\n    cpc: 0.65,\n    vol: 47354640,\n  },\n  {\n    keyword: \'ebay buy\',\n    kd: -1,\n    cpc: 0,\n    vol: -1,\n  },\n  {\n    keyword: \'ebay buy last\',\n    kd: 75.89,\n    cpc: 0,\n    vol: 21644290,\n  },\n];\n' },
};
export const LoadingScroll: Story = {
  render: LoadingScrollExample,
  parameters: { sourceCode: 'import Button from \'@semcore/ui/button\';\nimport { DataTable } from \'@semcore/ui/data-table\';\nimport React from \'react\';\n\nconst Demo = () => {\n  const [loading, setLoading] = React.useState(false);\n\n  React.useEffect(() => {\n    const showTimeout = setTimeout(() => {\n      setLoading(true);\n\n      const hideTimeout = setTimeout(() => {\n        setLoading(false);\n      }, 3000);\n\n      return () => clearTimeout(hideTimeout);\n    }, 3000);\n\n    return () => clearTimeout(showTimeout);\n  }, []);\n\n  return (\n    <>\n      <Button>Click</Button>\n      <DataTable\n        data={data}\n        aria-label=\'Scroll inside\'\n        loading={loading}\n        wMax={800}\n        hMax={200}\n        columns={[\n          {\n            name: \'keyword\',\n            children: \'keyword\',\n          },\n          {\n            name: \'kd\',\n            children: \'KD,%\',\n          },\n          {\n            name: \'cpc\',\n            children: \'CPC\',\n          },\n          {\n            name: \'vol\',\n            children: \'Vol.\',\n          },\n        ]}\n      />\n    </>\n  );\n};\n\nconst data = [\n  { keyword: \'ebay buy\', kd: \'77.8\', cpc: \'$1.25\', vol: \'32,500,000\' },\n  { keyword: \'www.ebay.com\', kd: \'11.2\', cpc: \'$3.4\', vol: \'65,457,920\' },\n  { keyword: \'www.ebay.com\', kd: \'10\', cpc: \'$0.65\', vol: \'47,354,640\' },\n  { keyword: \'ebay buy\', kd: \'-\', cpc: \'$0\', vol: \'n/a\' },\n  { keyword: \'ebay buy\', kd: \'75.89\', cpc: \'$0\', vol: \'21,644,290\' },\n  { keyword: \'ebay buy\', kd: \'77.8\', cpc: \'$1.25\', vol: \'32,500,000\' },\n  { keyword: \'www.ebay.com\', kd: \'11.2\', cpc: \'$3.4\', vol: \'65,457,920\' },\n  { keyword: \'www.ebay.com\', kd: \'10\', cpc: \'$0.65\', vol: \'47,354,640\' },\n  { keyword: \'ebay buy\', kd: \'-\', cpc: \'$0\', vol: \'n/a\' },\n  { keyword: \'ebay buy\', kd: \'75.89\', cpc: \'$0\', vol: \'21,644,290\' },\n];\n\nexport default Demo;\n' },
};
