export default {
  '--intergalactic-bg-primary-feature-highlight': '#ffffff',
  '--intergalactic-bg-primary-feature-highlight-hover-active': 'linear-gradient(90deg, #f3eaff, #eaf0ff)',
  '--intergalactic-bg-secondary-feature-highlight': 'linear-gradient(90deg, #f3eaff, #eaf0ff)',
  '--intergalactic-border-feature-highlight': 'linear-gradient(90deg, #b070ff, #709bff)',
  '--intergalactic-border-feature-highlight-active': 'linear-gradient(90deg, #a155ff, #5487ff)',
  '--intergalactic-border-feature-highlight-secondary': 'linear-gradient(90deg, #c99dff, #9dbaff)',
  '--intergalactic-control-primary-feature-highlight': 'linear-gradient(90deg, #a155ff, #5487ff)',
  '--intergalactic-control-primary-feature-highlight-hover': 'linear-gradient(90deg, #892aff, #2969ff)',
  '--intergalactic-control-primary-feature-highlight-active': 'linear-gradient(90deg, #7d26e8, #2560e8)',
  '--intergalactic-control-secondary-feature-highlight': 'linear-gradient(90deg, #f3eaff, #eaf0ff)',
  '--intergalactic-control-secondary-feature-highlight-hover': 'linear-gradient(90deg, #e5d1ff, #d1dfff)',
  '--intergalactic-control-secondary-feature-highlight-active': 'linear-gradient(90deg, #dabdff, #bdd1ff)',
  '--intergalactic-text-feature-highlight': 'linear-gradient(90deg, #892aff, #2969ff)',
  '--intergalactic-text-feature-highlight-hover-active': 'linear-gradient(90deg, #611eb5, #1d4bb5)',
  '--intergalactic-icon-primary-feature-highlight': '#892aff',
  '--intergalactic-icon-primary-feature-highlight-hover-active': '#6B3AB4',
  '--intergalactic-keyboard-focus-feature-highlight-outline': 'linear-gradient(90deg, #a155ff, #5487ff)',
};
