export default {
  '--intergalactic-bg-primary-feature-highlight': '#ffffff',
  '--intergalactic-bg-primary-feature-highlight-hover-active': 'linear-gradient(90deg, #f5f1ff, #eef4ff)',
  '--intergalactic-bg-secondary-feature-highlight': 'linear-gradient(90deg, #f5f1ff, #eef4ff)',
  '--intergalactic-border-feature-highlight': 'linear-gradient(90deg, #b494ff, #83aaf7)',
  '--intergalactic-border-feature-highlight-active': 'linear-gradient(90deg, #a070fe, #5e8ef2)',
  '--intergalactic-border-feature-highlight-secondary': 'linear-gradient(90deg, #cbb7ff, #aac6fb)',
  '--intergalactic-control-primary-feature-highlight': 'linear-gradient(90deg, #a070fe, #5e8ef2)',
  '--intergalactic-control-primary-feature-highlight-hover': 'linear-gradient(90deg, #8426f5, #2661e8)',
  '--intergalactic-control-primary-feature-highlight-active': 'linear-gradient(90deg, #5a17a9, #1640a1)',
  '--intergalactic-control-secondary-feature-highlight': 'linear-gradient(90deg, #f5f1ff, #eef4ff)',
  '--intergalactic-control-secondary-feature-highlight-hover': 'linear-gradient(90deg, #ebe4ff, #dee9fe)',
  '--intergalactic-control-secondary-feature-highlight-active': 'linear-gradient(90deg, #e2d8ff, #d0e0fe)',
  '--intergalactic-text-feature-highlight': 'linear-gradient(90deg, #8426f5, #2661e8)',
  '--intergalactic-text-feature-highlight-hover-active': 'linear-gradient(90deg, #350a69, #0e2a6a)',
  '--intergalactic-icon-primary-feature-highlight': '#8426f5',
  '--intergalactic-icon-primary-feature-highlight-hover-active': '#6B3AB4',
  '--intergalactic-keyboard-focus-feature-highlight-outline': 'linear-gradient(90deg, #a070fe, #5e8ef2)',
};
