export default {
  '--intergalactic-bg-primary-feature-highlight': '#ffffff',
  '--intergalactic-bg-primary-feature-highlight-hover-active': 'linear-gradient(90deg, #f5f1ff, #eef4ff)',
  '--intergalactic-bg-secondary-feature-highlight': 'linear-gradient(90deg, #f5f1ff, #eef4ff)',
  '--intergalactic-border-feature-highlight': 'linear-gradient(90deg, #c190ff, #83aaf7)',
  '--intergalactic-border-feature-highlight-active': 'linear-gradient(90deg, #a070fe, #709bff)',
  '--intergalactic-border-feature-highlight-secondary': 'linear-gradient(90deg, #cbb7ff, #bdd1ff)',
  '--intergalactic-control-primary-feature-highlight': 'linear-gradient(90deg, #a070fe, #709bff)',
  '--intergalactic-control-primary-feature-highlight-hover': 'linear-gradient(90deg, #7d26e8, #2969ff)',
  '--intergalactic-control-primary-feature-highlight-active': 'linear-gradient(90deg, #5a17a9, #1640a1)',
  '--intergalactic-control-secondary-feature-highlight': 'linear-gradient(90deg, #f5f1ff, #eef4ff)',
  '--intergalactic-control-secondary-feature-highlight-hover': 'linear-gradient(90deg, #e9d8ff, #dee9fe)',
  '--intergalactic-control-secondary-feature-highlight-active': 'linear-gradient(90deg, #e0c7ff, #d0e0fe)',
  '--intergalactic-text-feature-highlight': 'linear-gradient(90deg, #7d26e8, #2969ff)',
  '--intergalactic-text-feature-highlight-hover-active': 'linear-gradient(90deg, #350a69, #0a2564)',
  '--intergalactic-icon-primary-feature-highlight': '#7d26e8',
  '--intergalactic-icon-primary-feature-highlight-hover-active': '#6B3AB4',
  '--intergalactic-keyboard-focus-feature-highlight-outline': 'linear-gradient(90deg, #a070fe, #709bff)',
};
