export default {
  '--intergalactic-feature-highlight-bg-primary': 'rgba(30, 34, 49, 1)',
  '--intergalactic-feature-highlight-bg-primary-hover-active': 'linear-gradient(90deg, #f9f2ff, #e9f7ff)',
  '--intergalactic-feature-highlight-bg-secondary': 'linear-gradient(90deg, #f9f2ff, #e9f7ff)',
  '--intergalactic-feature-highlight-border': 'linear-gradient(90deg, #c695ff, #2bb3ff)',
  '--intergalactic-feature-highlight-border-active': 'linear-gradient(90deg, #ab6cfe, #008ff8)',
  '--intergalactic-feature-highlight-border-secondary': 'linear-gradient(90deg, #dcb8ff, #8ecdff)',
  '--intergalactic-feature-highlight-control-primary': 'linear-gradient(90deg, #ab6cfe, #008ff8)',
  '--intergalactic-feature-highlight-control-primary-hover': 'linear-gradient(90deg, #8649e1, #006dca)',
  '--intergalactic-feature-highlight-control-primary-active': 'linear-gradient(90deg, #5925ab, #044792)',
  '--intergalactic-feature-highlight-control-secondary': 'linear-gradient(90deg, #f9f2ff, #e9f7ff)',
  '--intergalactic-feature-highlight-control-secondary-hover': 'linear-gradient(90deg, #f2e4ff, #d6edfe)',
  '--intergalactic-feature-highlight-control-secondary-active': 'linear-gradient(90deg, #edd9ff, #c4e5fe)',
  '--intergalactic-feature-highlight-text': 'linear-gradient(90deg, #8649e1, #006dca)',
  '--intergalactic-feature-highlight-text-hover-active': 'linear-gradient(90deg, #421983, #002b5f)',
  '--intergalactic-feature-highlight-icon-primary': '#8649e1',
  '--intergalactic-feature-highlight-icon-primary-hover-active': '#6B3AB4',
  '--intergalactic-feature-highlight-keyboard-focus-outline': 'linear-gradient(90deg, #ab6cfe, #008ff8)',
};
