export default {
  '--gray-50': '#f7f8f9',
  '--gray-100': '#eaeff1',
  '--gray-200': '#d5dfe2',
  '--gray-300': '#b0c4c9',
  '--gray-400': '#85a2ab',
  '--gray-500': '#668791',
  '--gray-600': '#516e78',
  '--gray-700': '#425a62',
  '--gray-800': '#1e262a',
  '--gray-white': '#ffffff',
  '--blue-50': '#eaf0ff',
  '--blue-100': '#bdd1ff',
  '--blue-200': '#9dbaff',
  '--blue-300': '#709bff',
  '--blue-400': '#5487ff',
  '--blue-500': '#2969ff',
  '--blue-600': '#2560e8',
  '--blue-700': '#1d4bb5',
  '--blue-800': '#173a8c',
  '--green-50': '#ECF9EF',
  '--green-100': '#C4FFBA',
  '--green-200': '#A9E2B4',
  '--green-300': '#89FF75',
  '--green-400': '#69CD7D',
  '--green-500': '#44C15D',
  '--green-600': '#3EB055',
  '--green-700': '#308942',
  '--green-800': '#256A33',
  '--red-50': '#ffeaea',
  '--red-100': '#ffbdbd',
  '--red-200': '#ff9d9d',
  '--red-300': '#FF5454',
  '--red-400': '#ff5454',
  '--red-500': '#E82525',
  '--red-600': '#e82525',
  '--red-700': '#b51d1d',
  '--red-800': '#8c1717',
  '--orange-50': '#fff1ec',
  '--orange-100': '#ffd3c3',
  '--orange-200': '#ffbda5',
  '--orange-300': '#ff9f7c',
  '--orange-400': '#ff8d63',
  '--orange-500': '#ff703c',
  '--orange-600': '#e86637',
  '--orange-700': '#b5502b',
  '--orange-800': '#8c3e21',
  '--yellow-50': '#fff8ea',
  '--yellow-100': '#FFE09D',
  '--yellow-200': '#ffe09d',
  '--yellow-300': '#FFC954',
  '--yellow-400': '#ffc954',
  '--yellow-500': '#E89325',
  '--yellow-600': '#e8aa25',
  '--yellow-700': '#b5851d',
  '--yellow-800': '#8c6717',
  '--violet-50': '#f3eaff',
  '--violet-100': '#dabdff',
  '--violet-200': '#c99dff',
  '--violet-300': '#b070ff',
  '--violet-400': '#a155ff',
  '--violet-500': '#892aff',
  '--violet-600': '#7d26e8',
  '--violet-700': '#611eb5',
  '--violet-800': '#4b178c',
  '--violet-dusty-50': '#f5f4ff',
  '--violet-dusty-100': '#e2ddff',
  '--violet-dusty-200': '#bcb1e9',
  '--violet-dusty-300': '#a79cd6',
  '--violet-dusty-400': '#9083c5',
  '--violet-dusty-500': '#6d619f',
  '--violet-dusty-600': '#4d407e',
  '--violet-dusty-700': '#382e5e',
  '--violet-dusty-800': '#1d113e',
  '--pink-50': '#fff0ff',
  '--pink-100': '#ffd3ff',
  '--pink-200': '#ffa9fa',
  '--pink-300': '#ff87eb',
  '--pink-400': '#e14adf',
  '--pink-500': '#b229b9',
  '--pink-600': '#7d0480',
  '--pink-700': '#4d0050',
  '--pink-800': '#340439',
  '--salad-50': '#e8fef9',
  '--salad-100': '#b7faeb',
  '--salad-200': '#95f8e2',
  '--salad-300': '#64f5d4',
  '--salad-400': '#46f3cc',
  '--salad-500': '#18f0bf',
  '--salad-600': '#16daae',
  '--salad-700': '#11aa88',
  '--salad-800': '#0d8469',
  '--intergalactic-bg-primary-neutral': '#ffffff',
  '--intergalactic-bg-primary-neutral-hover': '#f7f8f9',
  '--intergalactic-bg-primary-neutral-active': '#eaeff1',
  '--intergalactic-bg-primary-info': '#5487ff',
  '--intergalactic-bg-primary-success': '#69CD7D',
  '--intergalactic-bg-primary-critical': '#ff5454',
  '--intergalactic-bg-primary-warning': '#ff8d63',
  '--intergalactic-bg-primary-highlight': '#FFE09D',
  '--intergalactic-bg-primary-advertising': '#611eb5',
  '--intergalactic-bg-primary-muted': '#668791',
  '--intergalactic-bg-primary-invert': '#1e262a',
  '--intergalactic-bg-primary-invert-hover': '#425a62',
  '--intergalactic-bg-primary-invert-active': '#516e78',
  '--intergalactic-bg-secondary-neutral': '#f7f8f9',
  '--intergalactic-bg-secondary-neutral-hover': '#eaeff1',
  '--intergalactic-bg-secondary-neutral-active': '#d5dfe2',
  '--intergalactic-bg-secondary-info': '#eaf0ff',
  '--intergalactic-bg-secondary-info-hover': '#bdd1ff',
  '--intergalactic-bg-secondary-info-active': '#9dbaff',
  '--intergalactic-bg-secondary-success': '#ECF9EF',
  '--intergalactic-bg-secondary-success-hover': '#C4FFBA',
  '--intergalactic-bg-secondary-success-active': '#A9E2B4',
  '--intergalactic-bg-secondary-critical': '#ffeaea',
  '--intergalactic-bg-secondary-critical-hover': '#ffbdbd',
  '--intergalactic-bg-secondary-critical-active': '#ff9d9d',
  '--intergalactic-bg-secondary-warning': '#fff1ec',
  '--intergalactic-bg-secondary-warning-hover': '#ffd3c3',
  '--intergalactic-bg-secondary-warning-active': '#ffbda5',
  '--intergalactic-bg-secondary-highlight': '#fff8ea',
  '--intergalactic-bg-secondary-highlight-hover': '#FFE09D',
  '--intergalactic-bg-secondary-highlight-active': '#ffe09d',
  '--intergalactic-bg-secondary-advertising': '#f3eaff',
  '--intergalactic-bg-secondary-advertising-hover': '#dabdff',
  '--intergalactic-bg-secondary-advertising-active': '#c99dff',
  '--intergalactic-bg-highlight-results': 'rgba(255, 201, 84, 0.4)',
  '--intergalactic-bg-highlight-focus': 'rgba(84, 135, 255, 0.2)',
  '--intergalactic-text-primary': '#1e262a',
  '--intergalactic-text-secondary': '#668791',
  '--intergalactic-text-placeholder': '#85a2ab',
  '--intergalactic-text-success': '#44C15D',
  '--intergalactic-text-success-hover-active': '#3EB055',
  '--intergalactic-text-critical': '#E82525',
  '--intergalactic-text-critical-hover-active': '#e82525',
  '--intergalactic-text-primary-invert': '#ffffff',
  '--intergalactic-text-secondary-invert': 'rgba(255, 255, 255, 0.8)',
  '--intergalactic-text-link': '#2969ff',
  '--intergalactic-text-link-hover-active': '#2560e8',
  '--intergalactic-text-link-invert': '#9dbaff',
  '--intergalactic-text-link-invert-hover': '#709bff',
  '--intergalactic-text-link-visited': '#892aff',
  '--intergalactic-text-hint': '#668791',
  '--intergalactic-text-hint-hover-active': '#516e78',
  '--intergalactic-text-hint-invert': '#d5dfe2',
  '--intergalactic-text-hint-invert-hover-active': '#b0c4c9',
  '--intergalactic-text-large-secondary': '#b0c4c9',
  '--intergalactic-text-large-info': '#5487ff',
  '--intergalactic-text-large-info-hover-active': '#2969ff',
  '--intergalactic-text-large-success': '#69CD7D',
  '--intergalactic-text-large-success-hover-active': '#44C15D',
  '--intergalactic-text-large-critical': '#ff5454',
  '--intergalactic-text-large-critical-hover-active': '#E82525',
  '--intergalactic-text-advertising': '#611eb5',
  '--intergalactic-border-primary': '#d5dfe2',
  '--intergalactic-border-secondary': '#eaeff1',
  '--intergalactic-border-info': '#9dbaff',
  '--intergalactic-border-info-active': '#1e262a',
  '--intergalactic-border-success': '#A9E2B4',
  '--intergalactic-border-success-active': '#44C15D',
  '--intergalactic-border-critical': '#ff9d9d',
  '--intergalactic-border-critical-active': '#E82525',
  '--intergalactic-border-warning': '#ffbda5',
  '--intergalactic-border-warning-active': '#ff703c',
  '--intergalactic-border-primary-invert': '#ffffff',
  '--intergalactic-border-secondary-invert': 'rgba(255, 255, 255, 0.3)',
  '--intergalactic-border-tooltip-invert': '#668791',
  '--intergalactic-border-table-accent': '#b0c4c9',
  '--intergalactic-border-date-picker-range-comparison': '#892aff',
  '--intergalactic-border-critical-pattern': 'repeating-linear-gradient(315deg, rgba(232, 37, 37, 1) 0, rgba(232, 37, 37, 1) 2px, transparent 0, transparent 50%)',
  '--intergalactic-control-switch-bg': '#b0c4c9',
  '--intergalactic-control-primary-info': '#1e262a',
  '--intergalactic-control-primary-info-hover': '#1e262a',
  '--intergalactic-control-primary-info-active': '#1e262a',
  '--intergalactic-control-primary-success': '#69CD7D',
  '--intergalactic-control-primary-success-hover': '#44C15D',
  '--intergalactic-control-primary-success-active': '#3EB055',
  '--intergalactic-control-primary-critical': '#ff5454',
  '--intergalactic-control-primary-critical-hover': '#E82525',
  '--intergalactic-control-primary-critical-active': '#e82525',
  '--intergalactic-control-primary-brand': '#ff8d63',
  '--intergalactic-control-primary-brand-hover': '#ff703c',
  '--intergalactic-control-primary-brand-active': '#e86637',
  '--intergalactic-control-primary-advertising': '#7d26e8',
  '--intergalactic-control-primary-advertising-hover': '#611eb5',
  '--intergalactic-control-primary-advertising-active': '#892aff',
  '--intergalactic-control-primary-invert': '#ffffff',
  '--intergalactic-control-primary-invert-hover': '#f7f8f9',
  '--intergalactic-control-primary-invert-active': '#eaeff1',
  '--intergalactic-control-secondary-neutral': 'rgba(133, 162, 171, 0.1)',
  '--intergalactic-control-secondary-neutral-hover': 'rgba(133, 162, 171, 0.2)',
  '--intergalactic-control-secondary-neutral-active': 'rgba(133, 162, 171, 0.3)',
  '--intergalactic-control-secondary-info': 'rgba(84, 135, 255, 0.1)',
  '--intergalactic-control-secondary-info-hover': 'rgba(84, 135, 255, 0.2)',
  '--intergalactic-control-secondary-info-active': 'rgba(84, 135, 255, 0.3)',
  '--intergalactic-control-secondary-invert': 'rgba(255, 255, 255, 0.05)',
  '--intergalactic-control-secondary-invert-hover': 'rgba(255, 255, 255, 0.1)',
  '--intergalactic-control-secondary-invert-active': 'rgba(255, 255, 255, 0.3)',
  '--intergalactic-control-tertiary-neutral': 'rgba(133, 162, 171, 0)',
  '--intergalactic-control-tertiary-neutral-hover': 'rgba(133, 162, 171, 0.2)',
  '--intergalactic-control-tertiary-neutral-active': 'rgba(133, 162, 171, 0.3)',
  '--intergalactic-control-tertiary-info': 'rgba(84, 135, 255, 0)',
  '--intergalactic-control-tertiary-info-hover': 'rgba(84, 135, 255, 0.2)',
  '--intergalactic-control-tertiary-info-active': 'rgba(84, 135, 255, 0.3)',
  '--intergalactic-control-tertiary-invert': 'rgba(255, 255, 255, 0)',
  '--intergalactic-control-tertiary-invert-hover': 'rgba(255, 255, 255, 0.1)',
  '--intergalactic-control-tertiary-invert-active': 'rgba(255, 255, 255, 0.3)',
  '--intergalactic-icon-primary-neutral': '#668791',
  '--intergalactic-icon-primary-neutral-hover-active': '#565861',
  '--intergalactic-icon-primary-info': '#2969ff',
  '--intergalactic-icon-primary-info-hover-active': '#0358a1',
  '--intergalactic-icon-primary-success': '#69CD7D',
  '--intergalactic-icon-primary-success-hover-active': '#037e68',
  '--intergalactic-icon-primary-critical': '#ff5454',
  '--intergalactic-icon-primary-critical-hover-active': '#cc3a42',
  '--intergalactic-icon-primary-warning': '#ff8d63',
  '--intergalactic-icon-primary-warning-hover-active': '#cc5024',
  '--intergalactic-icon-primary-invert': '#ffffff',
  '--intergalactic-icon-primary-invert-hover-active': '#eaeff1',
  '--intergalactic-icon-secondary-neutral': '#b0c4c9',
  '--intergalactic-icon-secondary-neutral-hover-active': '#878992',
  '--intergalactic-icon-secondary-info': '#709bff',
  '--intergalactic-icon-secondary-info-hover-active': '#2290cc',
  '--intergalactic-icon-secondary-success': '#89FF75',
  '--intergalactic-icon-secondary-success-hover-active': '#049b75',
  '--intergalactic-icon-secondary-critical': '#FF5454',
  '--intergalactic-icon-secondary-critical-hover-active': '#cc6c6b',
  '--intergalactic-icon-secondary-warning': '#ff9f7c',
  '--intergalactic-icon-secondary-warning-hover-active': '#cc7036',
  '--intergalactic-icon-non-interactive': '#1e262a',
  '--intergalactic-illustration-red': '#ff788f',
  '--intergalactic-illustration-orange': '#ff9400',
  '--intergalactic-illustration-yellow': '#ffe84d',
  '--intergalactic-illustration-salad': '#c7fa73',
  '--intergalactic-illustration-green': '#45e0a8',
  '--intergalactic-illustration-blue': '#6edbff',
  '--intergalactic-illustration-violet': '#b880ff',
  '--intergalactic-illustration-pink': '#ff7ad1',
  '--intergalactic-date-picker-cell': '#ffffff',
  '--intergalactic-date-picker-cell-current': '#85a2ab',
  '--intergalactic-date-picker-cell-hover': '#eaeff1',
  '--intergalactic-date-picker-cell-range': '#bdd1ff',
  '--intergalactic-date-picker-cell-range-hover': '#9dbaff',
  '--intergalactic-date-picker-cell-active': '#709bff',
  '--intergalactic-date-picker-cell-active-hover': '#5487ff',
  '--intergalactic-date-picker-cell-current-invert': 'rgba(255, 255, 255, 0.5)',
  '--intergalactic-date-picker-cell-comparison-active': '#892aff',
  '--intergalactic-date-picker-cell-comparison-active-hover': '#7d26e8',
  '--intergalactic-dropdown-menu-item': '#ffffff',
  '--intergalactic-dropdown-menu-item-hover': '#f7f8f9',
  '--intergalactic-dropdown-menu-item-selected': 'rgba(189, 209, 255, 0.7)',
  '--intergalactic-dropdown-menu-item-selected-hover': '#bdd1ff',
  '--intergalactic-feature-popover-bg': '#FFE09D',
  '--intergalactic-feature-popover-dot-outer-border': '#FFE09D',
  '--intergalactic-feature-popover-bg-neutral': '#1d113e',
  '--intergalactic-feature-popover-dot-neutral': '#89FF75',
  '--intergalactic-feature-popover-dot-neutral-outer-border': '#89FF75',
  '--intergalactic-progress-bar-bg': '#eaeff1',
  '--intergalactic-progress-bar-bg-hover': '#d5dfe2',
  '--intergalactic-progress-bar-bg-invert': 'rgba(255, 255, 255, 0.2)',
  '--intergalactic-progress-bar-bg-invert-hover': 'rgba(255, 255, 255, 0.4)',
  '--intergalactic-progress-bar-value-gradient': 'linear-gradient(-45deg, rgba(68, 193, 93, 0.9) 25%, rgba(68, 193, 93, 1) 0%, rgba(68, 193, 93, 1) 50%, rgba(68, 193, 93, 0.9) 0%, rgba(68, 193, 93, 0.9) 75%, rgba(68, 193, 93, 1) 0%)',
  '--intergalactic-progress-bar-pattern-gradient': 'linear-gradient(-45deg, rgba(234, 239, 241, 0.9) 25%, rgba(234, 239, 241, 1) 0%, rgba(234, 239, 241, 1) 50%, rgba(234, 239, 241, 0.9) 0%, rgba(234, 239, 241, 0.9) 75%, rgba(234, 239, 241, 1) 0%)',
  '--intergalactic-progress-bar-value-bg': '#000000',
  '--intergalactic-skeleton-bg': 'rgba(234, 239, 241, 0.8)',
  '--intergalactic-skeleton-bg-invert': 'rgba(255, 255, 255, 0.3)',
  '--intergalactic-slider-rating-normal': '#b0c4c9',
  '--intergalactic-slider-rating-hover-active': '#ffe09d',
  '--intergalactic-table-th-primary-cell': '#f7f8f9',
  '--intergalactic-table-th-primary-cell-hover': '#eaeff1',
  '--intergalactic-table-th-primary-cell-active': '#eaeff1',
  '--intergalactic-table-th-secondary-cell': '#ffffff',
  '--intergalactic-table-th-gradient': 'linear-gradient(to right, rgba(234, 239, 241, 0) 0%, rgba(234, 239, 241, 1) 100%)',
  '--intergalactic-table-td-cell': '#ffffff',
  '--intergalactic-table-td-cell-hover': '#f4f7f8',
  '--intergalactic-table-td-cell-active': '#eef2f4',
  '--intergalactic-table-td-cell-unread': '#f7f8f9',
  '--intergalactic-table-td-cell-accordion': '#f7f8f9',
  '--intergalactic-table-td-cell-selected': '#eaf0ff',
  '--intergalactic-table-td-cell-selected-hover': '#bdd1ff',
  '--intergalactic-table-td-cell-selected-active': '#bdd1ff',
  '--intergalactic-table-td-cell-new': '#ECF9EF',
  '--intergalactic-table-td-cell-new-hover': '#C4FFBA',
  '--intergalactic-table-td-cell-new-active': '#C4FFBA',
  '--intergalactic-table-td-cell-critical': '#ffeaea',
  '--intergalactic-table-td-cell-critical-hover': '#ffbdbd',
  '--intergalactic-table-td-cell-critical-active': '#ffbdbd',
  '--intergalactic-table-td-cell-warning': '#fff1ec',
  '--intergalactic-table-td-cell-warning-hover': '#ffd3c3',
  '--intergalactic-table-td-cell-warning-active': '#ffd3c3',
  '--intergalactic-brand-primary': '#ff8d63',
  '--intergalactic-brand-secondary': '#611eb5',
  '--intergalactic-brand-pinterest': '#bd081c',
  '--intergalactic-brand-instagram': '#e4405f',
  '--intergalactic-brand-youtube': '#ff0000',
  '--intergalactic-brand-facebook': '#1877f2',
  '--intergalactic-brand-linkedIn': '#0a66c2',
  '--intergalactic-brand-twitter': '#1d9bf0',
  '--intergalactic-brand-google-blue': '#1a0dab',
  '--intergalactic-brand-google-green': '#016723',
  '--intergalactic-brand-google-my-business': '#1a73e8',
  '--intergalactic-box-shadow-card': '0 0 0 1px #eaeff1',
  '--intergalactic-box-shadow-card-hover': '3px 3px 30px 0px rgba(30, 38, 42, 0.15)',
  '--intergalactic-box-shadow-dnd': '0px 0px 1px 0px rgba(30, 38, 42, 0.16), 0px 12px 40px 0px rgba(30, 38, 42, 0.16)',
  '--intergalactic-box-shadow-modal': '0px 3px 8px 0px rgba(30, 38, 42, 0.2)',
  '--intergalactic-box-shadow-popper': '0px 1px 12px 0px rgba(30, 38, 42, 0.15)',
  '--intergalactic-keyboard-focus-outline': '#1e262a',
  '--intergalactic-keyboard-focus-invalid-outline': '#ff5454',
  '--intergalactic-keyboard-focus-invalid': '0px 0px 0px 3px rgba(255, 84, 84, 0.5)',
  '--intergalactic-keyboard-focus-valid-outline': '#69CD7D',
  '--intergalactic-keyboard-focus-valid': '0px 0px 0px 3px rgba(105, 205, 125, 0.5)',
  '--intergalactic-keyboard-focus-invert-outline': 'rgba(255, 255, 255, 0.8)',
  '--intergalactic-keyboard-focus-invert': '0px 0px 0px 3px rgba(255, 255, 255, 0.8)',
  '--intergalactic-keyboard-focus': '0px 0px 0px 3px rgba(30, 38, 42, 0.5)',
  '--intergalactic-base': 'Inter',
  '--intergalactic-lh-800': '117%',
  '--intergalactic-lh-700': '110%',
  '--intergalactic-lh-600': '125%',
  '--intergalactic-lh-500': '117%',
  '--intergalactic-lh-400': '120%',
  '--intergalactic-lh-300': '150%',
  '--intergalactic-lh-200': '142%',
  '--intergalactic-lh-100': '133%',
  '--intergalactic-semi-bold': '600',
  '--intergalactic-bold': '700',
  '--intergalactic-regular': '400',
  '--intergalactic-medium': '500',
  '--intergalactic-fs-50': '10px',
  '--intergalactic-fs-100': '12px',
  '--intergalactic-fs-200': '14px',
  '--intergalactic-fs-300': '16px',
  '--intergalactic-fs-400': '20px',
  '--intergalactic-fs-500': '24px',
  '--intergalactic-fs-600': '32px',
  '--intergalactic-fs-700': '36px',
  '--intergalactic-fs-800': '48px',
  '--intergalactic-compact': '0.3',
  '--intergalactic-scale-indent': '4px',
  '--intergalactic-form-control-s': '20px',
  '--intergalactic-form-control-m': '28px',
  '--intergalactic-form-control-l': '40px',
  '--intergalactic-spacing-05x': '2px',
  '--intergalactic-spacing-1x': '4px',
  '--intergalactic-spacing-2x': '8px',
  '--intergalactic-spacing-3x': '12px',
  '--intergalactic-spacing-4x': '16px',
  '--intergalactic-spacing-5x': '20px',
  '--intergalactic-spacing-6x': '24px',
  '--intergalactic-spacing-8x': '32px',
  '--intergalactic-spacing-10x': '40px',
  '--intergalactic-spacing-14x': '56px',
  '--intergalactic-spacing-20x': '80px',
  '--intergalactic-spacing-24x': '96px',
  '--intergalactic-spacing-30x': '120px',
  '--intergalactic-rounded-extra-small': '2px',
  '--intergalactic-rounded-small': '4px',
  '--intergalactic-rounded-medium': '6px',
  '--intergalactic-rounded-large': '12px',
  '--intergalactic-rounded-extra-large': '24px',
  '--intergalactic-addon-rounded': '4px',
  '--intergalactic-badge-rounded': '6px',
  '--intergalactic-chart-rounded': '2px',
  '--intergalactic-counter-rounded': '12px',
  '--intergalactic-tag-rounded': '24px',
  '--intergalactic-switch-rounded': '24px',
  '--intergalactic-control-rounded': '6px',
  '--intergalactic-progress-bar-rounded': '6px',
  '--intergalactic-surface-rounded': '6px',
  '--intergalactic-popper-rounded': '6px',
  '--intergalactic-modal-rounded': '12px',
  '--intergalactic-disabled-opacity': '0.5',
  '--intergalactic-screen-extra-small': '320px',
  '--intergalactic-screen-small': '768px',
  '--intergalactic-screen-medium': '1200px',
  '--intergalactic-screen-large': '1920px',
  '--intergalactic-overlay-primary': 'rgba(30, 38, 42, 0.7)',
  '--intergalactic-overlay-secondary': 'rgba(30, 38, 42, 0.4)',
  '--intergalactic-overlay-limitation-primary': '#f7f8f9',
  '--intergalactic-overlay-limitation-secondary': 'rgba(255, 255, 255, 0.85)',
  '--intergalactic-z-index-deep': '-999',
  '--intergalactic-z-index-overlay': '500',
  '--intergalactic-z-index-modal': '900',
  '--intergalactic-z-index-popper': '700',
  '--intergalactic-z-index-dropdown': '750',
  '--intergalactic-z-index-tooltip': '800',
  '--intergalactic-z-index-notice-bubble': '999',
  '--intergalactic-tooltip-default': '#ffffff',
  '--intergalactic-tooltip-warning': '#ffbdbd',
  '--intergalactic-tooltip-invert': '#1e262a',
  '--intergalactic-neighbor-location-neutral': '#ffffff80',
  '--intergalactic-neighbor-location-invert': '#00000080',
  '--intergalactic-scroll-area-shadow-left': 'linear-gradient(to right, rgba(30, 38, 42, 0.1) 20.55%, rgba(255, 255, 255, 0.0001) 100%)',
  '--intergalactic-scroll-area-shadow-right': 'linear-gradient(to left, rgba(30, 38, 42, 0.1) 20.55%, rgba(255, 255, 255, 0.0001) 100%)',
  '--intergalactic-scroll-area-shadow-top': 'linear-gradient(to bottom, rgba(30, 38, 42, 0.1) 20.55%, rgba(255, 255, 255, 0.0001) 100%)',
  '--intergalactic-scroll-area-shadow-bottom': 'linear-gradient(to top, rgba(30, 38, 42, 0.1) 20.55%, rgba(255, 255, 255, 0.0001) 100%)',
  '--intergalactic-scroll-area-dropdown-menu-left': 'linear-gradient(to right, rgba(255, 255, 255, 1) 34.38%, rgba(255, 255, 255, 0) 100%)',
  '--intergalactic-scroll-area-dropdown-menu-right': 'linear-gradient(to left, rgba(255, 255, 255, 1) 34.38%, rgba(255, 255, 255, 0) 100%)',
  '--intergalactic-scroll-area-dropdown-menu-bottom': 'linear-gradient(to top, rgba(255, 255, 255, 1) 34.38%, rgba(255, 255, 255, 0) 100%)',
  '--intergalactic-scroll-area-dropdown-menu-top': 'linear-gradient(to bottom, rgba(255, 255, 255, 1) 34.38%, rgba(255, 255, 255, 0) 100%)',
  '--intergalactic-scroll-bar-background': 'rgba(30, 38, 42, 0.3)',
  '--intergalactic-tag-primary-gray-normal': '#ecedf0',
  '--intergalactic-tag-primary-gray-hover-active': '#e3e4e9',
  '--intergalactic-tag-primary-blue-normal': '#d0eeff',
  '--intergalactic-tag-primary-blue-hover-active': '#b7e4ff',
  '--intergalactic-tag-primary-green-normal': '#cff1ea',
  '--intergalactic-tag-primary-green-hover-active': '#b7eae0',
  '--intergalactic-tag-primary-orange-normal': '#ffddd2',
  '--intergalactic-tag-primary-orange-hover-active': '#ffccbb',
  '--intergalactic-tag-primary-red-normal': '#ffcedc',
  '--intergalactic-tag-primary-red-hover-active': '#ffb6ca',
  '--intergalactic-tag-primary-violet-normal': '#f4e3ff',
  '--intergalactic-tag-primary-violet-hover-active': '#efd5ff',
  '--intergalactic-tag-primary-yellow-normal': '#fee6d1',
  '--intergalactic-tag-primary-yellow-hover-active': '#fedab9',
  '--intergalactic-tag-primary-white-normal': 'rgba(255, 255, 255, 0.15)',
  '--intergalactic-tag-primary-white-hover-active': 'rgba(255, 255, 255, 0.3)',
  '--intergalactic-tag-primary-gray-text': '#668791',
  '--intergalactic-tag-primary-blue-text': '#2969ff',
  '--intergalactic-tag-primary-green-text': '#44C15D',
  '--intergalactic-tag-primary-orange-text': '#ff703c',
  '--intergalactic-tag-primary-red-text': '#E82525',
  '--intergalactic-tag-primary-violet-text': '#892aff',
  '--intergalactic-tag-primary-yellow-text': '#E89325',
  '--intergalactic-tag-primary-white-text': '#ffffff',
  '--intergalactic-tag-secondary-normal': '#ffffff',
  '--intergalactic-tag-secondary-hover-active': '#f7f8f9',
  '--intergalactic-tag-secondary-white-normal': 'rgba(255, 255, 255, 0)',
  '--intergalactic-tag-secondary-white-hover-active': 'rgba(255, 255, 255, 0.1)',
  '--intergalactic-tag-secondary-gray-text': '#668791',
  '--intergalactic-tag-secondary-white-text': '#ffffff',
  '--intergalactic-chart-palette-order-1': '#709bff',
  '--intergalactic-chart-palette-order-2': '#A9E2B4',
  '--intergalactic-chart-palette-order-3': '#ff8d63',
  '--intergalactic-chart-palette-order-4': '#ff87eb',
  '--intergalactic-chart-palette-order-5': '#ffe09d',
  '--intergalactic-chart-palette-order-6': '#a155ff',
  '--intergalactic-chart-palette-order-7': '#FF5454',
  '--intergalactic-chart-palette-order-8': '#95f8e2',
  '--intergalactic-chart-palette-order-9': '#5487ff',
  '--intergalactic-chart-palette-order-10': '#89FF75',
  '--intergalactic-chart-palette-order-11': '#ffbda5',
  '--intergalactic-chart-palette-order-12': '#e14adf',
  '--intergalactic-chart-palette-order-13': '#FFC954',
  '--intergalactic-chart-palette-order-14': '#c99dff',
  '--intergalactic-chart-palette-order-15': '#ff5454',
  '--intergalactic-chart-palette-order-16': '#64f5d4',
  '--intergalactic-chart-palette-order-17': '#9dbaff',
  '--intergalactic-chart-palette-order-18': '#69CD7D',
  '--intergalactic-chart-palette-order-19': '#ff9f7c',
  '--intergalactic-chart-palette-order-20': '#ffa9fa',
  '--intergalactic-chart-palette-order-21': '#ffc954',
  '--intergalactic-chart-palette-order-22': '#b070ff',
  '--intergalactic-chart-palette-order-23': '#ff9d9d',
  '--intergalactic-chart-palette-order-24': '#46f3cc',
  '--intergalactic-chart-palette-order-total-amount': '#85a2ab',
  '--intergalactic-chart-palette-order-other-data': '#d5dfe2',
  '--intergalactic-chart-palette-order-null': '#eaeff1',
  '--intergalactic-chart-grid-line': '#eaeff1',
  '--intergalactic-chart-grid-x-axis': '#d5dfe2',
  '--intergalactic-chart-grid-y-accent-hover-line': '#b0c4c9',
  '--intergalactic-chart-grid-text-label': '#668791',
  '--intergalactic-chart-grid-bar-chart-hover': 'rgba(213, 223, 226, 0.3)',
  '--intergalactic-chart-grid-bar-chart-base-bg': '#eaeff1',
  '--intergalactic-chart-grid-period-bg': 'rgba(213, 223, 226, 0.2)',
  '--intergalactic-chart-grid-period-pattern': 'rgba(30, 38, 42, 0.15)',
  '--intergalactic-chart-grid-border': '#ffffff',
  '--intergalactic-chart-x-axis-accent-period-active': '#668791',
  '--intergalactic-chart-x-axis-accent-data-start-tracking': 'rgba(105, 205, 125, 0.2)',
  '--intergalactic-header-bg': '#382e5e',
  '--intergalactic-header-border-primary': '#382e5e',
  '--intergalactic-header-border-secondary': '#ffffff26',
  '--intergalactic-sidebar-nav-control-hover': 'rgba(234, 239, 241, 0.7)',
  '--intergalactic-sidebar-nav-control-active': '#e2ddff',
  '--intergalactic-sidebar-nav-control-text-normal': '#6d619f',
  '--intergalactic-sidebar-nav-control-text-active': '#4d407e',
  '--intergalactic-sidebar-nav-control-icon-normal': '#9083c5',
  '--intergalactic-sidebar-nav-control-icon-active': '#4d407e',
  '--intergalactic-duration-extra-slow': '500',
  '--intergalactic-duration-slow': '400',
  '--intergalactic-duration-medium': '300',
  '--intergalactic-duration-fast': '200',
  '--intergalactic-duration-extra-fast': '100',
  '--intergalactic-duration-switch': '100',
  '--intergalactic-duration-popper': '200',
  '--intergalactic-duration-control': '200',
  '--intergalactic-duration-modal': '200',
  '--intergalactic-duration-accordion': '200',
  '--intergalactic-duration-counter': '200',
};
