export default {
  '--gray-50': '#f3f4f4',
  '--gray-100': '#dedfe2',
  '--gray-200': '#c4c5ca',
  '--gray-300': '#a9aab1',
  '--gray-400': '#90929a',
  '--gray-500': '#6c6e79',
  '--gray-600': '#484a52',
  '--gray-700': '#2f3035',
  '--gray-800': '#131416',
  '--gray-white': '#ffffff',
  '--blue-50': '#eef4ff',
  '--blue-100': '#d0e0fe',
  '--blue-200': '#aac6fb',
  '--blue-300': '#83aaf7',
  '--blue-400': '#5e8ef2',
  '--blue-500': '#2661e8',
  '--blue-600': '#1640a1',
  '--blue-700': '#0e2a6a',
  '--blue-800': '#08183c',
  '--green-50': '#dcfdf0',
  '--green-100': '#9df4d7',
  '--green-200': '#48e3b8',
  '--green-300': '#35c59f',
  '--green-400': '#2a8',
  '--green-500': '#0a8266',
  '--green-600': '#075844',
  '--green-700': '#033427',
  '--green-800': '#021912',
  '--red-50': '#ffefec',
  '--red-100': '#ffd0c8',
  '--red-200': '#ffa79a',
  '--red-300': '#ff786b',
  '--red-400': '#ff3f38',
  '--red-500': '#ca201f',
  '--red-600': '#8b1312',
  '--red-700': '#550807',
  '--red-800': '#2c0202',
  '--orange-50': '#ffefe9',
  '--orange-100': '#ffd4c6',
  '--orange-200': '#fcb097',
  '--orange-300': '#f48a66',
  '--orange-400': '#ea622f',
  '--orange-500': '#b4481e',
  '--orange-600': '#7b2f13',
  '--orange-700': '#4a1a09',
  '--orange-800': '#260a02',
  '--yellow-50': '#fff2d7',
  '--yellow-100': '#ffd997',
  '--yellow-200': '#fbb829',
  '--yellow-300': '#da9f21',
  '--yellow-400': '#bb881c',
  '--yellow-500': '#8e6711',
  '--yellow-600': '#614509',
  '--yellow-700': '#3a2803',
  '--yellow-800': '#1d1201',
  '--violet-50': '#f5f1ff',
  '--violet-100': '#e2d8ff',
  '--violet-200': '#cbb7ff',
  '--violet-300': '#b494ff',
  '--violet-400': '#a070fe',
  '--violet-500': '#8426f5',
  '--violet-600': '#5a17a9',
  '--violet-700': '#350a69',
  '--violet-800': '#1a0239',
  '--violet-dusty-50': '#f1f5f4',
  '--violet-dusty-100': '#d8e2e1',
  '--violet-dusty-200': '#b8cac8',
  '--violet-dusty-300': '#96b1af',
  '--violet-dusty-400': '#7b9996',
  '--violet-dusty-500': '#5c7472',
  '--violet-dusty-600': '#3e4e4d',
  '--violet-dusty-700': '#232e2d',
  '--violet-dusty-800': '#0f1515',
  '--pink-50': '#fff0ff',
  '--pink-100': '#ffd3ff',
  '--pink-200': '#ffa9fa',
  '--pink-300': '#ff87eb',
  '--pink-400': '#e14adf',
  '--pink-500': '#b229b9',
  '--pink-600': '#7d0480',
  '--pink-700': '#4d0050',
  '--pink-800': '#340439',
  '--salad-50': '#e8fef9',
  '--salad-100': '#b7faeb',
  '--salad-200': '#95f8e2',
  '--salad-300': '#64f5d4',
  '--salad-400': '#46f3cc',
  '--salad-500': '#18f0bf',
  '--salad-600': '#16daae',
  '--salad-700': '#11aa88',
  '--salad-800': '#0d8469',
  '--intergalactic-bg-primary-neutral': '#ffffff',
  '--intergalactic-bg-primary-neutral-hover': '#f3f4f4',
  '--intergalactic-bg-primary-neutral-active': '#dedfe2',
  '--intergalactic-bg-primary-info': '#5e8ef2',
  '--intergalactic-bg-primary-success': '#2a8',
  '--intergalactic-bg-primary-critical': '#ff3f38',
  '--intergalactic-bg-primary-warning': '#ea622f',
  '--intergalactic-bg-primary-highlight': '#ffd997',
  '--intergalactic-bg-primary-advertising': '#350a69',
  '--intergalactic-bg-primary-muted': '#6c6e79',
  '--intergalactic-bg-primary-invert': '#131416',
  '--intergalactic-bg-primary-invert-hover': '#2f3035',
  '--intergalactic-bg-primary-invert-active': '#484a52',
  '--intergalactic-bg-secondary-neutral': '#f3f4f4',
  '--intergalactic-bg-secondary-neutral-hover': '#dedfe2',
  '--intergalactic-bg-secondary-neutral-active': '#c4c5ca',
  '--intergalactic-bg-secondary-info': '#eef4ff',
  '--intergalactic-bg-secondary-info-hover': '#d0e0fe',
  '--intergalactic-bg-secondary-info-active': '#aac6fb',
  '--intergalactic-bg-secondary-success': '#dcfdf0',
  '--intergalactic-bg-secondary-success-hover': '#9df4d7',
  '--intergalactic-bg-secondary-success-active': '#48e3b8',
  '--intergalactic-bg-secondary-critical': '#ffefec',
  '--intergalactic-bg-secondary-critical-hover': '#ffd0c8',
  '--intergalactic-bg-secondary-critical-active': '#ffa79a',
  '--intergalactic-bg-secondary-warning': '#ffefe9',
  '--intergalactic-bg-secondary-warning-hover': '#ffd4c6',
  '--intergalactic-bg-secondary-warning-active': '#fcb097',
  '--intergalactic-bg-secondary-highlight': '#fff2d7',
  '--intergalactic-bg-secondary-highlight-hover': '#ffd997',
  '--intergalactic-bg-secondary-highlight-active': '#fbb829',
  '--intergalactic-bg-secondary-advertising': '#f5f1ff',
  '--intergalactic-bg-secondary-advertising-hover': '#e2d8ff',
  '--intergalactic-bg-secondary-advertising-active': '#cbb7ff',
  '--intergalactic-bg-highlight-results': 'rgba(218, 159, 33, 0.4)',
  '--intergalactic-bg-highlight-focus': 'rgba(94, 142, 242, 0.2)',
  '--intergalactic-text-primary': '#131416',
  '--intergalactic-text-secondary': '#6c6e79',
  '--intergalactic-text-placeholder': '#90929a',
  '--intergalactic-text-success': '#0a8266',
  '--intergalactic-text-success-hover-active': '#075844',
  '--intergalactic-text-critical': '#ca201f',
  '--intergalactic-text-critical-hover-active': '#8b1312',
  '--intergalactic-text-primary-invert': '#ffffff',
  '--intergalactic-text-secondary-invert': 'rgba(255, 255, 255, 0.8)',
  '--intergalactic-text-link': '#2661e8',
  '--intergalactic-text-link-hover-active': '#1640a1',
  '--intergalactic-text-link-invert': '#aac6fb',
  '--intergalactic-text-link-invert-hover': '#83aaf7',
  '--intergalactic-text-link-visited': '#8426f5',
  '--intergalactic-text-hint': '#6c6e79',
  '--intergalactic-text-hint-hover-active': '#484a52',
  '--intergalactic-text-hint-invert': '#c4c5ca',
  '--intergalactic-text-hint-invert-hover-active': '#a9aab1',
  '--intergalactic-text-large-secondary': '#a9aab1',
  '--intergalactic-text-large-info': '#5e8ef2',
  '--intergalactic-text-large-info-hover-active': '#2661e8',
  '--intergalactic-text-large-success': '#2a8',
  '--intergalactic-text-large-success-hover-active': '#0a8266',
  '--intergalactic-text-large-critical': '#ff3f38',
  '--intergalactic-text-large-critical-hover-active': '#ca201f',
  '--intergalactic-text-advertising': '#350a69',
  '--intergalactic-border-primary': '#c4c5ca',
  '--intergalactic-border-secondary': '#dedfe2',
  '--intergalactic-border-info': '#aac6fb',
  '--intergalactic-border-info-active': '#131416',
  '--intergalactic-border-success': '#48e3b8',
  '--intergalactic-border-success-active': '#0a8266',
  '--intergalactic-border-critical': '#ffa79a',
  '--intergalactic-border-critical-active': '#ca201f',
  '--intergalactic-border-warning': '#fcb097',
  '--intergalactic-border-warning-active': '#b4481e',
  '--intergalactic-border-primary-invert': '#ffffff',
  '--intergalactic-border-secondary-invert': 'rgba(255, 255, 255, 0.3)',
  '--intergalactic-border-tooltip-invert': '#6c6e79',
  '--intergalactic-border-table-accent': '#a9aab1',
  '--intergalactic-border-date-picker-range-comparison': '#8426f5',
  '--intergalactic-border-critical-pattern': 'repeating-linear-gradient(315deg, rgba(202, 32, 31, 1) 0, rgba(202, 32, 31, 1) 2px, transparent 0, transparent 50%)',
  '--intergalactic-control-switch-bg': '#a9aab1',
  '--intergalactic-control-primary-info': '#131416',
  '--intergalactic-control-primary-info-hover': '#131416',
  '--intergalactic-control-primary-info-active': '#131416',
  '--intergalactic-control-primary-success': '#2a8',
  '--intergalactic-control-primary-success-hover': '#0a8266',
  '--intergalactic-control-primary-success-active': '#075844',
  '--intergalactic-control-primary-critical': '#ff3f38',
  '--intergalactic-control-primary-critical-hover': '#ca201f',
  '--intergalactic-control-primary-critical-active': '#8b1312',
  '--intergalactic-control-primary-brand': '#ea622f',
  '--intergalactic-control-primary-brand-hover': '#b4481e',
  '--intergalactic-control-primary-brand-active': '#7b2f13',
  '--intergalactic-control-primary-advertising': '#5a17a9',
  '--intergalactic-control-primary-advertising-hover': '#350a69',
  '--intergalactic-control-primary-advertising-active': '#8426f5',
  '--intergalactic-control-primary-invert': '#ffffff',
  '--intergalactic-control-primary-invert-hover': '#f3f4f4',
  '--intergalactic-control-primary-invert-active': '#dedfe2',
  '--intergalactic-control-secondary-neutral': 'rgba(144, 146, 154, 0.1)',
  '--intergalactic-control-secondary-neutral-hover': 'rgba(144, 146, 154, 0.2)',
  '--intergalactic-control-secondary-neutral-active': 'rgba(144, 146, 154, 0.3)',
  '--intergalactic-control-secondary-info': 'rgba(94, 142, 242, 0.1)',
  '--intergalactic-control-secondary-info-hover': 'rgba(94, 142, 242, 0.2)',
  '--intergalactic-control-secondary-info-active': 'rgba(94, 142, 242, 0.3)',
  '--intergalactic-control-secondary-invert': 'rgba(255, 255, 255, 0.05)',
  '--intergalactic-control-secondary-invert-hover': 'rgba(255, 255, 255, 0.1)',
  '--intergalactic-control-secondary-invert-active': 'rgba(255, 255, 255, 0.3)',
  '--intergalactic-control-tertiary-neutral': 'rgba(144, 146, 154, 0)',
  '--intergalactic-control-tertiary-neutral-hover': 'rgba(144, 146, 154, 0.2)',
  '--intergalactic-control-tertiary-neutral-active': 'rgba(144, 146, 154, 0.3)',
  '--intergalactic-control-tertiary-info': 'rgba(94, 142, 242, 0)',
  '--intergalactic-control-tertiary-info-hover': 'rgba(94, 142, 242, 0.2)',
  '--intergalactic-control-tertiary-info-active': 'rgba(94, 142, 242, 0.3)',
  '--intergalactic-control-tertiary-invert': 'rgba(255, 255, 255, 0)',
  '--intergalactic-control-tertiary-invert-hover': 'rgba(255, 255, 255, 0.1)',
  '--intergalactic-control-tertiary-invert-active': 'rgba(255, 255, 255, 0.3)',
  '--intergalactic-icon-primary-neutral': '#6c6e79',
  '--intergalactic-icon-primary-neutral-hover-active': '#565861',
  '--intergalactic-icon-primary-info': '#2661e8',
  '--intergalactic-icon-primary-info-hover-active': '#0358a1',
  '--intergalactic-icon-primary-success': '#2a8',
  '--intergalactic-icon-primary-success-hover-active': '#037e68',
  '--intergalactic-icon-primary-critical': '#ff3f38',
  '--intergalactic-icon-primary-critical-hover-active': '#cc3a42',
  '--intergalactic-icon-primary-warning': '#ea622f',
  '--intergalactic-icon-primary-warning-hover-active': '#cc5024',
  '--intergalactic-icon-primary-invert': '#ffffff',
  '--intergalactic-icon-primary-invert-hover-active': '#dedfe2',
  '--intergalactic-icon-secondary-neutral': '#a9aab1',
  '--intergalactic-icon-secondary-neutral-hover-active': '#878992',
  '--intergalactic-icon-secondary-info': '#83aaf7',
  '--intergalactic-icon-secondary-info-hover-active': '#2290cc',
  '--intergalactic-icon-secondary-success': '#35c59f',
  '--intergalactic-icon-secondary-success-hover-active': '#049b75',
  '--intergalactic-icon-secondary-critical': '#ff786b',
  '--intergalactic-icon-secondary-critical-hover-active': '#cc6c6b',
  '--intergalactic-icon-secondary-warning': '#f48a66',
  '--intergalactic-icon-secondary-warning-hover-active': '#cc7036',
  '--intergalactic-icon-non-interactive': '#131416',
  '--intergalactic-illustration-red': '#ff788f',
  '--intergalactic-illustration-orange': '#ff9400',
  '--intergalactic-illustration-yellow': '#ffe84d',
  '--intergalactic-illustration-salad': '#c7fa73',
  '--intergalactic-illustration-green': '#45e0a8',
  '--intergalactic-illustration-blue': '#6edbff',
  '--intergalactic-illustration-violet': '#b880ff',
  '--intergalactic-illustration-pink': '#ff7ad1',
  '--intergalactic-date-picker-cell': '#ffffff',
  '--intergalactic-date-picker-cell-current': '#90929a',
  '--intergalactic-date-picker-cell-hover': '#dedfe2',
  '--intergalactic-date-picker-cell-range': '#d0e0fe',
  '--intergalactic-date-picker-cell-range-hover': '#aac6fb',
  '--intergalactic-date-picker-cell-active': '#83aaf7',
  '--intergalactic-date-picker-cell-active-hover': '#5e8ef2',
  '--intergalactic-date-picker-cell-current-invert': 'rgba(255, 255, 255, 0.5)',
  '--intergalactic-date-picker-cell-comparison-active': '#8426f5',
  '--intergalactic-date-picker-cell-comparison-active-hover': '#5a17a9',
  '--intergalactic-dropdown-menu-item': '#ffffff',
  '--intergalactic-dropdown-menu-item-hover': '#f3f4f4',
  '--intergalactic-dropdown-menu-item-selected': 'rgba(208, 224, 254, 0.7)',
  '--intergalactic-dropdown-menu-item-selected-hover': '#d0e0fe',
  '--intergalactic-feature-popover-bg': '#ffd997',
  '--intergalactic-feature-popover-dot-outer-border': '#ffd997',
  '--intergalactic-feature-popover-bg-neutral': '#0f1515',
  '--intergalactic-feature-popover-dot-neutral': '#35c59f',
  '--intergalactic-feature-popover-dot-neutral-outer-border': '#35c59f',
  '--intergalactic-progress-bar-bg': '#dedfe2',
  '--intergalactic-progress-bar-bg-hover': '#c4c5ca',
  '--intergalactic-progress-bar-bg-invert': 'rgba(255, 255, 255, 0.2)',
  '--intergalactic-progress-bar-bg-invert-hover': 'rgba(255, 255, 255, 0.4)',
  '--intergalactic-progress-bar-value-gradient': 'linear-gradient(-45deg, rgba(68, 193, 93, 0.9) 25%, rgba(68, 193, 93, 1) 0%, rgba(68, 193, 93, 1) 50%, rgba(68, 193, 93, 0.9) 0%, rgba(68, 193, 93, 0.9) 75%, rgba(68, 193, 93, 1) 0%)',
  '--intergalactic-progress-bar-pattern-gradient': 'linear-gradient(-45deg, rgba(234, 239, 241, 0.9) 25%, rgba(234, 239, 241, 1) 0%, rgba(234, 239, 241, 1) 50%, rgba(234, 239, 241, 0.9) 0%, rgba(234, 239, 241, 0.9) 75%, rgba(234, 239, 241, 1) 0%)',
  '--intergalactic-progress-bar-value-bg': '#000000',
  '--intergalactic-skeleton-bg': 'rgba(222, 223, 226, 0.8)',
  '--intergalactic-skeleton-bg-invert': 'rgba(255, 255, 255, 0.3)',
  '--intergalactic-slider-rating-normal': '#a9aab1',
  '--intergalactic-slider-rating-hover-active': '#fbb829',
  '--intergalactic-table-th-primary-cell': '#f3f4f4',
  '--intergalactic-table-th-primary-cell-hover': '#dedfe2',
  '--intergalactic-table-th-primary-cell-active': '#dedfe2',
  '--intergalactic-table-th-secondary-cell': '#ffffff',
  '--intergalactic-table-th-gradient': 'linear-gradient(to right, rgba(222, 223, 226, 0) 0%, rgba(222, 223, 226, 1) 100%)',
  '--intergalactic-table-td-cell': '#ffffff',
  '--intergalactic-table-td-cell-hover': '#efeff1',
  '--intergalactic-table-td-cell-active': '#e5e5e8',
  '--intergalactic-table-td-cell-unread': '#f3f4f4',
  '--intergalactic-table-td-cell-accordion': '#f3f4f4',
  '--intergalactic-table-td-cell-selected': '#eef4ff',
  '--intergalactic-table-td-cell-selected-hover': '#d0e0fe',
  '--intergalactic-table-td-cell-selected-active': '#d0e0fe',
  '--intergalactic-table-td-cell-new': '#dcfdf0',
  '--intergalactic-table-td-cell-new-hover': '#9df4d7',
  '--intergalactic-table-td-cell-new-active': '#9df4d7',
  '--intergalactic-table-td-cell-critical': '#ffefec',
  '--intergalactic-table-td-cell-critical-hover': '#ffd0c8',
  '--intergalactic-table-td-cell-critical-active': '#ffd0c8',
  '--intergalactic-table-td-cell-warning': '#ffefe9',
  '--intergalactic-table-td-cell-warning-hover': '#ffd4c6',
  '--intergalactic-table-td-cell-warning-active': '#ffd4c6',
  '--intergalactic-brand-primary': '#ea622f',
  '--intergalactic-brand-secondary': '#350a69',
  '--intergalactic-brand-pinterest': '#bd081c',
  '--intergalactic-brand-instagram': '#e4405f',
  '--intergalactic-brand-youtube': '#ff0000',
  '--intergalactic-brand-facebook': '#1877f2',
  '--intergalactic-brand-linkedIn': '#0a66c2',
  '--intergalactic-brand-twitter': '#1d9bf0',
  '--intergalactic-brand-google-blue': '#1a0dab',
  '--intergalactic-brand-google-green': '#016723',
  '--intergalactic-brand-google-my-business': '#1a73e8',
  '--intergalactic-box-shadow-card': '0 0 0 1px #dedfe2',
  '--intergalactic-box-shadow-card-hover': '3px 3px 30px 0px rgba(19, 20, 22, 0.15)',
  '--intergalactic-box-shadow-dnd': '0px 0px 1px 0px rgba(19, 20, 22, 0.16), 0px 12px 40px 0px rgba(19, 20, 22, 0.16)',
  '--intergalactic-box-shadow-modal': '0px 3px 8px 0px rgba(19, 20, 22, 0.2)',
  '--intergalactic-box-shadow-popper': '0px 1px 12px 0px rgba(19, 20, 22, 0.15)',
  '--intergalactic-keyboard-focus-outline': '#131416',
  '--intergalactic-keyboard-focus-invalid-outline': '#ff3f38',
  '--intergalactic-keyboard-focus-invalid': '0px 0px 0px 3px rgba(255, 63, 56, 0.5)',
  '--intergalactic-keyboard-focus-valid-outline': '#2a8',
  '--intergalactic-keyboard-focus-valid': '0px 0px 0px 3px rgba(2, 10, 8, 0.5)',
  '--intergalactic-keyboard-focus-invert-outline': 'rgba(255, 255, 255, 0.8)',
  '--intergalactic-keyboard-focus-invert': '0px 0px 0px 3px rgba(255, 255, 255, 0.8)',
  '--intergalactic-keyboard-focus': '0px 0px 0px 3px rgba(19, 20, 22, 0.5)',
  '--intergalactic-base': 'Inter',
  '--intergalactic-lh-800': '117%',
  '--intergalactic-lh-700': '110%',
  '--intergalactic-lh-600': '125%',
  '--intergalactic-lh-500': '117%',
  '--intergalactic-lh-400': '120%',
  '--intergalactic-lh-300': '150%',
  '--intergalactic-lh-200': '142%',
  '--intergalactic-lh-100': '133%',
  '--intergalactic-semi-bold': '600',
  '--intergalactic-bold': '700',
  '--intergalactic-regular': '400',
  '--intergalactic-medium': '500',
  '--intergalactic-fs-50': '10px',
  '--intergalactic-fs-100': '12px',
  '--intergalactic-fs-200': '14px',
  '--intergalactic-fs-300': '16px',
  '--intergalactic-fs-400': '20px',
  '--intergalactic-fs-500': '24px',
  '--intergalactic-fs-600': '32px',
  '--intergalactic-fs-700': '36px',
  '--intergalactic-fs-800': '48px',
  '--intergalactic-compact': '0.3',
  '--intergalactic-scale-indent': '4px',
  '--intergalactic-form-control-s': '20px',
  '--intergalactic-form-control-m': '28px',
  '--intergalactic-form-control-l': '40px',
  '--intergalactic-spacing-05x': '2px',
  '--intergalactic-spacing-1x': '4px',
  '--intergalactic-spacing-2x': '8px',
  '--intergalactic-spacing-3x': '12px',
  '--intergalactic-spacing-4x': '16px',
  '--intergalactic-spacing-5x': '20px',
  '--intergalactic-spacing-6x': '24px',
  '--intergalactic-spacing-8x': '32px',
  '--intergalactic-spacing-10x': '40px',
  '--intergalactic-spacing-14x': '56px',
  '--intergalactic-spacing-20x': '80px',
  '--intergalactic-spacing-24x': '96px',
  '--intergalactic-spacing-30x': '120px',
  '--intergalactic-rounded-extra-small': '2px',
  '--intergalactic-rounded-small': '4px',
  '--intergalactic-rounded-medium': '6px',
  '--intergalactic-rounded-large': '12px',
  '--intergalactic-rounded-extra-large': '24px',
  '--intergalactic-addon-rounded': '4px',
  '--intergalactic-badge-rounded': '6px',
  '--intergalactic-chart-rounded': '2px',
  '--intergalactic-counter-rounded': '12px',
  '--intergalactic-tag-rounded': '24px',
  '--intergalactic-switch-rounded': '24px',
  '--intergalactic-control-rounded': '6px',
  '--intergalactic-progress-bar-rounded': '6px',
  '--intergalactic-surface-rounded': '6px',
  '--intergalactic-popper-rounded': '6px',
  '--intergalactic-modal-rounded': '12px',
  '--intergalactic-disabled-opacity': '0.5',
  '--intergalactic-screen-extra-small': '320px',
  '--intergalactic-screen-small': '768px',
  '--intergalactic-screen-medium': '1200px',
  '--intergalactic-screen-large': '1920px',
  '--intergalactic-overlay-primary': 'rgba(19, 20, 22, 0.7)',
  '--intergalactic-overlay-secondary': 'rgba(19, 20, 22, 0.4)',
  '--intergalactic-overlay-limitation-primary': '#f3f4f4',
  '--intergalactic-overlay-limitation-secondary': 'rgba(255, 255, 255, 0.85)',
  '--intergalactic-z-index-deep': '-999',
  '--intergalactic-z-index-overlay': '500',
  '--intergalactic-z-index-modal': '900',
  '--intergalactic-z-index-popper': '700',
  '--intergalactic-z-index-dropdown': '750',
  '--intergalactic-z-index-tooltip': '800',
  '--intergalactic-z-index-notice-bubble': '999',
  '--intergalactic-tooltip-default': '#ffffff',
  '--intergalactic-tooltip-warning': '#ffd0c8',
  '--intergalactic-tooltip-invert': '#131416',
  '--intergalactic-neighbor-location-neutral': '#ffffff80',
  '--intergalactic-neighbor-location-invert': '#00000080',
  '--intergalactic-scroll-area-shadow-left': 'linear-gradient(to right, rgba(19, 20, 22, 0.1) 20.55%, rgba(255, 255, 255, 0.0001) 100%)',
  '--intergalactic-scroll-area-shadow-right': 'linear-gradient(to left, rgba(19, 20, 22, 0.1) 20.55%, rgba(255, 255, 255, 0.0001) 100%)',
  '--intergalactic-scroll-area-shadow-top': 'linear-gradient(to bottom, rgba(19, 20, 22, 0.1) 20.55%, rgba(255, 255, 255, 0.0001) 100%)',
  '--intergalactic-scroll-area-shadow-bottom': 'linear-gradient(to top, rgba(19, 20, 22, 0.1) 20.55%, rgba(255, 255, 255, 0.0001) 100%)',
  '--intergalactic-scroll-area-dropdown-menu-left': 'linear-gradient(to right, rgba(255, 255, 255, 1) 34.38%, rgba(255, 255, 255, 0) 100%)',
  '--intergalactic-scroll-area-dropdown-menu-right': 'linear-gradient(to left, rgba(255, 255, 255, 1) 34.38%, rgba(255, 255, 255, 0) 100%)',
  '--intergalactic-scroll-area-dropdown-menu-bottom': 'linear-gradient(to top, rgba(255, 255, 255, 1) 34.38%, rgba(255, 255, 255, 0) 100%)',
  '--intergalactic-scroll-area-dropdown-menu-top': 'linear-gradient(to bottom, rgba(255, 255, 255, 1) 34.38%, rgba(255, 255, 255, 0) 100%)',
  '--intergalactic-scroll-bar-background': 'rgba(19, 20, 22, 0.3)',
  '--intergalactic-tag-primary-gray-normal': '#ecedf0',
  '--intergalactic-tag-primary-gray-hover-active': '#e3e4e9',
  '--intergalactic-tag-primary-blue-normal': '#d0eeff',
  '--intergalactic-tag-primary-blue-hover-active': '#b7e4ff',
  '--intergalactic-tag-primary-green-normal': '#cff1ea',
  '--intergalactic-tag-primary-green-hover-active': '#b7eae0',
  '--intergalactic-tag-primary-orange-normal': '#ffddd2',
  '--intergalactic-tag-primary-orange-hover-active': '#ffccbb',
  '--intergalactic-tag-primary-red-normal': '#ffcedc',
  '--intergalactic-tag-primary-red-hover-active': '#ffb6ca',
  '--intergalactic-tag-primary-violet-normal': '#f4e3ff',
  '--intergalactic-tag-primary-violet-hover-active': '#efd5ff',
  '--intergalactic-tag-primary-yellow-normal': '#fee6d1',
  '--intergalactic-tag-primary-yellow-hover-active': '#fedab9',
  '--intergalactic-tag-primary-white-normal': 'rgba(255, 255, 255, 0.15)',
  '--intergalactic-tag-primary-white-hover-active': 'rgba(255, 255, 255, 0.3)',
  '--intergalactic-tag-primary-gray-text': '#6c6e79',
  '--intergalactic-tag-primary-blue-text': '#2661e8',
  '--intergalactic-tag-primary-green-text': '#0a8266',
  '--intergalactic-tag-primary-orange-text': '#b4481e',
  '--intergalactic-tag-primary-red-text': '#ca201f',
  '--intergalactic-tag-primary-violet-text': '#8426f5',
  '--intergalactic-tag-primary-yellow-text': '#8e6711',
  '--intergalactic-tag-primary-white-text': '#ffffff',
  '--intergalactic-tag-secondary-normal': '#ffffff',
  '--intergalactic-tag-secondary-hover-active': '#f3f4f4',
  '--intergalactic-tag-secondary-white-normal': 'rgba(255, 255, 255, 0)',
  '--intergalactic-tag-secondary-white-hover-active': 'rgba(255, 255, 255, 0.1)',
  '--intergalactic-tag-secondary-gray-text': '#6c6e79',
  '--intergalactic-tag-secondary-white-text': '#ffffff',
  '--intergalactic-chart-palette-order-1': '#83aaf7',
  '--intergalactic-chart-palette-order-2': '#48e3b8',
  '--intergalactic-chart-palette-order-3': '#ea622f',
  '--intergalactic-chart-palette-order-4': '#ff87eb',
  '--intergalactic-chart-palette-order-5': '#fbb829',
  '--intergalactic-chart-palette-order-6': '#a070fe',
  '--intergalactic-chart-palette-order-7': '#ff786b',
  '--intergalactic-chart-palette-order-8': '#95f8e2',
  '--intergalactic-chart-palette-order-9': '#5e8ef2',
  '--intergalactic-chart-palette-order-10': '#35c59f',
  '--intergalactic-chart-palette-order-11': '#fcb097',
  '--intergalactic-chart-palette-order-12': '#e14adf',
  '--intergalactic-chart-palette-order-13': '#da9f21',
  '--intergalactic-chart-palette-order-14': '#cbb7ff',
  '--intergalactic-chart-palette-order-15': '#ff3f38',
  '--intergalactic-chart-palette-order-16': '#64f5d4',
  '--intergalactic-chart-palette-order-17': '#aac6fb',
  '--intergalactic-chart-palette-order-18': '#2a8',
  '--intergalactic-chart-palette-order-19': '#f48a66',
  '--intergalactic-chart-palette-order-20': '#ffa9fa',
  '--intergalactic-chart-palette-order-21': '#bb881c',
  '--intergalactic-chart-palette-order-22': '#b494ff',
  '--intergalactic-chart-palette-order-23': '#ffa79a',
  '--intergalactic-chart-palette-order-24': '#46f3cc',
  '--intergalactic-chart-palette-order-total-amount': '#90929a',
  '--intergalactic-chart-palette-order-other-data': '#c4c5ca',
  '--intergalactic-chart-palette-order-null': '#dedfe2',
  '--intergalactic-chart-grid-line': '#dedfe2',
  '--intergalactic-chart-grid-x-axis': '#c4c5ca',
  '--intergalactic-chart-grid-y-accent-hover-line': '#a9aab1',
  '--intergalactic-chart-grid-text-label': '#6c6e79',
  '--intergalactic-chart-grid-bar-chart-hover': 'rgba(196, 197, 202, 0.3)',
  '--intergalactic-chart-grid-bar-chart-base-bg': '#dedfe2',
  '--intergalactic-chart-grid-period-bg': 'rgba(196, 197, 202, 0.2)',
  '--intergalactic-chart-grid-period-pattern': 'rgba(19, 20, 22, 0.15)',
  '--intergalactic-chart-grid-border': '#ffffff',
  '--intergalactic-chart-x-axis-accent-period-active': '#6c6e79',
  '--intergalactic-chart-x-axis-accent-data-start-tracking': 'rgba(2, 10, 8, 0.2)',
  '--intergalactic-header-bg': '#232e2d',
  '--intergalactic-header-border-primary': '#232e2d',
  '--intergalactic-header-border-secondary': '#ffffff26',
  '--intergalactic-sidebar-nav-control-hover': 'rgba(222, 223, 226, 0.7)',
  '--intergalactic-sidebar-nav-control-active': '#d8e2e1',
  '--intergalactic-sidebar-nav-control-text-normal': '#5c7472',
  '--intergalactic-sidebar-nav-control-text-active': '#3e4e4d',
  '--intergalactic-sidebar-nav-control-icon-normal': '#7b9996',
  '--intergalactic-sidebar-nav-control-icon-active': '#3e4e4d',
  '--intergalactic-duration-extra-slow': '500',
  '--intergalactic-duration-slow': '400',
  '--intergalactic-duration-medium': '300',
  '--intergalactic-duration-fast': '200',
  '--intergalactic-duration-extra-fast': '100',
  '--intergalactic-duration-switch': '100',
  '--intergalactic-duration-popper': '200',
  '--intergalactic-duration-control': '200',
  '--intergalactic-duration-modal': '200',
  '--intergalactic-duration-accordion': '200',
  '--intergalactic-duration-counter': '200',
};
