import Counter from '@semcore/ui/counter';
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';

import { CounterInFiltersTest } from './__tests__/counter_in_filters.test';
import AnimatedNumberExample, { defaultProps as AnimatedNumberProps } from './examples/animated_number';
import CounterAndTypographyExample from './examples/counter_and_typography';
import CounterInButtonExample from './examples/counter_in_button';
import CounterInDotExample from './examples/counter_in_dot';
import CounterInFiltersExample from './examples/counter_in_filters';
import CounterInFormsExample from './examples/counter_in_forms';
import CounterInLimitsExample from './examples/counter_in_limits';
import CounterInPillsExample from './examples/counter_in_pills';
import { playWrapper } from '../../../utils/playWrapper';
const meta: Meta<typeof Counter> = {
  title: 'Components/Counter/Documentation',
  component: Counter,
};
export default meta;
type Story = StoryObj<typeof Counter>;
export const AnimatedNumber: StoryObj<typeof AnimatedNumberProps> = {
  render: AnimatedNumberExample,
  argTypes: {
    duration: {
      control: { type: 'number' },
    },
    delay: {
      control: { type: 'number' },
    },
  },
  args: AnimatedNumberProps,
  parameters: { sourceCode: 'import Button from \'@semcore/ui/button\';\nimport { AnimatedNumber } from \'@semcore/ui/counter\';\nimport React from \'react\';\n\ntype AnimatedNumberBaseProps = { duration?: number; delay?: number };\nconst Demo = (props: AnimatedNumberBaseProps) => {\n  const [value, setValue] = React.useState(20);\n  const handleClick = () => {\n    setValue(value + 20);\n  };\n\n  return (\n    <>\n      <AnimatedNumber value={value} duration={props.duration} delay={props.delay} />\n      <Button onClick={handleClick} mt={2}>\n        Rerender value\n      </Button>\n    </>\n  );\n};\n\nexport const defaultProps: AnimatedNumberBaseProps = {\n  duration: undefined,\n  delay: undefined,\n};\n\nDemo.defaultProps = defaultProps;\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import Button from \'@semcore/ui/button\';\nimport { AnimatedNumber } from \'@semcore/ui/counter\';\nimport React from \'react\';\n\ntype AnimatedNumberBaseProps = { duration?: number; delay?: number };\nconst Demo = (props: AnimatedNumberBaseProps) => {\n  const [value, setValue] = React.useState(20);\n  const handleClick = () => {\n    setValue(value + 20);\n  };\n\n  return (\n    <>\n      <AnimatedNumber value={value} duration={props.duration} delay={props.delay} />\n      <Button onClick={handleClick} mt={2}>\n        Rerender value\n      </Button>\n    </>\n  );\n};\n\nexport const defaultProps: AnimatedNumberBaseProps = {\n  duration: undefined,\n  delay: undefined,\n};\n\nDemo.defaultProps = defaultProps;\n\nexport default Demo;\n' },
};
export const CounterAndTypography: Story = {
  render: CounterAndTypographyExample,
  parameters: { sourceCode: 'import { Text } from \'@semcore/ui/typography\';\nimport React from \'react\';\n\nconst Demo = () => (\n  <>\n    <Text size={300}>\n      Lorem ipsum\n      {\' \'}\n      <Text color=\'text-secondary\'>12,457</Text>\n    </Text>\n    <br />\n    <Text size={300}>\n      Dolor sit amet:\n      {\' \'}\n      <Text color=\'text-secondary\'>149</Text>\n    </Text>\n  </>\n);\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import { Text } from \'@semcore/ui/typography\';\nimport React from \'react\';\n\nconst Demo = () => (\n  <>\n    <Text size={300}>\n      Lorem ipsum\n      {\' \'}\n      <Text color=\'text-secondary\'>12,457</Text>\n    </Text>\n    <br />\n    <Text size={300}>\n      Dolor sit amet:\n      {\' \'}\n      <Text color=\'text-secondary\'>149</Text>\n    </Text>\n  </>\n);\n\nexport default Demo;\n' },
};
export const CounterInButton: Story = {
  render: CounterInButtonExample,
  parameters: { sourceCode: 'import SettingsM from \'@semcore/icon/Settings/m\';\nimport Button from \'@semcore/ui/button\';\nimport Counter from \'@semcore/ui/counter\';\nimport React from \'react\';\n\nconst Demo = () => (\n  <>\n    <Button mr={4}>\n      <Button.Addon>\n        <SettingsM />\n      </Button.Addon>\n      <Button.Text>Manage columns</Button.Text>\n      <Button.Addon>\n        <Counter>23</Counter>\n      </Button.Addon>\n    </Button>\n    <Button use=\'primary\'>\n      <Button.Addon>\n        <SettingsM />\n      </Button.Addon>\n      <Button.Text>Manage columns</Button.Text>\n      <Button.Addon>\n        <Counter theme=\'bg-primary-neutral\'>23</Counter>\n      </Button.Addon>\n    </Button>\n  </>\n);\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import SettingsM from \'@semcore/icon/Settings/m\';\nimport Button from \'@semcore/ui/button\';\nimport Counter from \'@semcore/ui/counter\';\nimport React from \'react\';\n\nconst Demo = () => (\n  <>\n    <Button mr={4}>\n      <Button.Addon>\n        <SettingsM />\n      </Button.Addon>\n      <Button.Text>Manage columns</Button.Text>\n      <Button.Addon>\n        <Counter>23</Counter>\n      </Button.Addon>\n    </Button>\n    <Button use=\'primary\'>\n      <Button.Addon>\n        <SettingsM />\n      </Button.Addon>\n      <Button.Text>Manage columns</Button.Text>\n      <Button.Addon>\n        <Counter theme=\'bg-primary-neutral\'>23</Counter>\n      </Button.Addon>\n    </Button>\n  </>\n);\n\nexport default Demo;\n' },
};
export const CounterInDot: Story = {
  render: CounterInDotExample,
  parameters: { sourceCode: 'import NotificationM from \'@semcore/icon/Notification/m\';\nimport Button from \'@semcore/ui/button\';\nimport { AnimatedNumber } from \'@semcore/ui/counter\';\nimport Dot from \'@semcore/ui/dot\';\nimport React from \'react\';\n\nconst notificationsCount = 18;\n\nconst Demo = () => (\n  <Button title=\'Notifications\' aria-describedby=\'notification-count\'>\n    <Button.Addon>\n      <NotificationM />\n      <Dot up>\n        <AnimatedNumber\n          initValue={10}\n          value={notificationsCount}\n          duration={1000}\n          delay={500}\n          formatValue={(x) => Math.round(x).toString()}\n          id=\'notification-count\'\n        />\n      </Dot>\n    </Button.Addon>\n  </Button>\n);\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import NotificationM from \'@semcore/icon/Notification/m\';\nimport Button from \'@semcore/ui/button\';\nimport { AnimatedNumber } from \'@semcore/ui/counter\';\nimport Dot from \'@semcore/ui/dot\';\nimport React from \'react\';\n\nconst notificationsCount = 18;\n\nconst Demo = () => (\n  <Button title=\'Notifications\' aria-describedby=\'notification-count\'>\n    <Button.Addon>\n      <NotificationM />\n      <Dot up>\n        <AnimatedNumber\n          initValue={10}\n          value={notificationsCount}\n          duration={1000}\n          delay={500}\n          formatValue={(x) => Math.round(x).toString()}\n          id=\'notification-count\'\n        />\n      </Dot>\n    </Button.Addon>\n  </Button>\n);\n\nexport default Demo;\n' },
};
export const CounterInFilters: Story = {
  render: CounterInFiltersExample,
  play: playWrapper(CounterInFiltersTest),
  parameters: { sourceCode: 'import { ScreenReaderOnly } from \'@semcore/ui/base-components\';\nimport { FilterTrigger } from \'@semcore/ui/base-trigger\';\nimport Counter, { AnimatedNumber } from \'@semcore/ui/counter\';\nimport Dropdown from \'@semcore/ui/dropdown\';\nimport React from \'react\';\n\nconst Demo = () => (\n  <Dropdown>\n    <Dropdown.Trigger aria-label=\'Link to website\' tag={FilterTrigger}>\n      <FilterTrigger.Text aria-hidden>Link to website</FilterTrigger.Text>\n      <FilterTrigger.Addon>\n        <Counter theme=\'info\'>\n          <AnimatedNumber value={500} delay={1000} formatValue={(x) => Math.round(x).toString()} />\n          <ScreenReaderOnly>selected</ScreenReaderOnly>\n        </Counter>\n      </FilterTrigger.Addon>\n    </Dropdown.Trigger>\n    <Dropdown.Popper aria-label=\'Link to website\' p={4}>\n      Filter content\n    </Dropdown.Popper>\n  </Dropdown>\n);\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import { ScreenReaderOnly } from \'@semcore/ui/base-components\';\nimport { FilterTrigger } from \'@semcore/ui/base-trigger\';\nimport Counter, { AnimatedNumber } from \'@semcore/ui/counter\';\nimport Dropdown from \'@semcore/ui/dropdown\';\nimport React from \'react\';\n\nconst Demo = () => (\n  <Dropdown>\n    <Dropdown.Trigger aria-label=\'Link to website\' tag={FilterTrigger}>\n      <FilterTrigger.Text aria-hidden>Link to website</FilterTrigger.Text>\n      <FilterTrigger.Addon>\n        <Counter theme=\'info\'>\n          <AnimatedNumber value={500} delay={1000} formatValue={(x) => Math.round(x).toString()} />\n          <ScreenReaderOnly>selected</ScreenReaderOnly>\n        </Counter>\n      </FilterTrigger.Addon>\n    </Dropdown.Trigger>\n    <Dropdown.Popper aria-label=\'Link to website\' p={4}>\n      Filter content\n    </Dropdown.Popper>\n  </Dropdown>\n);\n\nexport default Demo;\n' },
};
export const CounterInForms: Story = {
  render: CounterInFormsExample,
  parameters: { sourceCode: 'import { Flex, ScreenReaderOnly } from \'@semcore/ui/base-components\';\nimport Counter from \'@semcore/ui/counter\';\nimport Textarea from \'@semcore/ui/textarea\';\nimport { Text } from \'@semcore/ui/typography\';\nimport React from \'react\';\n\nconst maxSymbols = 150;\n\nconst Demo = () => {\n  const [value, setValue] = React.useState(\'\');\n  const [valueLength, setValueLength] = React.useState(0);\n  const [theme, setTheme] = React.useState<string>(\'\');\n  const handleChange = React.useCallback((value: string) => {\n    setValue(value);\n  }, []);\n\n  const valueTimer = React.useRef<number>();\n\n  React.useEffect(() => {\n    if (valueTimer.current) {\n      window.clearTimeout(valueTimer.current);\n    }\n\n    valueTimer.current = window.setTimeout(() => {\n      setValueLength(value.length);\n    }, 1000);\n  }, [value]);\n\n  React.useEffect(() => {\n    if (value.length >= 140) {\n      if (value.length <= maxSymbols) {\n        setTheme(\'warning\');\n      } else {\n        setTheme(\'danger\');\n      }\n    } else {\n      setTheme(\'\');\n    }\n  }, [value]);\n\n  return (\n    <Flex direction=\'column\' w={350}>\n      <Flex mb={2} justifyContent=\'space-between\'>\n        <Flex alignItems=\'center\'>\n          <Text size={200} tag=\'label\' htmlFor=\'limited-text-field\'>\n            Project description\n          </Text>\n          <Counter ml={1} theme={theme} id=\'counter-for-textarea\'>\n            {value.length}\n            <span aria-hidden=\'true\'>/</span>\n            <ScreenReaderOnly>of</ScreenReaderOnly>\n            {maxSymbols}\n            <ScreenReaderOnly>allowed characters</ScreenReaderOnly>\n            {theme === \'warning\' && <ScreenReaderOnly>Limit is almost reached</ScreenReaderOnly>}\n            {theme === \'danger\' && <ScreenReaderOnly>Limit is exceeded</ScreenReaderOnly>}\n          </Counter>\n        </Flex>\n        <Text size={200} color=\'text-secondary\' id=\'optional-for-textarea\'>\n          optional\n        </Text>\n      </Flex>\n      <Textarea\n        placeholder=\'The goal of your project, required resources, and so on\'\n        id=\'limited-text-field\'\n        aria-describedby=\'optional-for-textarea counter-for-textarea\'\n        onChange={handleChange}\n      />\n      <ScreenReaderOnly aria-live=\'polite\' aria-atomic={true}>\n        {valueLength}\n        {\' \'}\n        of\n        {maxSymbols}\n        {\' \'}\n        allowed characters\n        {valueLength >= 140 && valueLength <= 150 && (\n          <ScreenReaderOnly>Limit is almost reached</ScreenReaderOnly>\n        )}\n        {valueLength > 150 && <ScreenReaderOnly>Limit is exceeded</ScreenReaderOnly>}\n      </ScreenReaderOnly>\n    </Flex>\n  );\n};\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import { Flex, ScreenReaderOnly } from \'@semcore/ui/base-components\';\nimport Counter from \'@semcore/ui/counter\';\nimport Textarea from \'@semcore/ui/textarea\';\nimport { Text } from \'@semcore/ui/typography\';\nimport React from \'react\';\n\nconst maxSymbols = 150;\n\nconst Demo = () => {\n  const [value, setValue] = React.useState(\'\');\n  const [valueLength, setValueLength] = React.useState(0);\n  const [theme, setTheme] = React.useState<string>(\'\');\n  const handleChange = React.useCallback((value: string) => {\n    setValue(value);\n  }, []);\n\n  const valueTimer = React.useRef<number>();\n\n  React.useEffect(() => {\n    if (valueTimer.current) {\n      window.clearTimeout(valueTimer.current);\n    }\n\n    valueTimer.current = window.setTimeout(() => {\n      setValueLength(value.length);\n    }, 1000);\n  }, [value]);\n\n  React.useEffect(() => {\n    if (value.length >= 140) {\n      if (value.length <= maxSymbols) {\n        setTheme(\'warning\');\n      } else {\n        setTheme(\'danger\');\n      }\n    } else {\n      setTheme(\'\');\n    }\n  }, [value]);\n\n  return (\n    <Flex direction=\'column\' w={350}>\n      <Flex mb={2} justifyContent=\'space-between\'>\n        <Flex alignItems=\'center\'>\n          <Text size={200} tag=\'label\' htmlFor=\'limited-text-field\'>\n            Project description\n          </Text>\n          <Counter ml={1} theme={theme} id=\'counter-for-textarea\'>\n            {value.length}\n            <span aria-hidden=\'true\'>/</span>\n            <ScreenReaderOnly>of</ScreenReaderOnly>\n            {maxSymbols}\n            <ScreenReaderOnly>allowed characters</ScreenReaderOnly>\n            {theme === \'warning\' && <ScreenReaderOnly>Limit is almost reached</ScreenReaderOnly>}\n            {theme === \'danger\' && <ScreenReaderOnly>Limit is exceeded</ScreenReaderOnly>}\n          </Counter>\n        </Flex>\n        <Text size={200} color=\'text-secondary\' id=\'optional-for-textarea\'>\n          optional\n        </Text>\n      </Flex>\n      <Textarea\n        placeholder=\'The goal of your project, required resources, and so on\'\n        id=\'limited-text-field\'\n        aria-describedby=\'optional-for-textarea counter-for-textarea\'\n        onChange={handleChange}\n      />\n      <ScreenReaderOnly aria-live=\'polite\' aria-atomic={true}>\n        {valueLength}\n        {\' \'}\n        of\n        {maxSymbols}\n        {\' \'}\n        allowed characters\n        {valueLength >= 140 && valueLength <= 150 && (\n          <ScreenReaderOnly>Limit is almost reached</ScreenReaderOnly>\n        )}\n        {valueLength > 150 && <ScreenReaderOnly>Limit is exceeded</ScreenReaderOnly>}\n      </ScreenReaderOnly>\n    </Flex>\n  );\n};\n\nexport default Demo;\n' },
};
export const CounterInLimits: Story = {
  render: CounterInLimitsExample,
  parameters: { sourceCode: 'import WarningM from \'@semcore/icon/Warning/m\';\nimport { Flex } from \'@semcore/ui/base-components\';\nimport ProgressBar from \'@semcore/ui/progress-bar\';\nimport { Text } from \'@semcore/ui/typography\';\nimport React from \'react\';\n\nconst limitsMax = 10;\nconst limitsUsed = 10;\nconst warning = limitsUsed >= limitsMax;\n\nconst Demo = () => (\n  <Flex direction=\'column\' w={350}>\n    <Flex mb={1} justifyContent=\'space-between\'>\n      <Text size={200}>SEO Ideas Units</Text>\n      <Flex alignItems=\'center\'>\n        {warning ? <WarningM color=\'icon-primary-warning\' /> : null}\n        <Text size={200} ml={1} bold aria-hidden>\n          {limitsUsed}\n          <Text color=\'text-secondary\'>\n            /\n            {limitsMax}\n          </Text>\n        </Text>\n      </Flex>\n    </Flex>\n    <ProgressBar\n      value={(limitsUsed / limitsMax) * 100}\n      aria-valuetext={`${limitsUsed} out of ${limitsMax}`}\n      aria-label={`limits used ${warning ? \', warning\' : \'\'}`}\n      size=\'s\'\n    >\n      <ProgressBar.Value theme={warning ? \'bg-primary-warning\' : \'bg-primary-success\'} />\n    </ProgressBar>\n  </Flex>\n);\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import WarningM from \'@semcore/icon/Warning/m\';\nimport { Flex } from \'@semcore/ui/base-components\';\nimport ProgressBar from \'@semcore/ui/progress-bar\';\nimport { Text } from \'@semcore/ui/typography\';\nimport React from \'react\';\n\nconst limitsMax = 10;\nconst limitsUsed = 10;\nconst warning = limitsUsed >= limitsMax;\n\nconst Demo = () => (\n  <Flex direction=\'column\' w={350}>\n    <Flex mb={1} justifyContent=\'space-between\'>\n      <Text size={200}>SEO Ideas Units</Text>\n      <Flex alignItems=\'center\'>\n        {warning ? <WarningM color=\'icon-primary-warning\' /> : null}\n        <Text size={200} ml={1} bold aria-hidden>\n          {limitsUsed}\n          <Text color=\'text-secondary\'>\n            /\n            {limitsMax}\n          </Text>\n        </Text>\n      </Flex>\n    </Flex>\n    <ProgressBar\n      value={(limitsUsed / limitsMax) * 100}\n      aria-valuetext={`${limitsUsed} out of ${limitsMax}`}\n      aria-label={`limits used ${warning ? \', warning\' : \'\'}`}\n      size=\'s\'\n    >\n      <ProgressBar.Value theme={warning ? \'bg-primary-warning\' : \'bg-primary-success\'} />\n    </ProgressBar>\n  </Flex>\n);\n\nexport default Demo;\n' },
};
export const CounterInPills: Story = {
  render: CounterInPillsExample,
  parameters: { sourceCode: 'import Pills from \'@semcore/ui/pills\';\nimport { Text } from \'@semcore/ui/typography\';\nimport React from \'react\';\n\nconst Demo = () => (\n  <Pills defaultValue=\'all\' aria-label=\'Pills with counters\'>\n    <Pills.Item value=\'all\'>\n      <Pills.Item.Text>All</Pills.Item.Text>\n      <Pills.Item.Addon>\n        <Text color=\'text-secondary\'>1,259</Text>\n      </Pills.Item.Addon>\n    </Pills.Item>\n    <Pills.Item value=\'follow\'>\n      <Pills.Item.Text>Follow</Pills.Item.Text>\n      <Pills.Item.Addon>\n        <Text color=\'text-secondary\'>557</Text>\n      </Pills.Item.Addon>\n    </Pills.Item>\n    <Pills.Item value=\'nofollow\'>\n      <Pills.Item.Text>Nofollow</Pills.Item.Text>\n      <Pills.Item.Addon>\n        <Text color=\'text-secondary\'>736</Text>\n      </Pills.Item.Addon>\n    </Pills.Item>\n  </Pills>\n);\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import Pills from \'@semcore/ui/pills\';\nimport { Text } from \'@semcore/ui/typography\';\nimport React from \'react\';\n\nconst Demo = () => (\n  <Pills defaultValue=\'all\' aria-label=\'Pills with counters\'>\n    <Pills.Item value=\'all\'>\n      <Pills.Item.Text>All</Pills.Item.Text>\n      <Pills.Item.Addon>\n        <Text color=\'text-secondary\'>1,259</Text>\n      </Pills.Item.Addon>\n    </Pills.Item>\n    <Pills.Item value=\'follow\'>\n      <Pills.Item.Text>Follow</Pills.Item.Text>\n      <Pills.Item.Addon>\n        <Text color=\'text-secondary\'>557</Text>\n      </Pills.Item.Addon>\n    </Pills.Item>\n    <Pills.Item value=\'nofollow\'>\n      <Pills.Item.Text>Nofollow</Pills.Item.Text>\n      <Pills.Item.Addon>\n        <Text color=\'text-secondary\'>736</Text>\n      </Pills.Item.Addon>\n    </Pills.Item>\n  </Pills>\n);\n\nexport default Demo;\n' },
};
