import { Flex } from '@semcore/ui/base-components';
import { DataTable } from '@semcore/ui/data-table';
import Tooltip from '@semcore/ui/tooltip';
import React from 'react';

export default () => {
  return (
    <DataTable
      wMax={900}
      aria-label='One multiple column'
      data={data}
      columns={[
        {
          name: 'url',
          children: 'Page URL',
          gtcWidth: 'max-content',
          fixed: 'left',
        },
        {
          name: 'count',
          children: () => (
            <Tooltip title='Example tooltip content'>Hreflang</Tooltip>
          ),
          gtcWidth: '112px',
          fixed: 'left',
          sortable: true,
        },
        {
          name: 'some group',
          children: () => {
            return (
              <Tooltip title='Example tooltip content'>
                Hreflang Codes Usage
              </Tooltip>
            );
          },
          style: {
            width: 'fit-content',
            borderBottom: '1px solid var(--intergalactic-border-secondary, #e0e1e9)',
          },
          fixed: 'left',
          borders: 'left',
          columns: langs.map((lang) => ({
            name: lang,
            children: null,
            gtcWidth: 'max-content',
          })),
        },
      ]}
      renderCell={(props) => {
        if (['url', 'count'].includes(props.dataKey)) {
          return props.defaultRender();
        } else {
          return <LangsCellContent lang={props.dataKey} />;
        }
      }}
    />
  );
};

const styles = {
  normalCell: {
    borderLeft: '1px solid var(--gray-100)',
    backgroundColor: 'var(--gray-50)',
  },
  highlightedCell: {
    borderLeft: '1px solid var(--gray-100)',
    backgroundColor: 'var(--green-50)',
  },
};

function LangsCellContent({ lang }: { lang: string }) {
  const isHighlighted = langs.includes(lang);
  return (
    <Flex
      key={lang}
      alignItems='center'
      justifyContent='center'
      wMin={42}
      px='14px'
      style={isHighlighted ? styles.highlightedCell : styles.normalCell}
    >
      {lang}
    </Flex>
  );
}

const data = [
  {
    pageId: '67327bb6f1bd2d40bd90361d',
    url: 'https://locate.apple.com/',
    langs: [
      'ar-ae',
      'ar-bh',
      'ar-eg',
      'ar-jo',
      'ar-kw',
      'ar-lb',
      'ar-om',
      'ar-qa',
      'ar-sa',
      'cs-cz',
      'da-dk',
      'de-at',
      'de-ch',
      'de-de',
      'de-li',
      'el-gr',
      'en-ae',
      'en-ag',
      'en-ai',
      'en-am',
      'en-au',
      'en-az',
      'en-bb',
      'en-bg',
      'en-bh',
      'en-bm',
      'en-bs',
      'en-bw',
      'en-by',
      'en-bz',
      'en-ca',
      'en-dm',
      'en-eg',
      'en-gb',
      'en-gd',
      'en-ge',
      'en-gw',
      'en-gy',
      'en-hk',
      'en-ie',
      'en-il',
      'en-in',
      'en-jm',
      'en-jo',
      'en-ke',
      'en-kg',
      'en-kn',
      'en-kw',
      'en-ky',
      'en-kz',
      'en-lc',
      'en-md',
      'en-me',
      'en-mk',
      'en-ms',
      'en-mt',
      'en-my',
      'en-mz',
      'en-ng',
      'en-nz',
      'en-om',
      'en-ph',
      'en-qa',
      'en-sa',
      'en-sg',
      'en-si',
      'en-sr',
      'en-tc',
      'en-tj',
      'en-tm',
      'en-tt',
      'en-ug',
      'en-us',
      'en-uz',
      'en-vc',
      'en-vg',
      'en-vn',
      'en-za',
      'es-ar',
      'es-bo',
      'es-cl',
      'es-co',
      'es-cr',
      'es-do',
      'es-ec',
      'es-es',
      'es-gt',
      'es-hn',
      'es-mx',
      'es-ni',
      'es-pa',
      'es-pe',
      'es-pr',
      'es-py',
      'es-sv',
      'es-uy',
      'es-ve',
      'et-ee',
      'fi-fi',
      'fr-be',
      'fr-cf',
      'fr-ch',
      'fr-cm',
      'fr-fr',
      'fr-gn',
      'fr-gq',
      'fr-lu',
      'fr-ma',
      'fr-mg',
      'fr-ml',
      'fr-mu',
      'fr-ne',
      'fr-sn',
      'fr-tn',
      'hr-hr',
      'hu-hu',
      'id-id',
      'it-it',
      'ja-jp',
      'ko-kr',
      'lt-lt',
      'lv-lv',
      'nl-be',
      'nl-nl',
      'no-no',
      'pl-pl',
      'pt-br',
      'pt-pt',
      'ro-ro',
      'ru-ru',
      'sk-sk',
      'sv-se',
      'th-th',
      'tr-tr',
      'uk-ua',
      'vi-vn',
      'zh-cn',
      'zh-hk',
      'zh-mo',
      'zh-tw',
    ],
    count: 140,
  },
];

const langs = [
  'ar-ae',
  'ar-bh',
  'ar-eg',
  'ar-jo',
  'ar-kw',
  'ar-lb',
  'ar-om',
  'ar-qa',
  'ar-sa',
  'bg-bg',
  'cs-cz',
  'da-dk',
  'de-at',
  'de-ch',
  'de-de',
  'de-li',
  'el-cy',
  'el-gr',
  'en-ae',
  'en-ag',
  'en-ai',
  'en-al',
  'en-am',
  'en-ar',
  'en-at',
  'en-au',
  'en-az',
  'en-bb',
  'en-be',
  'en-bg',
  'en-bh',
  'en-bm',
  'en-bn',
  'en-bo',
  'en-br',
  'en-bs',
  'en-bw',
  'en-by',
  'en-bz',
  'en-ca',
  'en-cf',
  'en-ch',
  'en-ci',
  'en-cl',
  'en-cm',
  'en-co',
  'en-cr',
  'en-cv',
  'en-cy',
  'en-cz',
  'en-de',
  'en-dk',
  'en-dm',
  'en-do',
  'en-ec',
  'en-ee',
  'en-eg',
  'en-es',
  'en-fi',
  'en-fj',
  'en-fm',
  'en-fr',
  'en-gb',
  'en-gd',
  'en-ge',
  'en-gh',
  'en-gm',
  'en-gn',
  'en-gq',
  'en-gr',
  'en-gt',
  'en-gu',
  'en-gw',
  'en-gy',
  'en-hk',
  'en-hn',
  'en-hr',
  'en-hu',
  'en-id',
  'en-ie',
  'en-il',
  'en-in',
  'en-is',
  'en-it',
  'en-jm',
  'en-jo',
  'en-jp',
  'en-ke',
  'en-kg',
  'en-kh',
  'en-kn',
  'en-kr',
  'en-kw',
  'en-ky',
  'en-kz',
  'en-la',
  'en-lb',
  'en-lc',
  'en-li',
  'en-lk',
  'en-lt',
  'en-lu',
  'en-lv',
  'en-ma',
  'en-md',
  'en-me',
  'en-mg',
  'en-mk',
  'en-ml',
  'en-mn',
  'en-mo',
  'en-ms',
  'en-mt',
  'en-mu',
  'en-mx',
  'en-my',
  'en-mz',
  'en-na',
  'en-ne',
  'en-ng',
  'en-ni',
  'en-nl',
  'en-no',
  'en-nz',
  'en-om',
  'en-pa',
  'en-pe',
  'en-ph',
  'en-pl',
  'en-pt',
  'en-py',
  'en-qa',
  'en-ro',
  'en-ru',
  'en-sa',
  'en-se',
  'en-sg',
  'en-si',
  'en-sk',
  'en-sn',
  'en-sr',
  'en-sv',
  'en-sz',
  'en-tc',
  'en-th',
  'en-tj',
  'en-tm',
  'en-tn',
  'en-tr',
  'en-tt',
  'en-tw',
  'en-ua',
  'en-ug',
  'en-us',
  'en-uz',
  'en-vc',
  'en-ve',
  'en-vg',
  'en-vn',
  'en-za',
  'en-zw',
  'es-ar',
  'es-bo',
  'es-bz',
  'es-cl',
  'es-co',
  'es-cr',
  'es-do',
  'es-ec',
  'es-es',
  'es-gt',
  'es-hn',
  'es-la',
  'es-mx',
  'es-ni',
  'es-pa',
  'es-pe',
  'es-pr',
  'es-py',
  'es-sv',
  'es-us',
  'es-uy',
  'es-ve',
  'et-ee',
  'fi-fi',
  'fr-be',
  'fr-ca',
  'fr-cf',
  'fr-ch',
  'fr-ci',
  'fr-cm',
  'fr-fr',
  'fr-gn',
  'fr-gq',
  'fr-lu',
  'fr-ma',
  'fr-mg',
  'fr-ml',
  'fr-mu',
  'fr-ne',
  'fr-sn',
  'fr-tn',
  'hr-hr',
  'hu-hu',
  'id-id',
  'it-it',
  'ja-jp',
  'ko-kr',
  'lt-lt',
  'lv-lv',
  'nl-be',
  'nl-nl',
  'no-no',
  'pl-pl',
  'pt-br',
  'pt-pt',
  'ro-ro',
  'ru-ru',
  'sk-sk',
  'sl-si',
  'sv-se',
  'th-th',
  'tr-tr',
  'uk-ua',
  'vi-vn',
  'zh-cn',
  'zh-hk',
  'zh-mo',
  'zh-tw',
];
