import LikeM from '@semcore/icon/Like/m';

export default {
  Default: Array(12)
    .fill({})
    .map((_, i) => ({
      label: `Sheep ${i + 1}`,
      icon: LikeM,
    })),
  Movies: [
    { label: 'Action', key: 'action', color: 'chart-palette-order-1' },
    { label: 'Comedy', key: 'comedy', color: 'chart-palette-order-1' },
    { label: 'Drama', key: 'drama', color: 'chart-palette-order-1' },
    { label: 'Fantasy', key: 'fantasy', color: 'chart-palette-order-1' },
    { label: 'Mystery', key: 'mystery', color: 'chart-palette-order-1' },
    { label: 'Romance', key: 'romance', color: 'chart-palette-order-1' },
    { label: 'Western', key: 'western', color: 'chart-palette-order-1' },
    { label: 'Thriller', key: 'thriller', color: 'chart-palette-order-2' },
    { label: 'Crime Thriller', key: 'crime_thriller', color: 'chart-palette-order-2' },
    { label: 'Disaster Thriller', key: 'disaster_thriller', color: 'chart-palette-order-2' },
    { label: 'Psychological\nThriller', key: 'psychological_hriller', color: 'chart-palette-order-2' },
    { label: 'Techno Thriller', key: 'techo_thriller', color: 'chart-palette-order-2' },
    { label: 'Horror', key: 'horror', color: 'chart-palette-order-3' },
    { label: 'Zombie Horror', key: 'zoombie_orror', color: 'chart-palette-order-3' },
    { label: 'Folk Horror', key: 'folk_orror', color: 'chart-palette-order-3' },
    { label: 'Body Horror', key: 'body_horror', color: 'chart-palette-order-3' },
    { label: 'Found\nFootage Horror', key: '\nFootage Horror', color: 'chart-palette-order-3' },
  ],
  MoviesWithPaletteColor: [
    'Action',
    'Comedy',
    'Drama',
    'Fantasy',
    'Mystery',
    'Romance',
    'Western',
    'Thriller',
    'Crime Thriller',
    'Disaster Thriller',
    'Psychological\nThriller',
    'Techno Thriller',
    'Horror',
    'Zombie Horror',
    'Folk Horror',
    'Body Horror',
    'Found\nFootage Horror',
  ].map((label, index) => ({
    label,
    color: `chart-palette-order-${index + 1}`,
  })),
  MultilineText: [
    'consectetur\nadipiscing',
    'elit, sed do\neiusmod tempor',
    'incididunt ut\nlabore et\ndolore',
    'magna aliqua',
    'Ut enim',
    'ad minim veniam',
    'quis nostrud\nexercitation',
    'ullamco\nlaboris\nnisi',
    'ut aliquip ex',
    'ea commodo',
    'consequat',
    'Duis aute',
    'irure dolor\nin',
    'reprehenderit',
  ].map((label) => ({
    label,
    icon: LikeM,
  })),
};
