import Badge from '@semcore/ui/badge';
import type { Meta, StoryObj } from '@storybook/react-vite';

import BadgeMainTypesExample from './examples/badge_main_types';
const meta: Meta<typeof Badge> = {
  title: 'Components/Badge/Documentation',
  component: Badge,
};
export default meta;
type Story = StoryObj<typeof Badge>;
export const BadgeMainTypes: Story = {
  render: BadgeMainTypesExample,
  parameters: { sourceCode: 'import Badge from \'@semcore/ui/badge\';\nimport { Box, Flex } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst Demo = () => {\n  return (\n    <Flex gap={8} alignItems=\'center\'>\n      <Flex gap={2} alignItems=\'center\'>\n        <Badge bg=\'blue-400\' color=\'text-primary-invert\'>\n          admin\n        </Badge>\n        <Badge bg=\'orange-400\' color=\'text-primary-invert\'>\n          alpha\n        </Badge>\n        <Badge bg=\'red-400\' color=\'text-primary-invert\'>\n          beta\n        </Badge>\n        <Badge bg=\'green-400\' color=\'text-primary-invert\'>\n          new\n        </Badge>\n        <Badge bg=\'gray-400\' color=\'text-primary-invert\'>\n          soon\n        </Badge>\n      </Flex>\n      <Box\n        p={4}\n        style={{\n          background: \'var(--intergalactic-bg-primary-invert)\',\n          borderRadius: \'var(--intergalactic-surface-rounded, 6px)\',\n          width: \'fit-content\',\n        }}\n      >\n        <Flex gap={2} alignItems=\'center\'>\n          <Badge bg=\'gray-white\' color=\'text-primary\'>\n            admin\n          </Badge>\n          <Badge bg=\'gray-white\' color=\'text-primary\'>\n            alpha\n          </Badge>\n          <Badge bg=\'gray-white\' color=\'text-primary\'>\n            beta\n          </Badge>\n          <Badge bg=\'gray-white\' color=\'text-primary\'>\n            new\n          </Badge>\n          <Badge bg=\'gray-white\' color=\'text-primary\'>\n            soon\n          </Badge>\n        </Flex>\n      </Box>\n    </Flex>\n  );\n};\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import Badge from \'@semcore/ui/badge\';\nimport { Box, Flex } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst Demo = () => {\n  return (\n    <Flex gap={8} alignItems=\'center\'>\n      <Flex gap={2} alignItems=\'center\'>\n        <Badge bg=\'blue-400\' color=\'text-primary-invert\'>\n          admin\n        </Badge>\n        <Badge bg=\'orange-400\' color=\'text-primary-invert\'>\n          alpha\n        </Badge>\n        <Badge bg=\'red-400\' color=\'text-primary-invert\'>\n          beta\n        </Badge>\n        <Badge bg=\'green-400\' color=\'text-primary-invert\'>\n          new\n        </Badge>\n        <Badge bg=\'gray-400\' color=\'text-primary-invert\'>\n          soon\n        </Badge>\n      </Flex>\n      <Box\n        p={4}\n        style={{\n          background: \'var(--intergalactic-bg-primary-invert)\',\n          borderRadius: \'var(--intergalactic-surface-rounded, 6px)\',\n          width: \'fit-content\',\n        }}\n      >\n        <Flex gap={2} alignItems=\'center\'>\n          <Badge bg=\'gray-white\' color=\'text-primary\'>\n            admin\n          </Badge>\n          <Badge bg=\'gray-white\' color=\'text-primary\'>\n            alpha\n          </Badge>\n          <Badge bg=\'gray-white\' color=\'text-primary\'>\n            beta\n          </Badge>\n          <Badge bg=\'gray-white\' color=\'text-primary\'>\n            new\n          </Badge>\n          <Badge bg=\'gray-white\' color=\'text-primary\'>\n            soon\n          </Badge>\n        </Flex>\n      </Box>\n    </Flex>\n  );\n};\n\nexport default Demo;\n' },
};
