/* eslint-disable no-cyrillic-string/no-cyrillic-string */
import React from 'react';
import Components from './index';

const dataIcons = {
  icons: [
    {
      name: 'GitLab',
      size: ['m', 's', 'xs'],
      group: 'Color',
      tags: ['git', 'lab', 'гитлаб', 'гитхаб', 'гит', 'repo', 'logo', 'лого'],
    },
    {
      name: 'GoogleAnalytics',
      size: ['m', 's', 'xs'],
      group: 'Color',
      tags: ['google', 'analytics', 'гугл', 'аналитика', 'logo', 'лого'],
    },
    {
      name: 'GoogleAnalytics4',
      size: ['m', 's', 'xs'],
      group: 'Color',
      tags: ['google', 'analytics', 'гугл', 'аналитика', 'logo', 'лого'],
    },
    {
      name: 'AdobeAnalytics',
      size: ['m', 's', 'xs'],
      group: 'Color',
      tags: ['adobe', 'analytics', 'эдоб', 'эдоуби', 'аналитика', 'logo', 'лого'],
    },
    {
      name: 'GoogleMail',
      size: ['m', 's', 'xs'],
      group: 'Color',
      tags: [
        'google',
        'mail',
        'email',
        'e-mail',
        'почта',
        'гугл',
        'мэйл',
        'мэил',
        'меил',
        'logo',
        'лого',
      ],
    },
    {
      name: 'GoogleDataStudio',
      size: ['m', 's', 'xs'],
      group: 'Color',
      tags: [
        'google',
        'data',
        'studio',
        'analytics',
        'почта',
        'гугл',
        'дата',
        'студия',
        'аналитика',
      ],
    },
    {
      name: 'GoogleDoc',
      size: ['m', 's', 'xs'],
      group: 'Color',
      tags: ['google', 'document', 'paper', 'drive', 'sheet', 'гугл', 'документ', 'диск', 'бумага'],
    },
    {
      name: 'MicrosoftExchange',
      size: ['m', 's', 'xs'],
      group: 'Color',
      tags: [
        'microsoft',
        'exchange',
        'ms',
        'micro',
        'soft',
        'office',
        'микрософт',
        'мелкософт',
        'logo',
        'лого',
        'майкрософт',
        'эксчендж',
        'эксченж',
      ],
    },
    {
      name: 'Office365',
      size: ['m', 's', 'xs'],
      group: 'Color',
      tags: [
        'office365',
        'ms',
        'microsoft',
        '365',
        'офис',
        'микрософт',
        'мелкософт',
        'майкрософт',
        'logo',
        'лого',
      ],
    },
    {
      name: 'Outlook',
      size: ['m', 's', 'xs'],
      group: 'Color',
      tags: ['outlook', 'микрософт', 'мелкософт', 'майкрософт', 'ms', 'microsoft', 'logo', 'лого'],
    },
    {
      name: 'Sketch',
      size: ['m', 's', 'xs'],
      group: 'Color',
      tags: ['sketch', 'bohemian', 'coding', 'скетч', 'diamond', 'бриллиант', 'logo', 'лого'],
    },
    {
      name: 'Figma',
      size: ['m', 's', 'xs'],
      group: 'Color',
      tags: ['figma', 'coding', 'фигма', 'logo', 'лого'],
    },
    {
      name: 'Yahoo',
      size: ['m', 's', 'xs'],
      group: 'Color',
      tags: ['yahoo', 'яхху', 'logo', 'лого'],
    },
    {
      name: 'FacebookClick',
      size: ['20'],
      group: 'External',
      tags: ['facebook', 'click', 'фейсбук', 'курсор', 'cursor'],
    },
    {
      name: 'FacebookComment',
      size: ['20'],
      group: 'External',
      tags: [
        'facebook',
        'comment',
        'chat',
        'message',
        'фейсбук',
        'комментарий',
        'чат',
        'сообщение',
        'bubble',
      ],
    },
    {
      name: 'FacebookLike',
      size: ['20'],
      group: 'External',
      tags: [
        'facebook',
        'like',
        'фейсбук',
        'лайк',
        'большой',
        'палец',
        'вверх',
        'up',
        'нравится',
        'thumbs',
      ],
    },
    {
      name: 'FacebookSemrush',
      size: ['20'],
      group: 'External',
      tags: ['facebook', 'semrush', 'семраш', 'фейсбук', 'fireball', 'фаерболл'],
    },
    {
      name: 'FacebookShare',
      size: ['20'],
      group: 'External',
      tags: ['facebook', 'share', 'поделиться', 'arrow', 'стрелка', 'фейсбук'],
    },
    {
      name: 'FacebookView',
      size: ['20'],
      group: 'External',
      tags: ['facebook', 'view', 'фейсбук', 'глаз', 'eye', 'просмотр'],
    },
    {
      name: 'InstagramClick',
      size: ['20'],
      group: 'External',
      tags: ['instagram', 'click', 'фейсбук', 'курсор', 'cursor', 'нажать', 'щелкнуть', 'щелчок'],
    },
    {
      name: 'InstagramComment',
      size: ['20'],
      group: 'External',
      tags: [
        'instagram',
        'comment',
        'инстаграм',
        'комментарий',
        'чат',
        'сообщение',
        'bubble',
        'chat',
        'message',
      ],
    },
    {
      name: 'InstagramLike',
      size: ['20'],
      group: 'External',
      tags: [
        'instagram',
        'like',
        'инстаграм',
        'лайк',
        'большой',
        'палец',
        'вверх',
        'up',
        'нравится',
        'thumbs',
      ],
    },
    {
      name: 'InstagramSave',
      size: ['20'],
      group: 'External',
      tags: [
        'instagram',
        'save',
        'bookmark',
        'note',
        'clip',
        'инстаграм',
        'сохранить',
        'сохранение',
        'закладка',
        'букмарк',
      ],
    },
    {
      name: 'InstagramView',
      size: ['20'],
      group: 'External',
      tags: ['instagram', 'view', 'инстаграм', 'глаз', 'eye', 'просмотр'],
    },
    {
      name: 'LinkedInClick',
      size: ['20'],
      group: 'External',
      tags: [
        'linked',
        'in',
        'click',
        'cursor',
        'курсор',
        'линкед',
        'ин',
        'нажать',
        'щелкнуть',
        'щелчок',
      ],
    },
    {
      name: 'LinkedInComment',
      size: ['20'],
      group: 'External',
      tags: [
        'linked',
        'in',
        'comment',
        'chat',
        'линкед',
        'ин',
        'комментарий',
        'чат',
        'сообщение',
        'bubble',
        'message',
      ],
    },
    {
      name: 'LinkedInLike',
      size: ['20'],
      group: 'External',
      tags: [
        'linked',
        'in',
        'like',
        'линкед',
        'ин',
        'лайк',
        'большой',
        'палец',
        'вверх',
        'up',
        'нравится',
        'thumbs',
      ],
    },
    {
      name: 'LinkedInSemrush',
      size: ['20'],
      group: 'External',
      tags: ['linked', 'in', 'semrush', 'семраш', 'линкед', 'ин', 'fireball', 'фаерболл'],
    },
    {
      name: 'LinkedInShare',
      size: ['20'],
      group: 'External',
      tags: ['linked', 'in', 'share', 'поделиться', 'arrow', 'стрелка', 'линкед', 'ин'],
    },
    {
      name: 'LinkedInView',
      size: ['20'],
      group: 'External',
      tags: ['linked', 'in', 'view', 'линкед', 'ин', 'глаз', 'eye', 'просмотр'],
    },
    {
      name: 'PinterestComment',
      size: ['20'],
      group: 'External',
      tags: [
        'pinterest',
        'пинтерест',
        'comment',
        'chat',
        'комментарий',
        'чат',
        'сообщение',
        'bubble',
        'message',
      ],
    },
    {
      name: 'PinterestSave',
      size: ['20'],
      group: 'External',
      tags: ['pinterest', 'save', 'pin', 'пинтерест', 'булавка', 'сохранить', 'запинить'],
    },
    {
      name: 'PinterestSend',
      size: ['20'],
      group: 'External',
      tags: [
        'pinterest',
        'send',
        'mail',
        'outbox',
        'sent',
        'отправить',
        'пинтерест',
        'arrow',
        'up',
        'вверх',
      ],
    },
    {
      name: 'TwitterClick',
      size: ['20'],
      group: 'External',
      tags: ['twitter', 'click', 'cursor', 'курсор', 'твиттер', 'нажать', 'щелкнуть', 'щелчок'],
    },
    {
      name: 'TwitterLike',
      size: ['20'],
      group: 'External',
      tags: ['twitter', 'like', 'твиттер', 'нравится', 'heart', 'love', 'любовь', 'сердце'],
    },
    {
      name: 'TwitterReply',
      size: ['20'],
      group: 'External',
      tags: [
        'twitter',
        'reply',
        'твиттер',
        'comment',
        'chat',
        'комментарий',
        'чат',
        'сообщение',
        'bubble',
        'message',
        'ответ',
      ],
    },
    {
      name: 'TwitterRetweet',
      size: ['20'],
      group: 'External',
      tags: ['twitter', 'retweet', 'ретвит', 'arrow', 'cycle', 'круг', 'цепь'],
    },
    {
      name: 'TwitterSemrush',
      size: ['20'],
      group: 'External',
      tags: ['twitter', 'semrush', 'semrush', 'семраш', 'линкед', 'ин', 'fireball', 'фаерболл'],
    },
    {
      name: 'TwitterView',
      size: ['20'],
      group: 'External',
      tags: ['twitter', 'view', 'линкед', 'ин', 'глаз', 'eye', 'твиттер', 'просмотр'],
    },
    {
      name: 'ActionRedirect',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'action',
        'redirect',
        'bounce',
        'arrow',
        'стрелка',
        'редирект',
        'направление',
        'перенаправить',
        'верх',
        'наверх',
        'направо',
        'право',
        'up',
        'right',
      ],
    },
    {
      name: 'ActionRedo',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'action',
        'redo',
        'отмена',
        'стрелка',
        'arrow',
        'undo',
        'вернуть',
        'отменить',
        'right',
        'право',
        'направо',
      ],
    },
    {
      name: 'ActionReply',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['action', 'reply', 'ответ', 'стрелка', 'arrow', 'mail', 'left', 'лево', 'налево'],
    },
    {
      name: 'ActionReturn',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'action',
        'return',
        'enter',
        'ввод',
        'ентер',
        'энтер',
        'left',
        'налево',
        'лево',
        'arrow',
        'стрелка',
        'вернуть',
        'возврат',
      ],
    },
    {
      name: 'ActionShare',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'action',
        'share',
        'поделиться',
        'arrow',
        'стрелка',
        'right',
        'право',
        'направо',
        'шаринг',
        'sharing',
      ],
    },
    {
      name: 'ActionStop',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['action', 'stop', 'стоп', 'pause', 'пауза'],
    },
    {
      name: 'ActionUndo',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'action',
        'undo',
        'отмена',
        'отменить',
        'стрелка',
        'налево',
        'лево',
        'left',
        'arrow',
        'вернуть',
        'переделать',
        'вернуть',
      ],
    },
    {
      name: 'Ad',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['ad', 'реклама', 'advertisement', 'banner', 'баннер'],
    },
    {
      name: 'AdBottom',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['ad', 'bottom', 'реклама', 'advertisement', 'banner', 'баннер', 'низ', 'вниз'],
    },
    {
      name: 'AddCampaign',
      size: ['l', 'm', 's', 'xs'],
      group: 'Action',
      tags: ['add', 'campaign', 'добавить', 'plus', 'плюс', 'кампания', 'list', 'список'],
    },
    {
      name: 'AdTop',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['ad', 'top', 'реклама', 'advertisement', 'banner', 'баннер', 'вверх', 'верх'],
    },
    {
      name: 'AllDevices',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'all',
        'devices',
        'все',
        'девайсы',
        'desktop',
        'computer',
        'mobile',
        'десктоп',
        'пк',
        'мобильный',
        'телефон',
        'cell',
      ],
    },
    {
      name: 'AmpProject',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'amp',
        'project',
        'accelerated',
        'mobile',
        'pages',
        'google',
        'гугл',
        'проект',
        'lighning',
        'молния',
      ],
    },
    {
      name: 'Android',
      size: ['m', 's', 'xs'],
      group: 'Hardware',
      tags: [
        'android',
        'андроид',
        'робот',
        'mobile',
        'cell',
        'os',
        'operating',
        'system',
        'операционная',
        'система',
        'green',
        'зеленый',
      ],
    },
    {
      name: 'Apple',
      size: ['m', 's', 'xs'],
      group: 'Hardware',
      tags: [
        'apple',
        'эпл',
        'яблоко',
        'logo',
        'лого',
        'os',
        'operating',
        'system',
        'операционная',
        'система',
        'mobile',
        'cell',
      ],
    },
    {
      name: 'Archive',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'archive',
        'архив',
        'ящик',
        'drawer',
        'document',
        'документ',
        'бумаги',
        'papers',
        'storage',
        'хранение',
      ],
    },
    {
      name: 'ArrowDown',
      size: ['m', 's', 'xs', 'xxs'],
      group: 'Navigation',
      tags: ['arrow', 'down', 'стрелка', 'вниз', 'низ'],
    },
    {
      name: 'ArrowDownAlt',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: ['arrow', 'down', 'стрелка', 'вниз', 'низ', 'alt'],
    },
    {
      name: 'ArrowLeft',
      size: ['m', 's', 'xs', 'xxs'],
      group: 'Navigation',
      tags: ['arrow', 'left', 'стрелка', 'лево', 'налево', 'влево'],
    },
    {
      name: 'ArrowLeftAlt',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: ['arrow', 'left', 'стрелка', 'лево', 'влево', 'налево', 'alt'],
    },
    {
      name: 'ArrowRight',
      size: ['m', 's', 'xs', 'xxs'],
      group: 'Navigation',
      tags: ['arrow', 'right', 'стрелка', 'вправо', 'направо'],
    },
    {
      name: 'ArrowRightAlt',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: ['arrow', 'right', 'стрелка', 'вправо', 'направо', 'alt'],
    },
    {
      name: 'ArrowUp',
      size: ['m', 's', 'xs', 'xxs'],
      group: 'Navigation',
      tags: ['arrow', 'up', 'стрелка', 'вверх', 'верх'],
    },
    {
      name: 'ArrowUpAlt',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: ['arrow', 'up', 'стрелка', 'вверх', 'верх', 'alt'],
    },
    {
      name: 'Attach',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['attach', 'pin', 'булавка', 'аттач', 'скрепка', 'clip'],
    },
    {
      name: 'Block',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['block', 'stop', 'no', 'denied', 'стоп', 'блок', 'нельзя', 'доступ', 'запрещен'],
    },
    {
      name: 'Book',
      size: ['l', 'm', 's', 'xs'],
      group: 'Misc',
      tags: ['book', 'книга'],
    },
    {
      name: 'Briefcase',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'case',
        'work',
        'brief',
        'suit',
        'чемодан',
        'работа',
        'office',
        'bag',
        'portfolio',
        'портфолио',
        'attache',
        'атташе',
        'folder',
        'baggage',
      ],
    },
    {
      name: 'BriefcaseAlt',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'case',
        'work',
        'brief',
        'suit',
        'чемодан',
        'работа',
        'office',
        'bag',
        'portfolio',
        'портфолио',
        'attache',
        'атташе',
        'folder',
        'baggage',
      ],
    },
    {
      name: 'Filter',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'filter',
        'settings',
        'parameters',
        'funnel',
        'фильтр',
        'фильтрация',
        'настройки',
        'параметры',
        'switch',
      ],
    },
    {
      name: 'Funnel',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'filter',
        'settings',
        'parameters',
        'фильтр',
        'фильтрация',
        'настройки',
        'параметры',
        'switch',
      ],
    },
    {
      name: 'Hotel',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'hotel',
        'hostel',
        'building',
        'house',
        'star',
        'rating',
        'booking',
        'отель',
        'звезды',
        'здание',
        'хостел',
      ],
    },
    {
      name: 'Bookmark',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['bookmark', 'закладка', 'save', 'сохранить'],
    },
    {
      name: 'BookmarkOutline',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['bookmark', 'закладка', 'save', 'outline'],
    },
    {
      name: 'BracketsAngle',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['brackets', 'angle', 'code', 'скобки', 'программирование', 'угловые', 'js', 'html'],
    },
    {
      name: 'BracketsCode',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['brackets', 'code', 'angle', 'скобки', 'программирование', 'угловые', 'js', 'html'],
    },
    {
      name: 'BracketsCurly',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['brackets', 'curly', 'code', 'скобки', 'фигурные', 'скобки', 'css'],
    },
    {
      name: 'Bulb',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['bulb', 'лампочка', 'light', 'свет'],
    },
    {
      name: 'Calendar',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'calendar',
        'календарь',
        'date',
        'year',
        'month',
        'day',
        'год',
        'месяц',
        'день',
        'дата',
      ],
    },
    {
      name: 'CalendarCHeck',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'calendar',
        'календарь',
        'date',
        'year',
        'month',
        'day',
        'год',
        'месяц',
        'день',
        'дата',
        'check',
        'галочка',
        'галка',
        'отметить',
      ],
    },
    {
      name: 'Cards',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['cards', 'карточки', 'gallery', 'slider', 'flip', 'list', 'список', 'галерея'],
    },
    {
      name: 'Cart',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'cart',
        'shopping',
        'commence',
        'buy',
        'purchase',
        'корзина',
        'купить',
        'покупатель',
        'bag',
      ],
    },
    {
      name: 'ChartBar',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['chart', 'bar', 'график', 'vertical', 'вертикальный', 'полосы'],
    },
    {
      name: 'ChartBarStacked',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['chart', 'bar', 'stacked', 'horizontal', 'cigarette', 'сигарета', 'график'],
    },
    {
      name: 'ChartBubble',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['chart', 'bubble', 'пузырь', 'график', 'circle'],
    },
    {
      name: 'ChartLine',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['chart', 'line', 'график', 'линия', 'growth', 'increase'],
    },
    {
      name: 'ChartPie',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['chart', 'pie', 'donut', 'circle', 'график', 'пирог', 'пай'],
    },
    {
      name: 'Chat',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['chat', 'bubble', 'comment', 'say', 'text', 'чат', 'комментарий', 'сказать'],
    },
    {
      name: 'ChatCheck',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'chat',
        'check',
        'box',
        'comment',
        'say',
        'text',
        'чат',
        'комментарий',
        'сказать',
        'галочка',
      ],
    },
    {
      name: 'ChatPlus',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'chat',
        'plus',
        'comment',
        'say',
        'add',
        'text',
        'добавить',
        'чат',
        'комментарий',
        'сказать',
        'плюс',
      ],
    },
    {
      name: 'ChatQuestion',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'chat',
        'question',
        'mark',
        'say',
        'comment',
        'text',
        'ask',
        'чат',
        'спросить',
        'комментарий',
        'сказать',
        'вопросительный',
        'знак',
      ],
    },
    {
      name: 'Check',
      size: ['l', 'm', 's', 'xs', 'xxs'],
      group: 'Action',
      tags: [
        'check',
        'галочка',
        'mark',
        'approve',
        'yes',
        'accept',
        'done',
        'да',
        'применить',
        'принять',
        'подтвердить',
      ],
    },
    {
      name: 'CheckAlt',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'check',
        'галочка',
        'mark',
        'approve',
        'yes',
        'accept',
        'done',
        'да',
        'применить',
        'принять',
        'подтвердить',
        'alt',
      ],
    },
    {
      name: 'Checkbox',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'check',
        'галочка',
        'mark',
        'approve',
        'yes',
        'accept',
        'done',
        'да',
        'применить',
        'принять',
        'подтвердить',
        'vote',
        'box',
        'голосовать',
      ],
    },
    {
      name: 'ChevronDoubleDown',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['chevron', 'double', 'down', 'шеврон', 'вниз', 'низ', 'двойной', 'arrow', 'стрелка'],
    },
    {
      name: 'ChevronDoubleLeft',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'chevron',
        'double',
        'left',
        'лево',
        'налево',
        'влево',
        'arrow',
        'стрелка',
        'двойной',
        'шеврон',
      ],
    },
    {
      name: 'ChevronDoubleRight',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'chevron',
        'double',
        'right',
        'право',
        'направо',
        'вправо',
        'arrow',
        'стрелка',
        'двойной',
        'шеврон',
      ],
    },
    {
      name: 'ChevronDoubleUp',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['chevron', 'double', 'up', 'шеврон', 'верх', 'вверх', 'двойной', 'arrow', 'стрелка'],
    },
    {
      name: 'ChevronDown',
      size: ['l', 'm', 's', 'xs', 'xxs'],
      group: 'Misc',
      tags: ['chevron', 'down', 'шеврон', 'arrow', 'стрелка', 'низ', 'вниз'],
    },
    {
      name: 'ChevronLeft',
      size: ['l', 'm', 's', 'xs', 'xxs'],
      group: 'Misc',
      tags: ['chevron', 'left', 'стрелка', 'лево', 'влево', 'налево', 'arrow', 'шеврон'],
    },
    {
      name: 'ChevronRight',
      size: ['l', 'm', 's', 'xs', 'xxs'],
      group: 'Misc',
      tags: [
        'chevron',
        'right',
        'вправо',
        'направо',
        'вправо',
        'право',
        'шеврон',
        'arrow',
        'стрелка',
      ],
    },
    {
      name: 'ChevronUp',
      size: ['l', 'm', 's', 'xs', 'xxs'],
      group: 'Misc',
      tags: ['chevron', 'up', 'верх', 'вверх', 'шеврон', 'стрелка', 'arrow'],
    },
    {
      name: 'Chrome',
      size: ['m', 's', 'xs'],
      group: 'Hardware',
      tags: ['chrome', 'google', 'хром', 'browser', 'logo', 'лого', 'браузер'],
    },
    {
      name: 'Close',
      size: ['m', 's', 'xs', 'xxs'],
      group: 'Action',
      tags: ['close', 'cross', 'закрыть', 'крестик', 'stop', 'denied', 'x'],
    },
    {
      name: 'CloseAlt',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['close', 'cross', 'закрыть', 'крестик', 'stop', 'denied', 'x', 'alt'],
    },
    {
      name: 'Collapse',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'collapse',
        'arrow',
        'zoom',
        'window',
        'окно',
        'стрелка',
        'minimize',
        'close',
        'свернуть',
        'уменьшить',
        'full',
        'size',
        'screen',
        'весь',
        'экран',
      ],
    },
    {
      name: 'ColumnThree',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'column',
        'three',
        'колонка',
        '3',
        'три',
        'layout',
        'верстка',
        'compose',
        'grid',
        'сетка',
      ],
    },
    {
      name: 'ColumnTwo',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'column',
        'two',
        'колонка',
        '2',
        'два',
        'layout',
        'верстка',
        'compose',
        'grid',
        'сетка',
      ],
    },
    {
      name: 'Compose',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'compose',
        'pencil',
        'write',
        'карандаш',
        'mail',
        'edit',
        'написать',
        'создать',
        'create',
      ],
    },
    {
      name: 'Copy',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['copy', 'plus', 'скопировать', 'копия', 'double', 'duplicate', 'add', 'плюс'],
    },
    {
      name: 'Crosshair',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'crosshair',
        'aim',
        'dot',
        'sight',
        'прицел',
        'мишень',
        'target',
        'выстрел',
        'shot',
        'shoot',
        'optical',
      ],
    },
    {
      name: 'Crown',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'crown',
        'king',
        'queen',
        'admin',
        'корона',
        'король',
        'королева',
        'админ',
        'super',
        'rights',
      ],
    },
    {
      name: 'CurrencyUsd',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'currency',
        'usd',
        'united',
        'states',
        'dollar',
        'валюта',
        'money',
        'pay',
        'US',
        'США',
        'америка',
        'платеж',
      ],
    },
    {
      name: 'CursorDefault',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['cursor', 'default', 'arrow', 'стрелка', 'курсор', 'mac', 'point'],
    },
    {
      name: 'CursorMove',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'cursor',
        'move',
        'edit',
        'arrow',
        'стрелка',
        'directions',
        'x',
        'y',
        'up',
        'down',
        'left',
        'right',
        'верх',
        'низ',
        'лево',
        'право',
        'вверх',
        'вниз',
        'налево',
        'направо',
      ],
    },
    {
      name: 'CursorPointer',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['cursor', 'pointer', 'hand', 'курсор', 'finger', 'указатель', 'палец'],
    },
    {
      name: 'Cut',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['cut', 'scissors', 'вырезать', 'copy', 'exclude', 'ножницы'],
    },
    {
      name: 'Density',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'density',
        'flask',
        'chemistry',
        'capacity',
        'liquid',
        'плотность',
        'жидкость',
        'колба',
        'химия',
      ],
    },
    {
      name: 'Desktop',
      size: ['m', 's', 'xs'],
      group: 'Hardware',
      tags: [
        'desktop',
        'pc',
        'computer',
        'компьютер',
        'пк',
        'монитор',
        'десктоп',
        'display',
        'monitor',
      ],
    },
    {
      name: 'DesktopChart',
      size: ['m', 's', 'xs'],
      group: 'Hardware',
      tags: [
        'desktop',
        'pc',
        'computer',
        'компьютер',
        'пк',
        'монитор',
        'десктоп',
        'display',
        'monitor',
        'chart',
        'vertical',
        'bar',
        'график',
        'вертикальный',
      ],
    },
    {
      name: 'Document',
      size: ['m', 's', 'xs'],
      group: 'File',
      tags: ['document', 'документ', 'paper', 'листок', 'бумага', 'sheet', 'blank'],
    },
    {
      name: 'DocumentCheck',
      size: ['m', 's', 'xs'],
      group: 'File',
      tags: [
        'document',
        'документ',
        'paper',
        'листок',
        'бумага',
        'sheet',
        'blank',
        'check',
        'галочка',
        'box',
        'approve',
        'ok',
      ],
    },
    {
      name: 'DocumentDrop',
      size: ['l', 'm', 's', 'xs'],
      group: 'File',
      tags: [
        'document',
        'документ',
        'paper',
        'листок',
        'бумага',
        'sheet',
        'blank',
        'upload',
        'file',
        'drop',
        'zone',
        'бросить',
        'move',
        'dashed',
        'пунктир',
      ],
    },
    {
      name: 'DocumentExport',
      size: ['m', 's', 'xs'],
      group: 'File',
      tags: [
        'document',
        'документ',
        'paper',
        'листок',
        'бумага',
        'sheet',
        'blank',
        'export',
        'экспорт',
        'стрелка',
        'arrow',
        'convert',
      ],
    },
    {
      name: 'DocumentHappy',
      size: ['l', 'm', 's', 'xs'],
      group: 'File',
      tags: [
        'document',
        'документ',
        'paper',
        'листок',
        'бумага',
        'sheet',
        'blank',
        'happy',
        'счастливый',
        'emotion',
        'smile',
        'улыбка',
        'эмодзи',
        'emoji',
      ],
    },
    {
      name: 'DocumentPdf',
      size: ['m', 's', 'xs'],
      group: 'File',
      tags: ['document', 'документ', 'paper', 'листок', 'бумага', 'sheet', 'blank', 'pdf'],
    },
    {
      name: 'DocumentSad',
      size: ['l', 'm', 's', 'xs'],
      group: 'File',
      tags: [
        'document',
        'документ',
        'paper',
        'листок',
        'бумага',
        'sheet',
        'blank',
        'sad',
        'грустный',
        'emotion',
        'smile',
        'улыбка',
        'эмодзи',
        'emoji',
      ],
    },
    {
      name: 'Drawer',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'drawer',
        'inbox',
        'archive',
        'storage',
        'ящик',
        'empty',
        'пустой',
        'архив',
        'хранение',
        'хранилище',
        'document',
        'papers',
      ],
    },
    {
      name: 'Drop',
      size: ['l', 'm', 's', 'xs'],
      group: 'Misc',
      tags: [
        'drop',
        'zone',
        'dashed',
        'пунктир',
        'зона',
        'загрузка',
        'бросить',
        'upload',
        'file',
        'файл',
      ],
    },
    {
      name: 'DropText',
      size: ['l', 'm', 's', 'xs'],
      group: 'Misc',
      tags: [
        'drop',
        'zone',
        'dashed',
        'пунктир',
        'зона',
        'загрузка',
        'бросить',
        'upload',
        'file',
        'файл',
        'text',
        'текст',
      ],
    },
    {
      name: 'Edit',
      size: ['l', 'm', 's', 'xs'],
      group: 'Action',
      tags: [
        'edit',
        'pencil',
        'write',
        'карандаш',
        'mail',
        'edit',
        'написать',
        'создать',
        'create',
        'редактировать',
      ],
    },
    {
      name: 'Education',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'education',
        'graduate',
        'course',
        'university',
        'cap',
        'gown',
        'academic',
        'square',
        'обучение',
        'курсы',
        'выпускник',
        'образование',
        'университет',
      ],
    },
    {
      name: 'Ellipsis',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: [
        'ellipsis',
        'three',
        'dot',
        'многоточие',
        'троеточие',
        'more',
        'details',
        'menu',
        'kebab',
        'hamburger',
        'кебаб',
        'меню',
      ],
    },
    {
      name: 'EllipsisAlt',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: [
        'ellipsis',
        'three',
        'dot',
        'многоточие',
        'троеточие',
        'more',
        'details',
        'menu',
        'kebab',
        'hamburger',
        'кебаб',
        'меню',
        'alt',
      ],
    },
    {
      name: 'Exit',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: [
        'exit',
        'wayfindings',
        'выход',
        'arrow',
        'стрелка',
        'право',
        'вправо',
        'направо',
        'right',
        'box',
      ],
    },
    {
      name: 'Expand',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'expand',
        'fullscreen',
        'enlarge',
        'open',
        'весь',
        'экран',
        'увеличить',
        'zoom',
        'big',
        'large',
        'расширить',
      ],
    },
    {
      name: 'Facebook',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: ['facebook', 'logo', 'лого', 'фейсбук', 'social'],
    },
    {
      name: 'FacebookMessenger',
      size: ['l', 'm', 's', 'xs'],
      group: 'Social',
      tags: [
        'facebook',
        'logo',
        'лого',
        'фейсбук',
        'social',
        'message',
        'messenger',
        'мессенджер',
        'мессенжер',
        'chat',
        'chat',
        'чат',
        'сообщение',
      ],
    },
    {
      name: 'Slack',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: [
        'slack',
        'чат',
        'слак',
        'слэк',
        'social',
        'message',
        'corporate',
        'chat',
        'чат',
        'сообщение',
      ],
    },
    {
      name: 'Favorite',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['favorite', 'favourite', 'фаворит', 'star', 'звезда', 'like', 'mark'],
    },
    {
      name: 'Airplane',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['plane', 'take-off', 'flight', 'air', 'airplane', 'самолет', 'полет', 'вылет'],
    },
    {
      name: 'FavoriteOutline',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['favorite', 'favourite', 'фаворит', 'star', 'звезда', 'like', 'mark', 'outline'],
    },
    {
      name: 'FileDownload',
      size: ['m', 's', 'xs'],
      group: 'File',
      tags: ['file', 'download', 'arrow', 'стрелка', 'вниз', 'низ', 'down', 'файл', 'скачать'],
    },
    {
      name: 'FileExport',
      size: ['m', 's', 'xs'],
      group: 'File',
      tags: ['file', 'export', 'arrow', 'стрелка', 'вверх', 'верх', 'up', 'файл', 'экспорт'],
    },
    {
      name: 'FileImport',
      size: ['m', 's', 'xs'],
      group: 'File',
      tags: ['file', 'arrow', 'стрелка', 'вниз', 'низ', 'down', 'файл', 'import'],
    },
    {
      name: 'FileUpload',
      size: ['m', 's', 'xs'],
      group: 'File',
      tags: [
        'file',
        'upload',
        'arrow',
        'стрелка',
        'вверх',
        'cloud',
        'up',
        'файл',
        'загрузка',
        'save',
        'backup',
      ],
    },
    {
      name: 'Fire',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['fire', 'flame', 'огонь', 'danger', 'опасность', 'foster'],
    },
    {
      name: 'Firefox',
      size: ['m', 's', 'xs'],
      group: 'Hardware',
      tags: ['firefox', 'logo', 'лого', 'лиса', 'фаирфокс', 'фаер', 'браузер', 'browser'],
    },
    {
      name: 'Folder',
      size: ['m', 's', 'xs'],
      group: 'File',
      tags: ['folder', 'папка', 'directory', 'storage', 'file', 'директория'],
    },
    {
      name: 'FolderOpen',
      size: ['m', 's', 'xs'],
      group: 'File',
      tags: ['folder', 'папка', 'directory', 'storage', 'file', 'директория', 'open', 'открытая'],
    },
    {
      name: 'FolderOpenOutline',
      size: ['m', 's', 'xs'],
      group: 'File',
      tags: [
        'folder',
        'папка',
        'directory',
        'storage',
        'file',
        'директория',
        'open',
        'открытая',
        'outline',
      ],
    },
    {
      name: 'FolderOutline',
      size: ['m', 's', 'xs'],
      group: 'File',
      tags: ['folder', 'папка', 'directory', 'storage', 'file', 'директория', 'folder', 'outline'],
    },
    {
      name: 'Form',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'form',
        'fill',
        'форма',
        'doctors',
        'note',
        'document',
        'документ',
        'заполнить',
        'paper',
        'бумага',
      ],
    },
    {
      name: 'FormatAlignCenter',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'format',
        'align',
        'center',
        'text',
        'layout',
        'форматирование',
        'текст',
        'плилипание',
        'wysiwyg',
        'editor',
        'редактор',
        'центр',
      ],
    },
    {
      name: 'FormatAlignJustify',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'format',
        'align',
        'justify',
        'text',
        'layout',
        'форматирование',
        'текст',
        'плилипание',
        'wysiwyg',
        'editor',
        'редактор',
        'на',
        'весь',
        'экран',
        'ширину',
      ],
    },
    {
      name: 'FormatAlignLeft',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'format',
        'align',
        'left',
        'text',
        'layout',
        'форматирование',
        'текст',
        'плилипание',
        'wysiwyg',
        'editor',
        'редактор',
        'лево',
      ],
    },
    {
      name: 'GenderMale',
      size: ['l', 'm', 's', 'xs'],
      group: 'Misc',
      tags: [
        'gender',
        'sex',
        'пол',
        'гендер',
        'male',
        'man',
        'men',
        'мужчина',
        'human',
        'masculine',
        'маскулинный',
      ],
    },
    {
      name: 'GenderFemale',
      size: ['l', 'm', 's', 'xs'],
      group: 'Misc',
      tags: [
        'gender',
        'sex',
        'пол',
        'гендер',
        'female',
        'woman',
        'women',
        'женщина',
        'human',
        'feminine',
        'феминный',
      ],
    },
    {
      name: 'FormatAlignRight',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'format',
        'align',
        'right',
        'text',
        'layout',
        'форматирование',
        'текст',
        'плилипание',
        'wysiwyg',
        'editor',
        'редактор',
        'право',
      ],
    },
    {
      name: 'Foursquare',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: ['foursquare', 'logo', 'лого', 'фосквер', 'форсквер', 'social'],
    },
    {
      name: 'Wordpress',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: ['wordpress', 'site', 'blog', 'engine', 'вордпресс', 'блог'],
    },
    {
      name: 'G2crowd',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: ['g2crowd', 'social', 'logo', 'лого'],
    },
    {
      name: 'Globe',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['globe', 'planet', 'глобус', 'планета', 'Earth', 'Земля', 'world', 'global', 'мир'],
    },
    {
      name: 'GlobeAlt',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['globe', 'planet', 'глобус', 'планета', 'Earth', 'Земля', 'world', 'global', 'мир'],
    },
    {
      name: 'Goblet',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'goblet',
        'cup',
        'кубок',
        'trophy',
        'трофей',
        'prize',
        'first',
        'place',
        'winner',
        'победитель',
        'приз',
      ],
    },
    {
      name: 'Google',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: ['google', 'гугл', 'лого', 'logo'],
    },
    {
      name: 'GoogleColor',
      size: ['l', 'm', 's', 'xs'],
      group: 'Color',
      tags: ['google', 'гугл', 'лого', 'logo'],
    },
    {
      name: 'GoogleGSC',
      size: ['l', 'm', 's', 'xs'],
      group: 'Color',
      tags: ['google', 'гугл', 'лого', 'logo', 'gsc'],
    },
    {
      name: 'GoogleMyBusiness',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: [
        'google',
        'my',
        'business',
        'google',
        'social',
        'logo',
        'лого',
        'бизнес',
        'мой',
        'гугл',
      ],
    },
    {
      name: 'GooglePlus',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: ['google', 'plus', 'social', 'гугл', 'лого', 'logo'],
    },
    {
      name: 'Hamburger',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: ['hamburger', 'menu', 'more', 'kebab', 'меню', 'гамбургер', 'еда', 'кушоть', 'list'],
    },
    {
      name: 'Health',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['health', 'heart', 'pulse', 'beep', 'monitor', 'hr', 'пульс', 'здоровье', 'сердце'],
    },
    {
      name: 'Home',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: ['home', 'house', 'chimney', 'directory', 'дом', 'здание', 'building'],
    },
    {
      name: 'Infinity',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['infinity', 'eight', 'бесконечность', 'loop', '8', 'number'],
    },
    {
      name: 'Info',
      size: ['m', 's', 'xs', 'xxs'],
      group: 'Status',
      tags: ['info', 'ишка', 'информация', 'details', 'детали', 'подробнее', 'help', 'помощь'],
    },
    {
      name: 'InfoOutline',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'info',
        'ишка',
        'информация',
        'details',
        'детали',
        'подробнее',
        'help',
        'помощь',
        'outline',
      ],
    },
    {
      name: 'Instagram',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: [
        'instagram',
        'social',
        'logo',
        'facebook',
        'фейсбук',
        'инстаграм',
        'photo',
        'camera',
        'лого',
      ],
    },
    {
      name: 'Key',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['key', 'ключ', 'access', 'chain', 'доступ'],
    },
    {
      name: 'KeyCmd',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['key', 'cmd', 'command', 'клавиша', 'board', 'press', 'windows', 'клавиатура'],
    },
    {
      name: 'KeyHotkey',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['key', 'hotkey', 'горячая', 'клавиша', 'board', 'press', 'quick', 'быстрый'],
    },
    {
      name: 'Lightning',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['lightning', 'молния', 'zap', 'fast', 'sonic', 'quick', 'быстро', 'flash'],
    },
    {
      name: 'Like',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['like', 'heart', 'сердце', 'нравится', 'любовь', 'love'],
    },
    {
      name: 'LikeOutline',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['like', 'heart', 'сердце', 'нравится', 'любовь', 'love', 'outline'],
    },
    {
      name: 'Link',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['link', 'chain', 'цепь', 'ссылка', 'pin', 'clip', 'connect'],
    },
    {
      name: 'LinkAlt',
      size: ['l', 'm', 's', 'xs'],
      group: 'Status',
      tags: ['link', 'chain', 'цепь', 'ссылка', 'pin', 'clip', 'alt', 'connect'],
    },
    {
      name: 'LinkAltBroken',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['link', 'alt', 'broken', 'ссылка', 'pin', 'clip', 'connect', 'disconnect', 'разорван'],
    },
    {
      name: 'LinkAltHalf',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['link', 'alt', 'half', 'ссылка', 'pin', 'clip', 'connect', 'частично', 'разорван'],
    },
    {
      name: 'LinkedIn',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: ['linked', 'in', 'social', 'logo', 'лого', 'линкед', 'ин'],
    },
    {
      name: 'LinkExternal',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'link',
        'external',
        'arrow',
        'стрелка',
        'up',
        'right',
        'наверх',
        'верх',
        'право',
        'вправо',
        'направо',
        'share',
        'outside',
      ],
    },
    {
      name: 'LinkInternal',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'link',
        'internal',
        'arrow',
        'стрелка',
        'down',
        'left',
        'вниз',
        'низ',
        'влево',
        'лево',
        'налево',
        'inside',
        'внутрь',
      ],
    },
    {
      name: 'ListAddBottom',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: ['list', 'add', 'bottom', 'список', 'plus', 'добавить', 'низ', 'вниз', 'плюс'],
    },
    {
      name: 'ListAddTop',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: ['list', 'add', 'top', 'список', 'добавить', 'верх', 'вверх', 'plus', 'плюс'],
    },
    {
      name: 'ListBullet',
      size: ['m', 's', 'xs', 'xxs'],
      group: 'Format',
      tags: [
        'list',
        'bullet',
        'список',
        'буллиты',
        'ul',
        'unordered',
        'нумерованный',
        'wysiwyg',
        'editor',
      ],
    },
    {
      name: 'ListCheck',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'list',
        'check',
        'список',
        'галочка',
        'wysiwyg',
        'mark',
        'чеклист',
        'to',
        'do',
        'tasks',
        'задачи',
        'сделать',
      ],
    },
    {
      name: 'ListCheckAlt',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: ['list', 'check', 'alt', 'список', 'галочка', 'wysiwyg', 'mark', 'отметить', 'сделано'],
    },
    {
      name: 'ListNumber',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'list',
        'number',
        'ol',
        'ordered',
        'нумерованный',
        'список',
        'числа',
        'one',
        'two',
        'three',
      ],
    },
    {
      name: 'LockNo',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['lock', 'no', 'unlock', 'замок', 'снять', 'разблокировать', 'access', 'key', 'доступ'],
    },
    {
      name: 'LockYes',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['lock', 'yes', 'замок', 'заблокировать', 'access', 'key', 'доступ'],
    },
    {
      name: 'MagicWand',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'magic',
        'wand',
        'фокусник',
        'волшебная',
        'палочка',
        'trick',
        'magician',
        'illusionist',
        'select',
      ],
    },
    {
      name: 'Magnet',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['magnet', 'магнит', 'pole', 'north', 'south', 'field', 'поле'],
    },
    {
      name: 'Mail',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'mail',
        'envelope',
        'post',
        'почта',
        'box',
        'конверт',
        'email',
        'имейл',
        'мэил',
        'мейл',
        'емейл',
      ],
    },
    {
      name: 'MailOutline',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'mail',
        'envelope',
        'post',
        'почта',
        'box',
        'конверт',
        'email',
        'имейл',
        'мэил',
        'мейл',
        'емейл',
        'outline',
      ],
    },
    {
      name: 'MailOpen',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['mail', 'email', 'e-mail', 'имейл', 'мэил', 'мэйл', 'меил'],
    },
    {
      name: 'MailOutlineOpen',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['mail', 'email', 'e-mail', 'имейл', 'мэил', 'мэйл', 'меил', 'outline'],
    },
    {
      name: 'MailSent',
      size: ['l', 'm', 's', 'xs'],
      group: 'Action',
      tags: [
        'mail',
        'envelope',
        'post',
        'почта',
        'box',
        'конверт',
        'email',
        'имейл',
        'мэил',
        'мейл',
        'емейл',
        'sent',
        'отправлено',
        'move',
        'push',
      ],
    },
    {
      name: 'MathMinus',
      size: ['m', 's', 'xs', 'xxs'],
      group: 'Action',
      tags: [
        'math',
        'minus',
        'минус',
        'calculator',
        'уменьшить',
        'hyphen',
        'dash',
        'тире',
        'дефис',
        'прочерк',
        'none',
        'null',
      ],
    },
    {
      name: 'MathMinusAlt',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'math',
        'minus',
        'минус',
        'calculator',
        'уменьшить',
        'hyphen',
        'dash',
        'тире',
        'дефис',
        'прочерк',
        'none',
        'null',
        'alt',
      ],
    },
    {
      name: 'MathPlus',
      size: ['m', 's', 'xs', 'xxs'],
      group: 'Action',
      tags: ['math', 'plus', 'плюс', 'добавить', 'add'],
    },
    {
      name: 'MathPlusAlt',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['math', 'plus', 'плюс', 'добавить', 'add', 'alt'],
    },
    {
      name: 'Medkit',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'medkit',
        'health',
        'pack',
        'hp',
        'аптечка',
        'здоровье',
        'хелс',
        'хэлс',
        'лечение',
        'doctor',
      ],
    },
    {
      name: 'Megaphone',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'megaphone',
        'speaker',
        'орало',
        'мегафон',
        'громко',
        'говоритель',
        'loud',
        'trumpet',
        'sound',
        'звук',
      ],
    },
    {
      name: 'Microphone',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'microphone',
        'podcast',
        'подкаст',
        'микрофон',
        'запись',
        'rec',
        'record',
        'voice',
        'голос',
        'sound',
        'звук',
      ],
    },
    {
      name: 'Mobile',
      size: ['m', 's', 'xs'],
      group: 'Hardware',
      tags: ['mobile', 'cell', 'iphone', 'android', 'телефон', 'мобильный', 'device'],
    },
    {
      name: 'MoneyCoins',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'money',
        'coins',
        'currency',
        'валюта',
        'money',
        'pay',
        'монета',
        'token',
        'токен',
        'платеж',
      ],
    },
    {
      name: 'MoveAlt',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'move',
        'alt',
        'dot',
        'menu',
        'меню',
        'гамбургер',
        'hamburger',
        'kebab',
        'more',
        'details',
        'двигать',
      ],
    },
    {
      name: 'Museum',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'museum',
        'building',
        'ancient',
        'old',
        'музей',
        'старый',
        'version',
        'версия',
        'vintage',
      ],
    },
    {
      name: 'News',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['news', 'paper', 'новости', 'газета', 'banner', 'document'],
    },
    {
      name: 'NotebookDemo',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['notebook', 'demo', 'laptop', 'ноутбук', 'лэптоп', 'play', 'демо', 'video', 'видео'],
    },
    {
      name: 'Notification',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'notification',
        'bell',
        'notice',
        'ring',
        'колокол',
        'колокольчик',
        'уведомление',
        'нотификация',
        'new',
      ],
    },
    {
      name: 'Opera',
      size: ['m', 's', 'xs'],
      group: 'Hardware',
      tags: ['opera', 'browser', 'браузер', 'опера', 'logo', 'лого'],
    },
    {
      name: 'Organic',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'organic',
        'green',
        'healthy',
        'leaf',
        'лист',
        'листок',
        'зеленый',
        'органик',
        'traffic',
      ],
    },
    {
      name: 'OrientationLandscape',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'orientation',
        'landscape',
        'switch',
        'wysiwyg',
        'editor',
        'редактор',
        'положение',
        'ориентация',
        'пейзаж',
        'horizontal',
        'text',
        'layout',
      ],
    },
    {
      name: 'OrientationPortrait',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'orientation',
        'portrait',
        'switch',
        'wysiwyg',
        'editor',
        'редактор',
        'положение',
        'ориентация',
        'портрет',
        'vertical',
        'text',
        'layout',
      ],
    },
    {
      name: 'Pause',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['pause', 'stop', 'пауза', 'стоп'],
    },
    {
      name: 'Picture',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'picture',
        'image',
        'photo',
        'картинка',
        'картина',
        'изображение',
        'иллюстрация',
        'фото',
      ],
    },
    {
      name: 'PictureAdd',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'picture',
        'image',
        'photo',
        'картинка',
        'картина',
        'изображение',
        'иллюстрация',
        'фото',
        'add',
        'plus',
        'плюс',
      ],
    },
    {
      name: 'PictureFrame',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'picture',
        'frame',
        'painting',
        'рамка',
        'image',
        'photo',
        'картинка',
        'картина',
        'изображение',
        'иллюстрация',
        'фото',
      ],
    },
    {
      name: 'Pictures',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'pictures',
        'image',
        'photo',
        'картинка',
        'картина',
        'изображение',
        'иллюстрация',
        'фото',
      ],
    },
    {
      name: 'Pin',
      size: ['m', 's', 'xs'],
      group: 'Map',
      tags: [
        'pin',
        'map',
        'navigation',
        'mark',
        'метка',
        'пометить',
        'отметить',
        'булавка',
        'карта',
      ],
    },
    {
      name: 'PinList',
      size: ['m', 's', 'xs'],
      group: 'Map',
      tags: [
        'pin',
        'list',
        'navigation',
        'map',
        'mark',
        'метка',
        'пометить',
        'отметить',
        'булавка',
        'список',
        'items',
        'карта',
      ],
    },
    {
      name: 'PinMap',
      size: ['m', 's', 'xs'],
      group: 'Map',
      tags: [
        'pin',
        'map',
        'navigation',
        'mark',
        'метка',
        'пометить',
        'отметить',
        'булавка',
        'список',
        'карта',
      ],
    },
    {
      name: 'PinNo',
      size: ['m', 's', 'xs'],
      group: 'Map',
      tags: [
        'pin',
        'map',
        'navigation',
        'mark',
        'метка',
        'пометить',
        'отметить',
        'булавка',
        'список',
        'карта',
        'no',
        'crossed',
        'карта',
      ],
    },
    {
      name: 'Pins',
      size: ['m', 's', 'xs'],
      group: 'Map',
      tags: [
        'pins',
        'map',
        'navigation',
        'map',
        'mark',
        'метка',
        'пометить',
        'отметить',
        'булавка',
        'карта',
      ],
    },
    {
      name: 'Pinterest',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: ['pinterest', 'пинтерест', 'лого', 'logo', 'social'],
    },
    {
      name: 'PinUsd',
      size: ['m', 's', 'xs'],
      group: 'Map',
      tags: [
        'pin',
        'usd',
        'navigation',
        'map',
        'mark',
        'метка',
        'пометить',
        'отметить',
        'булавка',
        'карта',
        'currency',
        'usd',
        'united',
        'states',
        'dollar',
        'валюта',
        'money',
        'pay',
        'US',
        'США',
        'америка',
        'платеж',
      ],
    },
    {
      name: 'Popup',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'popup',
        'window',
        'modal',
        'spotlight',
        'new',
        'окно',
        'всплывающее',
        'попап',
        'открыть',
      ],
    },
    {
      name: 'PositionBottom',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'position',
        'bottom',
        'format',
        'align',
        'text',
        'layout',
        'форматирование',
        'текст',
        'плилипание',
        'wysiwyg',
        'editor',
        'редактор',
        'низ',
      ],
    },
    {
      name: 'PositionLeft',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'position',
        'left',
        'format',
        'align',
        'text',
        'layout',
        'форматирование',
        'текст',
        'плилипание',
        'wysiwyg',
        'editor',
        'редактор',
        'лево',
        'влево',
        'налево',
      ],
    },
    {
      name: 'PositionRight',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'position',
        'right',
        'format',
        'align',
        'text',
        'layout',
        'форматирование',
        'текст',
        'плилипание',
        'wysiwyg',
        'editor',
        'редактор',
        'право',
        'вправо',
        'направо',
      ],
    },
    {
      name: 'PositionTop',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'position',
        'top',
        'format',
        'align',
        'text',
        'layout',
        'форматирование',
        'текст',
        'плилипание',
        'wysiwyg',
        'editor',
        'редактор',
        'верх',
        'вверх',
      ],
    },
    {
      name: 'Pulse',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'pulse',
        'health',
        'heart',
        'pulse',
        'beep',
        'monitor',
        'hr',
        'пульс',
        'здоровье',
        'сердце',
        'линия',
      ],
    },
    {
      name: 'Question',
      size: ['l', 'm', 's', 'xs'],
      group: 'Status',
      tags: ['question', 'mark', 'вопрос', 'знак', '?'],
    },
    {
      name: 'QuestionAlt',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['question', 'mark', 'вопрос', 'знак', '?', 'alt'],
    },
    {
      name: 'Reload',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'reload',
        'repeat',
        'arrow',
        'стрелка',
        'пере',
        'загрузка',
        'повторить',
        'обновить',
        'left',
        'right',
        'лево',
        'право',
        'влево',
        'налево',
        'вправо',
        'направо',
      ],
    },
    {
      name: 'Repeat',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'repeat',
        'reload',
        'arrow',
        'стрелка',
        'пере',
        'загрузка',
        'повторить',
        'обновить',
        'left',
        'влево',
        'налево',
      ],
    },
    {
      name: 'Report',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'report',
        'отчет',
        'form',
        'fill',
        'форма',
        'doctors',
        'note',
        'document',
        'документ',
        'заполнить',
        'paper',
        'бумага',
      ],
    },
    {
      name: 'ResizeCol',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'resize',
        'col',
        'horizontal',
        'arrow',
        'стрелка',
        'размер',
        'expand',
        'fullscreen',
        'enlarge',
        'open',
        'весь',
        'экран',
        'увеличить',
        'zoom',
        'big',
        'large',
        'расширить',
      ],
    },
    {
      name: 'ResizeRow',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: [
        'resize',
        'row',
        'vertical',
        'arrow',
        'стрелка',
        'размер',
        'expand',
        'fullscreen',
        'enlarge',
        'open',
        'весь',
        'экран',
        'увеличить',
        'zoom',
        'big',
        'large',
        'расширить',
      ],
    },
    {
      name: 'Robot',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['robot', 'робот', 'cyborg', 'киборг', 'ai', 'artificial', 'intelligence'],
    },
    {
      name: 'Rss',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['rss', 'RDF', 'site', 'summary', 'feed', 'subscription', 'подписка'],
    },
    {
      name: 'Safari',
      size: ['m', 's', 'xs'],
      group: 'Hardware',
      tags: ['safari', 'browser', 'logo', 'лого', 'сафари', 'apple', 'яблоко', 'эпл'],
    },
    {
      name: 'Search',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['search', 'поиск', 'magnifier', 'zoom'],
    },
    {
      name: 'Semrush',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['semrush', 'семраш', 'фейсбук', 'fireball', 'фаерболл'],
    },
    {
      name: 'Sent',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'sent',
        'paper',
        'plane',
        'telegram',
        'бумага',
        'самолет',
        'отправлено',
        'mail',
        'почта',
      ],
    },
    {
      name: 'Serp',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'serp',
        'search',
        'engine',
        'results',
        'window',
        'browser',
        'popup',
        'всплывашка',
        'серп',
      ],
    },
    {
      name: 'Settings',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['settings', 'parameters', 'cog', 'wheel', 'настройки', 'system', 'preferences'],
    },
    {
      name: 'SettingsAlt',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['settings', 'parameters', 'cog', 'wheel', 'настройки', 'system', 'preferences', 'alt'],
    },
    {
      name: 'SharedToUser',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'shared',
        'user',
        'arrow',
        'sharing',
        'пошарили',
        'пошарил',
        'пошарено',
        'пользователь',
      ],
    },
    {
      name: 'ShowNo',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'show',
        'no',
        'глаз',
        'eye',
        'просмотр',
        'скрыть',
        'view',
        'hide',
        'disable',
        'transparency',
        'visibility',
      ],
    },
    {
      name: 'ShowYes',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'show',
        'yes',
        'глаз',
        'eye',
        'просмотр',
        'показать',
        'view',
        'enable',
        'transparency',
        'visibility',
      ],
    },
    {
      name: 'SideMenuLeft',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: [
        'side',
        'menu',
        'left',
        'panel',
        'боковое',
        'меню',
        'лево',
        'налево',
        'влево',
        'navigation',
        'slide',
      ],
    },
    {
      name: 'SideMenuRight',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: [
        'side',
        'menu',
        'right',
        'panel',
        'боковое',
        'меню',
        'право',
        'направо',
        'вправо',
        'navigation',
        'slide',
      ],
    },
    {
      name: 'Sitemap',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'sitemap',
        'карта',
        'сайта',
        'site',
        'structure',
        'visualisation',
        'map',
        'scheme',
        'block',
      ],
    },
    {
      name: 'Skype',
      size: ['m', 's', 'xs'],
      group: 'Hardware',
      tags: ['skype', 'logo', 'скайп', 'лого', 'файлообменник'],
    },
    {
      name: 'SmileHappy',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['smile', 'happy', 'emoji', 'face', 'emotion', 'эмоция', 'лицо', 'react', 'счастливый'],
    },
    {
      name: 'SmileNeutral',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'smile',
        'neutral',
        'emoji',
        'face',
        'emotion',
        'эмоция',
        'лицо',
        'react',
        'нейтральный',
      ],
    },
    {
      name: 'SmileSad',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['smile', 'sad', 'emoji', 'face', 'emotion', 'эмоция', 'лицо', 'react', 'грустный'],
    },
    {
      name: 'SmileSimple',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'smile',
        'smiley',
        'emoji',
        'face',
        'emotion',
        'эмоция',
        'лицо',
        'react',
        'веселый',
        'улыбка',
        'simple',
      ],
    },
    {
      name: 'SortAsc',
      size: ['m', 's', 'xs', 'xxs'],
      group: 'Navigation',
      tags: [
        'sort',
        'asc',
        'сортировка',
        'table',
        'data',
        'данные',
        'wysiwyg',
        'возрастание',
        'ascending',
        'funnel',
        'filter',
      ],
    },
    {
      name: 'SortDesc',
      size: ['m', 's', 'xs', 'xxs'],
      group: 'Navigation',
      tags: [
        'sort',
        'desc',
        'сортировка',
        'table',
        'data',
        'данные',
        'wysiwyg',
        'убывание',
        'descending',
        'funnel',
        'filter',
      ],
    },
    {
      name: 'SortDown',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: [
        'sort',
        'down',
        'сортировка',
        'таблица',
        'table',
        'data',
        'filter',
        'wysiwyg',
        'arrow',
        'стрелка',
        'вниз',
        'низ',
      ],
    },
    {
      name: 'SortLeft',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: [
        'sort',
        'left',
        'сортировка',
        'таблица',
        'table',
        'data',
        'filter',
        'wysiwyg',
        'arrow',
        'стрелка',
        'лево',
        'влево',
        'налево',
      ],
    },
    {
      name: 'SortRight',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: [
        'sort',
        'right',
        'сортировка',
        'таблица',
        'table',
        'data',
        'filter',
        'wysiwyg',
        'arrow',
        'стрелка',
        'право',
        'вправо',
        'направо',
      ],
    },
    {
      name: 'SortUp',
      size: ['m', 's', 'xs'],
      group: 'Navigation',
      tags: [
        'sort',
        'up',
        'сортировка',
        'таблица',
        'table',
        'data',
        'filter',
        'wysiwyg',
        'arrow',
        'стрелка',
        'верх',
        'наверх',
      ],
    },
    {
      name: 'Table',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: ['table', 'таблица', 'column', 'row', 'header', 'data'],
    },
    {
      name: 'Tablet',
      size: ['m', 's', 'xs'],
      group: 'Hardware',
      tags: ['tablet', 'device', 'mobile', 'ipad', 'планшет', 'таблет', 'фаблет', 'phablet'],
    },
    {
      name: 'Tag',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['tag', 'shopping', 'save', 'bookmark', 'note', 'тэг', 'шоппинг', 'отметка'],
    },
    {
      name: 'TagOutline',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: ['tag', 'shopping', 'save', 'bookmark', 'note', 'тэг', 'шоппинг', 'отметка', 'outline'],
    },
    {
      name: 'Telescope',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['telescope', 'телескоп', 'star', 'gazing', 'zoom'],
    },
    {
      name: 'Text',
      size: ['m', 's', 'xs'],
      group: 'Format',
      tags: ['text', 'текст', 'wysiwyg', 'editor', 'letter', 'формат', 'format'],
    },
    {
      name: 'ThumbDown',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'thumb',
        'down',
        'большой',
        'палец',
        'like',
        'dislike',
        'не',
        'нравится',
        'reaction',
        'hand',
      ],
    },
    {
      name: 'ThumbUp',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['thumb', 'up', 'большой', 'палец', 'like', 'нравится', 'reaction', 'hand'],
    },
    {
      name: 'Tile',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: ['tile', 'плитка', 'view', 'menu', 'меню', 'sort', 'сортировка'],
    },
    {
      name: 'TimeClock',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['time', 'clock', 'время', 'часы', 'wait', 'loading', 'soon'],
    },
    {
      name: 'TimeHourglass',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['time', 'hourglass', 'время', 'часы', 'песочные', 'wait', 'loading', 'загрузка'],
    },
    {
      name: 'TimeWristwatch',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['time', 'wristwatch', 'время', 'часы', 'наручные', 'котлы', 'hand'],
    },
    {
      name: 'TimeNight',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'time',
        'moon',
        'crescent',
        'night',
        'ночь',
        'луна',
        'месяц',
        'полумесяц',
        'время',
        'сутки',
      ],
    },
    {
      name: 'TimeDay',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'time',
        'sun',
        'day',
        'light',
        'daylight',
        'morning',
        'утро',
        'солнце',
        'время',
        'день',
        'сутки',
      ],
    },
    {
      name: 'Toxic',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'toxic',
        'hazard',
        'hazardous',
        'toxin',
        'токсин',
        'danger',
        'опасно',
        'токсично',
        'знак',
        'sign',
      ],
    },
    {
      name: 'Trash',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'trash',
        'bin',
        'trash',
        'мусор',
        'корзина',
        'помойка',
        'delete',
        'remove',
        'rubbish',
        'waste',
        'litter',
        'garbage',
        'помои',
      ],
    },
    {
      name: 'Trello',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: ['trello', 'logo', 'лого', 'трелло', 'task', 'manager'],
    },
    {
      name: 'Twitter',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: ['twitter', 'logo', 'лого', 'social', 'твиттер'],
    },
    {
      name: 'User',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['user', 'пользователь', 'human', 'male', 'личный', 'кабинет'],
    },
    {
      name: 'UserGroup',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['user', 'group', 'пользователь', 'human', 'male', 'личный', 'кабинет'],
    },
    {
      name: 'UserGroupNo',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['user', 'group', 'no', 'пользователь', 'human', 'male', 'личный', 'кабинет'],
    },
    {
      name: 'Vacation',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'vacation',
        'чемодан',
        'путешествие',
        'trolley',
        'case',
        'bag',
        'carry',
        'moving',
        'plane',
        'train',
        'flight',
        'travel',
      ],
    },
    {
      name: 'Value',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'value',
        'forty',
        'two',
        '42',
        'number',
        'answer',
        'ultimate',
        'question',
        'life',
        'universe',
        'everything',
        'hitchhiker',
        'guide',
      ],
    },
    {
      name: 'Video',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['video', 'видео', 'play', 'воспроизвести', 'preview'],
    },
    {
      name: 'VideoAlt',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['video', 'alt', 'видео', 'play', 'воспроизвести', 'preview'],
    },
    {
      name: 'VideoStop',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: ['video', 'видео', 'stop', 'остановить', 'preview'],
    },
    {
      name: 'Vk',
      size: ['m', 's', 'xs'],
      group: 'Social',
      tags: ['vk', 'social', 'vkontakte', 'вконтакте', 'logo', 'лого'],
    },
    {
      name: 'VolumeUp',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'volume',
        'up',
        'громкость',
        'increase',
        'music',
        'play',
        'loud',
        'speaker',
        'megaphone',
        'орало',
        'мегафон',
        'громко',
        'говоритель',
        'trumpet',
        'sound',
        'звук',
      ],
    },
    {
      name: 'Warning',
      size: ['m', 's', 'xs'],
      group: 'Status',
      tags: [
        'warning',
        'exclamation',
        'danger',
        'sign',
        'опасно',
        'внимание',
        'caution',
        'careful',
        'watch',
        'out',
      ],
    },
    {
      name: 'Webpages',
      size: ['m', 's', 'xs'],
      group: 'Misc',
      tags: [
        'webpages',
        'popup',
        'window',
        'modal',
        'spotlight',
        'new',
        'окно',
        'всплывающее',
        'попап',
        'открыть',
        'browser',
        'браузер',
      ],
    },
    {
      name: 'Youtube',
      size: ['l', 'm', 's', 'xs'],
      group: 'Social',
      tags: ['youtube', 'video', 'видео', 'social', 'logo', 'логотип'],
    },
    {
      name: 'YoutubeRed',
      size: ['l', 'm', 's', 'xs'],
      group: 'Color',
      tags: ['youtube', 'video', 'видео', 'social', 'logo', 'логотип'],
    },
    {
      name: 'YoutubeAlt',
      size: ['l', 'm', 's', 'xs'],
      group: 'Color',
      tags: ['youtube', 'video', 'видео', 'social', 'logo', 'логотип'],
    },
    {
      name: 'WhatsApp',
      size: ['l', 'm', 's', 'xs'],
      group: 'Color',
      tags: ['whatsapp', 'вотсап', 'ватсап', 'social', 'logo', 'логотип'],
    },
    {
      name: 'YoutubePlaceholder',
      size: ['l', 'm', 's', 'xs'],
      group: 'Social',
      tags: [
        'youtube',
        'placeholder',
        'video',
        'видео',
        'social',
        'ellipsis',
        'dots',
        'wait',
        'loading',
        'three',
        'многоточие',
        'троеточие',
      ],
    },
    {
      name: 'ZoomMinus',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'zoom',
        'minus',
        'magnifier',
        'glass',
        'зум',
        'уменьшение',
        'лупа',
        'minus',
        'минус',
        'minimize',
      ],
    },
    {
      name: 'ZoomPlus',
      size: ['m', 's', 'xs'],
      group: 'Action',
      tags: [
        'zoom',
        'plus',
        'magnifier',
        'glass',
        'зум',
        'увеличие',
        'лупа',
        'плюс',
        'plus',
        'enlarge',
        'expand',
        'enhance',
      ],
    },
    {
      name: 'AmericanExpress',
      size: ['32'],
      group: 'Pay',
      tags: [
        'american',
        'express',
        'американ',
        'экспресс',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'ApplePay',
      size: ['32'],
      group: 'Pay',
      tags: [
        'apple',
        'pay',
        'эпл',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'CreditCard',
      size: ['32'],
      group: 'Pay',
      tags: [
        'credit',
        'card',
        'bank',
        'visa',
        'mastercard',
        'payment',
        'currency',
        'method',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'Bitcoin',
      size: ['32'],
      group: 'Pay',
      tags: [
        'bitcoin',
        'биткоин',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'Cash',
      size: ['32'],
      group: 'Pay',
      tags: [
        'cash',
        'наличные',
        'bill',
        'банкнота',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'Cheque',
      size: ['32'],
      group: 'Pay',
      tags: [
        'cheque',
        'чек',
        'bill',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'Diners',
      size: ['32'],
      group: 'Pay',
      tags: [
        'diners',
        'club',
        'дайнер',
        'клаб',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'Discover',
      size: ['32'],
      group: 'Pay',
      tags: [
        'discover',
        'дискавер',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'Financing',
      size: ['32'],
      group: 'Pay',
      tags: [
        'financing',
        'coins',
        'монеты',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'GooglePay',
      size: ['32'],
      group: 'Pay',
      tags: [
        'google',
        'pay',
        'гугл',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'Invoice',
      size: ['32'],
      group: 'Pay',
      tags: [
        'invoice',
        'инвойс',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'Mastercard',
      size: ['32'],
      group: 'Pay',
      tags: [
        'mastercard',
        'мастер',
        'кард',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'PayPal',
      size: ['32'],
      group: 'Pay',
      tags: [
        'pay',
        'pal',
        'пэйпол',
        'пэйпэл',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'SamsungPay',
      size: ['32'],
      group: 'Pay',
      tags: [
        'samsung',
        'pay',
        'самсунг',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'TravelersCheck',
      size: ['32'],
      group: 'Pay',
      tags: [
        'travelers',
        'check',
        'чек',
        'путешествие',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'UnionPay',
      size: ['32'],
      group: 'Pay',
      tags: [
        'union',
        'pay',
        'энион',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'Visa',
      size: ['32'],
      group: 'Pay',
      tags: [
        'visa',
        'виза',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'VPay',
      size: ['32'],
      group: 'Pay',
      tags: [
        'visa',
        'v pay',
        'pay',
        'euro',
        'sepa',
        'виза',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'Maestro',
      size: ['32'],
      group: 'Pay',
      tags: [
        'maestro',
        'mastercard',
        'debit',
        'маестро',
        'маэстро',
        'мастеркард',
        'мастер',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'Bacs',
      size: ['32'],
      group: 'Pay',
      tags: [
        'bacs',
        'uk',
        'pay',
        'payment',
        'schemes',
        'limited',
        'бакс',
        'logo',
        'лого',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'DirectCredit',
      size: ['32'],
      group: 'Pay',
      tags: [
        'bacs',
        'direct',
        'credit',
        'payment',
        'currency',
        'method',
        'card',
        'credit',
        'debit',
        'платеж',
        'карта',
        'метод',
        'валюта',
      ],
    },
    {
      name: 'FeaturedImage',
      size: ['l', 'm', 's', 'xs', 'xxs'],
      group: 'Misc',
      tags: [
        'feature',
        'featured',
        'image',
        'picture',
        'pictures',
        'serp',
        'изображение',
        'картинка',
        'серп',
      ],
    },
    {
      name: 'FeaturedVideo',
      size: ['l', 'm', 's', 'xs', 'xxs'],
      group: 'Misc',
      tags: ['feature', 'featured', 'video', 'serp', 'видео', 'серп'],
    },
  ],
};

const Icons = importAll(require.context('@semcore/icon/lib', true, /^\.\/.*\.js$/));
const icons = {}; // {name, fn}

Object.keys(Icons).forEach((nameFile) => {
  const fn = Icons[nameFile];
  const name = fn.displayName;
  if (fn && name && name !== 'Icon') {
    icons[name] = fn;
  }
});

function importAll(r) {
  return r.keys().reduce((components, key) => {
    const module = r(key);

    if (module.default) {
      components[key] = module.default;
    } else {
      components[key] = module;
    }
    return components;
  }, {});
}

export default () => <Components icons={icons} json={dataIcons} old />;
