#!/usr/bin/env sh

echo "$GITHUB_SECRET" > ./.gh-auth-token.txt
gh auth login --with-token < ./.gh-auth-token.txt
rm ./.gh-auth-token.txt
version="$(cat semcore/ui/package.json | jq -r .version)"
git diff master --patch -- semcore/ui/CHANGELOG.md | grep '^+++' --invert-match | grep '^+' | cut -c 2- > .github-release-notes.txt
gh release create "v$version" --title "v$version" --notes-file .github-release-notes.txt
rm .github-release-notes.txt