import Accrordion from '@semcore/ui/accordion';
import type { Meta, StoryObj } from '@storybook/react-vite';

import { BasicUsageTest } from './__tests__/basic-usage.test';
import BasicExample, { defaultProps as BasicExampleProps } from './examples/basic_usage';
import CustomStylesExample from './examples/custom_styles';
import HeadingTagExample from './examples/heading_tag';
import NonCompactExample from './examples/non_compact';
import OneSectionOpeningExample from './examples/one_section_opening';
import SeoExample from './examples/seo';
import { playWrapper } from '../../../utils/playWrapper';
const meta: Meta<typeof Accrordion> = {
  title: 'Components/Accordion/Documentation',
  component: Accrordion,
};
export default meta;
type Story = StoryObj<typeof Accrordion>;
export const Basic: StoryObj<typeof BasicExampleProps> = {
  render: BasicExample,
  argTypes: {
    w: {
      control: { type: 'number' },
    },
    h: {
      control: { type: 'number' },
    },
    duration: {
      control: { type: 'number' },
    },
    overflowHidden: {
      control: { type: 'boolean' },
    },
    use: {
      control: { type: 'select' },
      options: ['primary', 'secondary'],
    },
    defaultHeight: {
      control: { type: 'select' },
      options: ['auto', '100%'],
    },
  },
  args: BasicExampleProps,
  play: playWrapper(BasicUsageTest),
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport type { NSAccordion } from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport type { BoxProps } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\ntype ExampleAccordionProps = NSAccordion.Props & { duration?: number } & NSAccordion.Item.Collapse.Props & BoxProps;\n\nconst Demo = (props: ExampleAccordionProps) => {\n  const [value, onChange] = React.useState([0]);\n\n  return (\n    <Accordion value={value} onChange={(value: any) => onChange(value)} duration={props.duration} use={props.use}>\n      {[...new Array(3)].map((_, index) => (\n        <Accordion.Item value={index} key={index} disabled={index === 2}>\n          <Accordion.Item.Toggle pb={2} w={props.w} h={props.h}>\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Section\n              {\' \'}\n              {index + 1}\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse overflowHidden={props.overflowHidden} defaultHeight={props.defaultHeight}>\n            <Box p=\'12px 24px 24px\'>{`Hello Section ${index + 1}`}</Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n      ))}\n    </Accordion>\n  );\n};\n\nexport const defaultProps: ExampleAccordionProps = {\n  duration: undefined,\n  use: undefined,\n  overflowHidden: undefined,\n  defaultHeight: undefined,\n  w: undefined,\n  h: undefined,\n};\n\nDemo.defaultProps = defaultProps;\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport type { NSAccordion } from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport type { BoxProps } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\ntype ExampleAccordionProps = NSAccordion.Props & { duration?: number } & NSAccordion.Item.Collapse.Props & BoxProps;\n\nconst Demo = (props: ExampleAccordionProps) => {\n  const [value, onChange] = React.useState([0]);\n\n  return (\n    <Accordion value={value} onChange={(value: any) => onChange(value)} duration={props.duration} use={props.use}>\n      {[...new Array(3)].map((_, index) => (\n        <Accordion.Item value={index} key={index} disabled={index === 2}>\n          <Accordion.Item.Toggle pb={2} w={props.w} h={props.h}>\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Section\n              {\' \'}\n              {index + 1}\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse overflowHidden={props.overflowHidden} defaultHeight={props.defaultHeight}>\n            <Box p=\'12px 24px 24px\'>{`Hello Section ${index + 1}`}</Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n      ))}\n    </Accordion>\n  );\n};\n\nexport const defaultProps: ExampleAccordionProps = {\n  duration: undefined,\n  use: undefined,\n  overflowHidden: undefined,\n  defaultHeight: undefined,\n  w: undefined,\n  h: undefined,\n};\n\nDemo.defaultProps = defaultProps;\n\nexport default Demo;\n' },
};
export const CustomStyles: Story = {
  render: CustomStylesExample,
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst cn = (...classes: any[]) => classes.filter(Boolean).join(\' \');\n\nconst Demo = () => {\n  return (\n    <>\n      <style>\n        {`\n          /* In this example we are forced to use more specific css-selectors to override the default Vitepress styles */\n          .vp-doc h3.styled-accordion-item {\n            background-color: var(--intergalactic-bg-secondary-neutral);\n            padding: var(--intergalactic-spacing-2x) var(--intergalactic-spacing-3x);\n            color: var(--intergalactic-text-primary);\n            margin-bottom: var(--intergalactic-spacing-05x);\n          }\n          .vp-doc h3.styled-accordion-item:first-of-type {\n            border-radius: var(--intergalactic-control-rounded) var(--intergalactic-control-rounded) 0 0;\n          }\n          .vp-doc h3.styled-accordion-item:last-of-type {\n            border-radius: 0 0 var(--intergalactic-control-rounded) var(--intergalactic-control-rounded);\n          }\n          .vp-doc h3.styled-accordion-item-selected {\n            background-color: var(--intergalactic-bg-secondary-neutral-hover);\n            color: #000;\n          }\n        `}\n      </style>\n      <Accordion>\n        {[...new Array(3)].map((_, index) => (\n          <Accordion.Item value={index} key={index}>\n            {({ selected }) => (\n              <>\n                <Accordion.Item.Toggle\n                  className={cn(\n                    \'styled-accordion-item\',\n                    selected && \'styled-accordion-item-selected\',\n                  )}\n                >\n                  <Accordion.Item.ToggleButton>\n                    <Accordion.Item.Chevron mr={2} />\n                    Section\n                    {\' \'}\n                    {index + 1}\n                  </Accordion.Item.ToggleButton>\n                </Accordion.Item.Toggle>\n                <Accordion.Item.Collapse>\n                  <Box p=\'12px 32px\'>{`Hello Section ${index + 1}`}</Box>\n                </Accordion.Item.Collapse>\n              </>\n            )}\n          </Accordion.Item>\n        ))}\n      </Accordion>\n    </>\n  );\n};\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst cn = (...classes: any[]) => classes.filter(Boolean).join(\' \');\n\nconst Demo = () => {\n  return (\n    <>\n      <style>\n        {`\n          /* In this example we are forced to use more specific css-selectors to override the default Vitepress styles */\n          .vp-doc h3.styled-accordion-item {\n            background-color: var(--intergalactic-bg-secondary-neutral);\n            padding: var(--intergalactic-spacing-2x) var(--intergalactic-spacing-3x);\n            color: var(--intergalactic-text-primary);\n            margin-bottom: var(--intergalactic-spacing-05x);\n          }\n          .vp-doc h3.styled-accordion-item:first-of-type {\n            border-radius: var(--intergalactic-control-rounded) var(--intergalactic-control-rounded) 0 0;\n          }\n          .vp-doc h3.styled-accordion-item:last-of-type {\n            border-radius: 0 0 var(--intergalactic-control-rounded) var(--intergalactic-control-rounded);\n          }\n          .vp-doc h3.styled-accordion-item-selected {\n            background-color: var(--intergalactic-bg-secondary-neutral-hover);\n            color: #000;\n          }\n        `}\n      </style>\n      <Accordion>\n        {[...new Array(3)].map((_, index) => (\n          <Accordion.Item value={index} key={index}>\n            {({ selected }) => (\n              <>\n                <Accordion.Item.Toggle\n                  className={cn(\n                    \'styled-accordion-item\',\n                    selected && \'styled-accordion-item-selected\',\n                  )}\n                >\n                  <Accordion.Item.ToggleButton>\n                    <Accordion.Item.Chevron mr={2} />\n                    Section\n                    {\' \'}\n                    {index + 1}\n                  </Accordion.Item.ToggleButton>\n                </Accordion.Item.Toggle>\n                <Accordion.Item.Collapse>\n                  <Box p=\'12px 32px\'>{`Hello Section ${index + 1}`}</Box>\n                </Accordion.Item.Collapse>\n              </>\n            )}\n          </Accordion.Item>\n        ))}\n      </Accordion>\n    </>\n  );\n};\n\nexport default Demo;\n' },
};
export const HeadingTag: Story = {
  render: HeadingTagExample,
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst Demo = () => {\n  const [value, onChange] = React.useState(null); // or []\n  return (\n    <Accordion value={value} onChange={onChange}>\n      {[...new Array(3)].map((_, index) => (\n        <Accordion.Item value={index} key={index} disabled={index === 2}>\n          <Accordion.Item.Toggle pb={2} tag=\'h2\'>\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Section\n              {\' \'}\n              {index + 1}\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse>\n            <Box p=\'12px 24px 24px\'>{`Hello Section ${index + 1}`}</Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n      ))}\n    </Accordion>\n  );\n};\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst Demo = () => {\n  const [value, onChange] = React.useState(null); // or []\n  return (\n    <Accordion value={value} onChange={onChange}>\n      {[...new Array(3)].map((_, index) => (\n        <Accordion.Item value={index} key={index} disabled={index === 2}>\n          <Accordion.Item.Toggle pb={2} tag=\'h2\'>\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Section\n              {\' \'}\n              {index + 1}\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse>\n            <Box p=\'12px 24px 24px\'>{`Hello Section ${index + 1}`}</Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n      ))}\n    </Accordion>\n  );\n};\n\nexport default Demo;\n' },
};
export const NonCompact: Story = {
  render: NonCompactExample,
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst Demo = () => {\n  return (\n    <Accordion use=\'primary\'>\n      {[...new Array(3)].map((_, index) => (\n        <Accordion.Item value={index} key={index} disabled={index === 2}>\n          <Accordion.Item.Toggle pb={2}>\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Section\n              {\' \'}\n              {index + 1}\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse>\n            <Box p=\'12px 24px 24px\'>{`Hello Section ${index + 1}`}</Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n      ))}\n    </Accordion>\n  );\n};\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst Demo = () => {\n  return (\n    <Accordion use=\'primary\'>\n      {[...new Array(3)].map((_, index) => (\n        <Accordion.Item value={index} key={index} disabled={index === 2}>\n          <Accordion.Item.Toggle pb={2}>\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Section\n              {\' \'}\n              {index + 1}\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse>\n            <Box p=\'12px 24px 24px\'>{`Hello Section ${index + 1}`}</Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n      ))}\n    </Accordion>\n  );\n};\n\nexport default Demo;\n' },
};
export const OneSectionOpening: Story = {
  render: OneSectionOpeningExample,
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst Demo = () => {\n  const [value, onChange] = React.useState(null); // or []\n  return (\n    <Accordion value={value} onChange={onChange}>\n      {[...new Array(3)].map((_, index) => (\n        <Accordion.Item value={index} key={index} disabled={index === 2}>\n          <Accordion.Item.Toggle pb={2}>\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Section\n              {\' \'}\n              {index + 1}\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse>\n            <Box p=\'12px 24px 24px\'>{`Hello Section ${index + 1}`}</Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n      ))}\n    </Accordion>\n  );\n};\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst Demo = () => {\n  const [value, onChange] = React.useState(null); // or []\n  return (\n    <Accordion value={value} onChange={onChange}>\n      {[...new Array(3)].map((_, index) => (\n        <Accordion.Item value={index} key={index} disabled={index === 2}>\n          <Accordion.Item.Toggle pb={2}>\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Section\n              {\' \'}\n              {index + 1}\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse>\n            <Box p=\'12px 24px 24px\'>{`Hello Section ${index + 1}`}</Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n      ))}\n    </Accordion>\n  );\n};\n\nexport default Demo;\n' },
};
export const Seo: Story = {
  render: SeoExample,
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst Demo = () => {\n  const [value, onChange] = React.useState([0]);\n\n  return (\n    <Accordion value={value} onChange={(value: any) => onChange(value)}>\n      {[...new Array(3)].map((_, index) => (\n        <Accordion.Item value={index} key={index} disabled={index === 1}>\n          <Accordion.Item.Toggle pb={2}>\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Section\n              {\' \'}\n              {index + 1}\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse preserveNode>\n            <Box p=\'12px 24px 24px\'>\n              {`Hello Section ${index + 1}`}\n              {\' \'}\n              <a href=\'#\'>Some focusable link in content</a>\n            </Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n      ))}\n    </Accordion>\n  );\n};\n\nexport default Demo;\n' },
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst Demo = () => {\n  const [value, onChange] = React.useState([0]);\n\n  return (\n    <Accordion value={value} onChange={(value: any) => onChange(value)}>\n      {[...new Array(3)].map((_, index) => (\n        <Accordion.Item value={index} key={index} disabled={index === 1}>\n          <Accordion.Item.Toggle pb={2}>\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Section\n              {\' \'}\n              {index + 1}\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse preserveNode>\n            <Box p=\'12px 24px 24px\'>\n              {`Hello Section ${index + 1}`}\n              {\' \'}\n              <a href=\'#\'>Some focusable link in content</a>\n            </Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n      ))}\n    </Accordion>\n  );\n};\n\nexport default Demo;\n' },
};
