import type { Meta, StoryObj } from '@storybook/react-vite';

import AreaExample from './examples/area-chart/area';
import BasicUsageExample from './examples/area-chart/basic-usage';
import CustomLineExample from './examples/area-chart/custom-line';
import EdgeCasesExample from './examples/area-chart/edge-cases';
import InterpolationExample from './examples/area-chart/interpolation';
import LegendAndPatternFillExample from './examples/area-chart/legend-and-pattern-fill';
const meta: Meta = {
  title: 'Components/d3Charts/Documentation/Area-Chart',
};
export default meta;
export const Area: StoryObj = {
  render: AreaExample,
  parameters: { sourceCode: 'import { Plot, XAxis, YAxis, minMax, Area } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport { curveCardinal } from \'d3-shape\';\nimport React from \'react\';\n\nimport AreaMockData from \'../../../__mocks__/area\';\n\nfunction formatDate(value: any, options: any) {\n  return new Intl.DateTimeFormat(\'en\', options).format(value);\n}\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'time\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([0, 10]);\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks ticks={data.map((d) => +d.time)}>\n          {({ index }) => ({\n            children: formatDate(data[index].time, {\n              month: \'short\',\n              day: \'numeric\',\n            }),\n          })}\n        </XAxis.Ticks>\n      </XAxis>\n      <Area x=\'time\' y=\'line\' curve={curveCardinal}>\n        <Area.Dots display />\n      </Area>\n    </Plot>\n  );\n};\n\nconst data = AreaMockData.Default;\n\nexport default Demo;\n' },
};
export const BasicUsage: StoryObj = {
  render: BasicUsageExample,
  parameters: { sourceCode: 'import { Chart } from \'@semcore/ui/d3-chart\';\nimport React from \'react\';\n\nimport AreaMockData from \'../../../__mocks__/area\';\n\nfunction formatDate(value: any) {\n  const options = {\n    month: \'short\' as const,\n    day: \'numeric\' as const,\n  };\n\n  return new Intl.DateTimeFormat(\'en\', options).format(value);\n}\n\nconst Demo = () => {\n  return (\n    <Chart.Area\n      groupKey=\'time\'\n      data={data}\n      plotWidth={500}\n      plotHeight={200}\n      tooltipValueFormatter={formatDate}\n      aria-label=\'Area chart\'\n    />\n  );\n};\n\nconst data = AreaMockData.Default;\n\nexport default Demo;\n' },
};
export const CustomLine: StoryObj = {
  render: CustomLineExample,
  parameters: { sourceCode: 'import { Area, minMax, Plot, XAxis, YAxis } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport { curveCardinal } from \'d3-shape\';\nimport React from \'react\';\n\nimport AreaMockData from \'../../../__mocks__/area\';\n\nconst customLineStyles = { strokeWidth: 4, stroke: \'pink\' };\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'x\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([0, 10]);\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <YAxis>\n        <YAxis.Ticks />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks />\n      </XAxis>\n      <Area x=\'x\' y=\'y\' curve={curveCardinal}>\n        <Area.Line style={customLineStyles} />\n      </Area>\n    </Plot>\n  );\n};\n\nconst data = AreaMockData.XY;\n\nexport default Demo;\n' },
};
export const EdgeCases: StoryObj = {
  render: EdgeCasesExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { Plot, XAxis, YAxis, minMax, HoverLine, Area } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport AreaMockData from \'../../../__mocks__/area\';\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'x\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([0, 10]);\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks />\n      </XAxis>\n      <HoverLine.Tooltip x=\'x\' wMin={100}>\n        {({ xIndex }) => {\n          return {\n            children: (\n              <>\n                <HoverLine.Tooltip.Title>{data[xIndex].x}</HoverLine.Tooltip.Title>\n                <Flex justifyContent=\'space-between\'>\n                  <HoverLine.Tooltip.Dot mr={4}>Line</HoverLine.Tooltip.Dot>\n                  <Text bold>{data[xIndex].y ?? \'n/a\'}</Text>\n                </Flex>\n              </>\n            ),\n          };\n        }}\n      </HoverLine.Tooltip>\n      <Area x=\'x\' y=\'y\'>\n        <Area.Null />\n        <Area.Dots />\n      </Area>\n    </Plot>\n  );\n};\n\nconst data = AreaMockData.XYEdgeCase;\n\nexport default Demo;\n' },
};
export const Interpolation: StoryObj = {
  render: InterpolationExample,
  parameters: { sourceCode: 'import { Plot, XAxis, YAxis, minMax, Area } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport { curveCardinal } from \'d3-shape\';\nimport React from \'react\';\n\nimport AreaMockData from \'../../../__mocks__/area\';\n\nfunction formatDate(value: any, options: any) {\n  return new Intl.DateTimeFormat(\'en\', options).format(value);\n}\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'time\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([0, 10]);\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks ticks={data.map((d) => +d.time)}>\n          {({ value }) => ({\n            children: formatDate(value, {\n              month: \'short\',\n              day: \'numeric\',\n            }),\n          })}\n        </XAxis.Ticks>\n      </XAxis>\n      <Area x=\'time\' y=\'line1\' curve={curveCardinal}>\n        <Area.Dots display />\n      </Area>\n      <Area x=\'time\' y=\'line2\' curve={curveCardinal}>\n        <Area.Dots display />\n      </Area>\n    </Plot>\n  );\n};\n\nconst data = AreaMockData.Interpolation;\n\nexport default Demo;\n' },
};
export const LegendAndPatternFill: StoryObj = {
  render: LegendAndPatternFillExample,
  parameters: { sourceCode: 'import {\n  Plot,\n  XAxis,\n  YAxis,\n  minMax,\n  Area,\n  ChartLegend,\n  makeDataHintsContainer,\n} from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport { curveCardinal } from \'d3-shape\';\nimport React from \'react\';\n\nimport AreaMockData from \'../../../__mocks__/area\';\n\nfunction formatDate(value: any, options: any) {\n  return new Intl.DateTimeFormat(\'en\', options).format(value);\n}\n\nconst dataHints = makeDataHintsContainer();\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'time\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([0, 10]);\n\n  const [legendItems, setLegendItems] = React.useState(\n    Object.keys(data[0])\n      .filter((name) => name !== \'time\')\n      .map((item, index) => {\n        return {\n          id: item,\n          label: `Line ${index + 1}`,\n          checked: true,\n          color: `chart-palette-order-${index + 1}`,\n        };\n      }),\n  );\n\n  const handleChangeVisible = React.useCallback((id: string, isVisible: boolean) => {\n    setLegendItems((prevItems) => {\n      return prevItems.map((item) => {\n        if (item.id === id) {\n          item.checked = isVisible;\n        }\n\n        return item;\n      });\n    });\n  }, []);\n\n  return (\n    <>\n      <ChartLegend\n        dataHints={dataHints}\n        items={legendItems}\n        onChangeVisibleItem={handleChangeVisible}\n        patterns\n        aria-label=\'Area chart legend\'\n      />\n      <Plot\n        data={data}\n        scale={[xScale, yScale]}\n        width={width}\n        height={height}\n        dataHints={dataHints}\n        patterns={true}\n      >\n        <YAxis>\n          <YAxis.Ticks />\n          <YAxis.Grid />\n        </YAxis>\n        <XAxis>\n          <XAxis.Ticks ticks={data.map((d) => +d.time)}>\n            {({ value }) => ({\n              children: formatDate(value, {\n                month: \'short\',\n                day: \'numeric\',\n              }),\n            })}\n          </XAxis.Ticks>\n        </XAxis>\n        {legendItems.map((item) => {\n          return (\n            item.checked && (\n              <Area key={item.id} x=\'time\' y={item.id} curve={curveCardinal} color={item.color}>\n                <Area.Dots display />\n              </Area>\n            )\n          );\n        })}\n      </Plot>\n    </>\n  );\n};\n\nconst data = AreaMockData.Interpolation;\n\nexport default Demo;\n' },
};
