import type { Meta, StoryObj } from '@storybook/react-vite';

import AdvancedUsageExample from './examples/bar-horizontal-compact/advanced_usage';
import BasicUsageExample from './examples/bar-horizontal-compact/basic_usage';
import ClickableAdvancedExample from './examples/bar-horizontal-compact/clickable_advanced';
import ClickableBasicExample from './examples/bar-horizontal-compact/clickable_basic';
import LinksExample from './examples/bar-horizontal-compact/links';
const meta: Meta = {
  title: 'Components/d3Charts/Documentation/Bar-Horizontal-Compact',
};
export default meta;
export const AdvancedUsage: StoryObj = {
  render: AdvancedUsageExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { Plot, CompactHorizontalBar } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport { scaleLinear, scaleBand } from \'d3-scale\';\nimport React from \'react\';\n\nimport BarMockData from \'../../../__mocks__/bar\';\n\nconst Demo = () => {\n  const MARGIN = 30;\n  const width = 500;\n  const height = 500;\n\n  const sum = data.reduce((acc, d) => acc + d.value, 0);\n\n  const xScale = scaleLinear().range([0, width]).domain([0, sum]);\n\n  const yScale = scaleBand()\n    .range([height - MARGIN, MARGIN])\n    .domain([...data].reverse().map((d) => d.category))\n    .paddingInner(0.6)\n    .paddingOuter(0.6);\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <CompactHorizontalBar x=\'value\' y=\'category\'>\n        <CompactHorizontalBar.Hover />\n        <CompactHorizontalBar.Tooltip>\n          {({ index }) => {\n            return {\n              children: (\n                <>\n                  <CompactHorizontalBar.Tooltip.Title>\n                    {data[index].category}\n                  </CompactHorizontalBar.Tooltip.Title>\n                  <Flex justifyContent=\'space-between\'>\n                    <CompactHorizontalBar.Tooltip.Dot mr={4}>Bar</CompactHorizontalBar.Tooltip.Dot>\n                    <Text bold>{data[index].value}</Text>\n                  </Flex>\n                </>\n              ),\n            };\n          }}\n        </CompactHorizontalBar.Tooltip>\n        <CompactHorizontalBar.Annotation>\n          <CompactHorizontalBar.Label />\n          <CompactHorizontalBar.Percent />\n          <CompactHorizontalBar.Value />\n        </CompactHorizontalBar.Annotation>\n        <CompactHorizontalBar.Bar>\n          <CompactHorizontalBar.Bar.Background />\n          <CompactHorizontalBar.Bar.Fill />\n        </CompactHorizontalBar.Bar>\n      </CompactHorizontalBar>\n    </Plot>\n  );\n};\n\nconst data = BarMockData.WithValue;\n\nexport default Demo;\n' },
};
export const ClickableAdvanced: StoryObj = {
  render: ClickableAdvancedExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { Plot, CompactHorizontalBar } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport { scaleLinear, scaleBand } from \'d3-scale\';\nimport React from \'react\';\n\nimport BarMockData from \'../../../__mocks__/bar\';\n\nconst Demo = () => {\n  const MARGIN = 30;\n  const width = 500;\n  const height = 500;\n\n  const sum = data.reduce((acc, d) => acc + d.value, 0);\n\n  const xScale = scaleLinear().range([0, width]).domain([0, sum]);\n\n  const yScale = scaleBand()\n    .range([height - MARGIN, MARGIN])\n    .domain([...data].reverse().map((d) => d.category))\n    .paddingInner(0.6)\n    .paddingOuter(0.2);\n\n  return (\n    <Flex flexWrap gap={5}>\n      <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n        <CompactHorizontalBar x=\'value\' y=\'category\'>\n          <CompactHorizontalBar.Hover />\n          <CompactHorizontalBar.Tooltip>\n            {({ index }) => {\n              return {\n                children: (\n                  <>\n                    <CompactHorizontalBar.Tooltip.Title>\n                      {data[index].category}\n                    </CompactHorizontalBar.Tooltip.Title>\n                    <Flex justifyContent=\'space-between\'>\n                      <CompactHorizontalBar.Tooltip.Dot mr={4}>\n                        Bar\n                      </CompactHorizontalBar.Tooltip.Dot>\n                      <Text bold>{data[index].value}</Text>\n                    </Flex>\n                  </>\n                ),\n              };\n            }}\n          </CompactHorizontalBar.Tooltip>\n          <CompactHorizontalBar.Annotation>\n            <CompactHorizontalBar.Label />\n            <CompactHorizontalBar.Percent />\n            <CompactHorizontalBar.Value />\n          </CompactHorizontalBar.Annotation>\n          <CompactHorizontalBar.Bar onClick={(barIndex: any) => alert(`Bar ${barIndex} clicked`)}>\n            <CompactHorizontalBar.Bar.Background />\n            <CompactHorizontalBar.Bar.Fill />\n          </CompactHorizontalBar.Bar>\n        </CompactHorizontalBar>\n      </Plot>\n    </Flex>\n  );\n};\n\nconst data = BarMockData.WithValue;\n\nexport default Demo;\n' },
};
export const BasicUsage: StoryObj = {
  render: BasicUsageExample,
  parameters: { sourceCode: 'import { Chart } from \'@semcore/ui/d3-chart\';\nimport React from \'react\';\n\nimport BarMockData from \'../../../__mocks__/bar\';\n\nconst Demo = () => {\n  return (\n    <Chart.CompactHorizontalBar\n      y=\'category\'\n      x=\'value\'\n      data={data}\n      plotWidth={500}\n      plotHeight={450}\n      aria-label=\'CompactHorizontalBar chart\'\n    />\n  );\n};\n\nconst data = BarMockData.WithValue;\n\nexport default Demo;\n' },
};
export const ClickableBasic: StoryObj = {
  render: ClickableBasicExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { Chart } from \'@semcore/ui/d3-chart\';\nimport React from \'react\';\n\nimport BarMockData from \'../../../__mocks__/bar\';\n\nconst Demo = () => {\n  return (\n    <Flex flexWrap gap={5}>\n      <Chart.CompactHorizontalBar\n        y=\'category\'\n        x=\'value\'\n        data={data}\n        plotWidth={500}\n        plotHeight={450}\n        onClickBar={(barIndex) => alert(`Bar ${barIndex} clicked`)}\n        aria-label=\'CompactHorizontalBar chart\'\n      />\n    </Flex>\n  );\n};\n\nconst data = BarMockData.WithValue;\n\nexport default Demo;\n' },
};
export const Links: StoryObj = {
  render: LinksExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { Plot, CompactHorizontalBar } from \'@semcore/ui/d3-chart\';\nimport Link from \'@semcore/ui/link\';\nimport { Text } from \'@semcore/ui/typography\';\nimport { scaleLinear, scaleBand } from \'d3-scale\';\nimport React from \'react\';\n\nimport BarMockData from \'../../../__mocks__/bar\';\n\nconst Demo = () => {\n  const MARGIN = 30;\n  const width = 500;\n  const height = 500;\n\n  const sum = data.reduce((acc, d) => acc + d.value, 0);\n\n  const xScale = scaleLinear().range([0, width]).domain([0, sum]);\n\n  const yScale = scaleBand()\n    .range([height - MARGIN, MARGIN])\n    .domain([...data].reverse().map((d) => d.category))\n    .paddingInner(0.6)\n    .paddingOuter(0.2);\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <CompactHorizontalBar x=\'value\' y=\'category\'>\n        <CompactHorizontalBar.Hover />\n        <CompactHorizontalBar.Tooltip>\n          {({ index }) => {\n            return {\n              children: (\n                <>\n                  <CompactHorizontalBar.Tooltip.Title>\n                    {data[index].category}\n                  </CompactHorizontalBar.Tooltip.Title>\n                  <Flex justifyContent=\'space-between\'>\n                    <CompactHorizontalBar.Tooltip.Dot mr={4}>Bar</CompactHorizontalBar.Tooltip.Dot>\n                    <Text bold>{data[index].value}</Text>\n                  </Flex>\n                </>\n              ),\n            };\n          }}\n        </CompactHorizontalBar.Tooltip>\n        <CompactHorizontalBar.Annotation>\n          <CompactHorizontalBar.Label />\n          <CompactHorizontalBar.Percent />\n          <CompactHorizontalBar.Value tag={Link} href=\'https://semrush.com\'>\n            {({ formatted }) => {\n              return (\n                <Link.Text>\n                  ~\n                  {formatted}\n                </Link.Text>\n              );\n            }}\n          </CompactHorizontalBar.Value>\n        </CompactHorizontalBar.Annotation>\n        <CompactHorizontalBar.Bar>\n          <CompactHorizontalBar.Bar.Background />\n          <CompactHorizontalBar.Bar.Fill />\n        </CompactHorizontalBar.Bar>\n      </CompactHorizontalBar>\n    </Plot>\n  );\n};\n\nconst data = BarMockData.WithValue;\n\nexport default Demo;\n' },
};
