import type { Meta, StoryObj } from '@storybook/react-vite';

import BasicUsageExample from './examples/donut-chart/basic-usage';
import DonutExample from './examples/donut-chart/donut';
import DonutControlledHighlightExample from './examples/donut-chart/donut-controlled-highlight';
import EdgeCasesExample from './examples/donut-chart/edge-cases';
import LegendAndPatternFillExample from './examples/donut-chart/legend-and-pattern-fill';
import SemiDonutExample from './examples/donut-chart/semi-donut';
const meta: Meta = {
  title: 'Components/d3Charts/Documentation/Donut-Chart',
};
export default meta;
export const Donut: StoryObj = {
  render: DonutExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { Donut, Plot } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport React from \'react\';\n\nimport DonutMockData from \'../../../__mocks__/donut\';\n\nconst Demo = () => {\n  return (\n    <Plot width={300} height={300} data={data}>\n      <Donut innerRadius={100}>\n        <Donut.Pie dataKey=\'a\' name=\'Pie 1\' />\n        <Donut.Pie dataKey=\'b\' name=\'Pie 2\' />\n        <Donut.Pie dataKey=\'c\' name=\'Pie 3\' />\n        <Donut.Label>\n          <Text tag=\'tspan\' fill=\'#191b23\' size={400}>\n            Example\n          </Text>\n        </Donut.Label>\n      </Donut>\n      <Donut.Tooltip>\n        {({ dataKey, name }) => {\n          return {\n            children: (\n              <>\n                <Donut.Tooltip.Title>{name}</Donut.Tooltip.Title>\n                <Flex justifyContent=\'space-between\'>\n                  {/* @ts-ignore */}\n                  <Text bold>{data[dataKey]}</Text>\n                </Flex>\n              </>\n            ),\n          };\n        }}\n      </Donut.Tooltip>\n    </Plot>\n  );\n};\n\nconst data = DonutMockData.Default;\n\nexport default Demo;\n' },
};
export const BasicUsage: StoryObj = {
  render: BasicUsageExample,
  parameters: { sourceCode: 'import { Chart } from \'@semcore/ui/d3-chart\';\nimport React from \'react\';\n\nimport DonutMockData from \'../../../__mocks__/donut\';\n\nconst Demo = () => {\n  return (\n    <div style={{ width: \'450px\' }}>\n      <Chart.Donut plotWidth={300} plotHeight={300} data={data} aria-label=\'Donut chart\' />\n    </div>\n  );\n};\n\nconst data = DonutMockData.Default;\n\nexport default Demo;\n' },
};
export const DonutControlledHighlight: StoryObj = {
  render: DonutControlledHighlightExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport Checkbox from \'@semcore/ui/checkbox\';\nimport { Donut, Plot } from \'@semcore/ui/d3-chart\';\nimport React from \'react\';\n\nimport DonutMockData from \'../../../__mocks__/donut\';\n\nconst Demo = () => {\n  const [selected, setSelected] = React.useState([\'b\']);\n  const handleCheckboxToggle = React.useCallback(\n    (name: any) => () => {\n      setSelected((selected) => {\n        if (selected.includes(name)) {\n          return selected.filter((selectedName) => selectedName !== name);\n        } else {\n          return [...selected, name];\n        }\n      });\n    },\n    [setSelected],\n  );\n\n  return (\n    <Flex mt={3} alignItems=\'flex-start\' flexWrap>\n      <Plot height={120} width={120} m=\'0 28px 24px 0\' data={data}>\n        <Donut innerRadius={30}>\n          {Object.keys(data).map((name, index) => (\n            <Donut.Pie\n              key={name}\n              dataKey={name}\n              name={`Pie ${index}`}\n              active={selected.includes(name)}\n            />\n          ))}\n        </Donut>\n      </Plot>\n      <Flex direction=\'column\'>\n        {Object.keys(data).map((name, index) => {\n          return (\n            <Checkbox key={name} id={name} theme={`chart-palette-order-${index + 1}`}>\n              <Checkbox.Value\n                value={name}\n                checked={selected.includes(name)}\n                onChange={handleCheckboxToggle(name)}\n              />\n              <Checkbox.Text>{`Option ${name.toUpperCase()}`}</Checkbox.Text>\n            </Checkbox>\n          );\n        })}\n      </Flex>\n    </Flex>\n  );\n};\n\nconst data = DonutMockData.Default;\n\nexport default Demo;\n' },
};
export const EdgeCases: StoryObj = {
  render: EdgeCasesExample,
  parameters: { sourceCode: 'import { Plot, Donut } from \'@semcore/ui/d3-chart\';\nimport React from \'react\';\n\nimport DonutMockData from \'../../../__mocks__/donut\';\n\nconst Demo = () => {\n  return (\n    <Plot width={300} height={300} data={data}>\n      <Donut innerRadius={100}>\n        <Donut.EmptyData />\n        <Donut.Pie dataKey=\'a\' name=\'a\' />\n        <Donut.Pie dataKey=\'b\' name=\'b\' />\n        <Donut.Pie dataKey=\'c\' name=\'c\' />\n      </Donut>\n    </Plot>\n  );\n};\n\nconst data = DonutMockData.EdgeCase;\n\nexport default Demo;\n' },
};
export const SemiDonut: StoryObj = {
  render: SemiDonutExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { Plot, Donut } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport React from \'react\';\n\nimport DonutMockData from \'../../../__mocks__/donut\';\n\nconst Demo = () => {\n  return (\n    <Plot width={300} height={150} data={data}>\n      <Donut halfsize innerRadius={100}>\n        <Donut.Pie dataKey=\'a\' name=\'Pie 1\' />\n        <Donut.Pie dataKey=\'b\' name=\'Pie 2\' />\n        <Donut.Pie dataKey=\'c\' name=\'Pie 3\' />\n        <Donut.Label label=\'71,240 engagements\'>\n          <Text tag=\'tspan\' x=\'0\' dy=\'-1.2em\' fill=\'#191b23\' size={600}>\n            71,240\n          </Text>\n          <Text tag=\'tspan\' x=\'0\' dy=\'1.2em\' fill=\'#6c6e79\' size={200}>\n            Engagements\n          </Text>\n        </Donut.Label>\n      </Donut>\n      <Donut.Tooltip>\n        {({ dataKey, name }) => {\n          return {\n            children: (\n              <>\n                <Donut.Tooltip.Title>{name}</Donut.Tooltip.Title>\n                <Flex justifyContent=\'space-between\'>\n                  {/* @ts-ignore */}\n                  <Text bold>{data[dataKey]}</Text>\n                </Flex>\n              </>\n            ),\n          };\n        }}\n      </Donut.Tooltip>\n    </Plot>\n  );\n};\n\nconst data = DonutMockData.Default;\n\nexport default Demo;\n' },
};
export const LegendAndPatternFill: StoryObj = {
  render: LegendAndPatternFillExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { ChartLegend, Donut, makeDataHintsContainer, Plot } from \'@semcore/ui/d3-chart\';\nimport React from \'react\';\n\nimport DonutMockData from \'../../../__mocks__/donut\';\n\nconst dataHints = makeDataHintsContainer();\n\nconst Demo = () => {\n  const width = 250;\n  const height = 250;\n\n  const [legendItems, setLegendItems] = React.useState(\n    Object.keys(data).map((item, index) => {\n      return {\n        id: item,\n        label: `Category ${index + 1}`,\n        checked: true,\n        color: `chart-palette-order-${index + 1}`,\n      };\n    }),\n  );\n\n  const [highlightedLine, setHighlightedLine] = React.useState(-1);\n\n  const handleChangeVisible = React.useCallback((id: string, isVisible: boolean) => {\n    setLegendItems((prevItems) => {\n      return prevItems.map((item) => {\n        if (item.id === id) {\n          item.checked = isVisible;\n        }\n\n        return item;\n      });\n    });\n  }, []);\n\n  const handleMouseEnter = React.useCallback((id: string) => {\n    setHighlightedLine(legendItems.findIndex((line) => line.id === id));\n  }, []);\n  const handleMouseLeave = React.useCallback(() => {\n    setHighlightedLine(-1);\n  }, []);\n\n  return (\n    <Flex direction=\'row\' gap={5}>\n      <Plot width={width} height={height} data={data} dataHints={dataHints} patterns>\n        <Donut innerRadius={height / 2 - 50}>\n          {legendItems.filter((item) => item.checked).length === 0 && <Donut.EmptyData />}\n          {legendItems.map((item, index) => {\n            return (\n              item.checked && (\n                <Donut.Pie\n                  dataKey={item.id}\n                  key={item.id}\n                  name={item.label}\n                  color={item.color}\n                  transparent={highlightedLine !== -1 && highlightedLine !== index}\n                />\n              )\n            );\n          })}\n        </Donut>\n      </Plot>\n      <ChartLegend\n        direction=\'column\'\n        wMin={100}\n        items={legendItems}\n        onChangeVisibleItem={handleChangeVisible}\n        onMouseEnterItem={handleMouseEnter}\n        onMouseLeaveItem={handleMouseLeave}\n        dataHints={dataHints}\n        patterns\n        aria-label=\'Donut chart legend\'\n      />\n    </Flex>\n  );\n};\n\nconst data = DonutMockData.Default;\n\nexport default Demo;\n' },
};
