import type { Meta, StoryObj } from '@storybook/react-vite';

import BasicUsageExample from './examples/line-chart/basic-usage';
import CurveExample from './examples/line-chart/curve';
import DotsDisplayFunctionExample from './examples/line-chart/dots-display-function';
import HoverLineExample from './examples/line-chart/hover-line';
import InterpolationExample from './examples/line-chart/interpolation';
import LegendAndSymbolsForDotExample from './examples/line-chart/legend-and-symbols-for-dots';
import LineExample from './examples/line-chart/line';
import LineWithAreaExample from './examples/line-chart/line-with-area';
import TimeExample from './examples/line-chart/time';
import TooltipExample from './examples/line-chart/tooltip';
const meta: Meta = {
  title: 'Components/d3Charts/Documentation/Line-Chart',
};
export default meta;
export const Line: StoryObj = {
  render: LineExample,
  parameters: { sourceCode: 'import { Plot, Line, XAxis, YAxis, minMax } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport LineMockData from \'../../../__mocks__/line\';\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'x\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([0, 10]);\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks />\n      </XAxis>\n      <Line x=\'x\' y=\'y\'>\n        <Line.Dots display />\n      </Line>\n    </Plot>\n  );\n};\n\nconst data = LineMockData.Default;\n\nexport default Demo;\n' },
};
export const BasicUsage: StoryObj = {
  render: BasicUsageExample,
  parameters: { sourceCode: 'import { Chart } from \'@semcore/ui/d3-chart\';\nimport React from \'react\';\n\nimport LineMockData from \'../../../__mocks__/line\';\n\nconst Demo = () => {\n  return (\n    <Chart.Line\n      data={data}\n      plotWidth={500}\n      plotHeight={200}\n      groupKey=\'x\'\n      xTicksCount={data.length / 2}\n      aria-label=\'Line chart\'\n    />\n  );\n};\n\nconst data = LineMockData.TwoLines;\n\nexport default Demo;\n' },
};
export const Curve: StoryObj = {
  render: CurveExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { Plot, Line, XAxis, YAxis, HoverLine, minMax } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport { scaleLinear } from \'d3-scale\';\nimport { curveCardinal } from \'d3-shape\';\nimport React from \'react\';\n\nimport LineMockData from \'../../../__mocks__/line\';\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'x\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([0, 10]);\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks />\n      </XAxis>\n      <HoverLine.Tooltip x=\'x\' wMin={100}>\n        {({ xIndex }) => {\n          return {\n            children: (\n              <>\n                <HoverLine.Tooltip.Title>{data[xIndex].x}</HoverLine.Tooltip.Title>\n                <Flex justifyContent=\'space-between\'>\n                  <HoverLine.Tooltip.Dot mr={4}>Line</HoverLine.Tooltip.Dot>\n                  <Text bold>{data[xIndex].y}</Text>\n                </Flex>\n              </>\n            ),\n          };\n        }}\n      </HoverLine.Tooltip>\n      <Line x=\'x\' y=\'y\' curve={curveCardinal}>\n        <Line.Dots />\n      </Line>\n    </Plot>\n  );\n};\n\nconst data = LineMockData.Default;\n\nexport default Demo;\n' },
};
export const DotsDisplayFunction: StoryObj = {
  render: DotsDisplayFunctionExample,
  parameters: { sourceCode: 'import { Plot, Line, XAxis, YAxis, minMax } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport { curveCardinal } from \'d3-shape\';\nimport React from \'react\';\n\nimport LineMockData from \'../../../__mocks__/line\';\n\nconst displayDots = (index: number, active: boolean, single: boolean) => {\n  if (single || active) return true;\n  return index < 10;\n};\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'x\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([0, 10]);\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks />\n      </XAxis>\n      <Line x=\'x\' y=\'y\' curve={curveCardinal}>\n        <Line.Dots display={displayDots} />\n      </Line>\n    </Plot>\n  );\n};\n\nconst data = LineMockData.Default;\n\nexport default Demo;\n' },
};
export const HoverLine: StoryObj = {
  render: HoverLineExample,
  parameters: { sourceCode: 'import { Plot, XAxis, YAxis, HoverLine, minMax } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport LineMockData from \'../../../__mocks__/line\';\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'x\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain(minMax(data, \'y\'));\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <YAxis>\n        <YAxis.Ticks />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks />\n      </XAxis>\n      <HoverLine x=\'x\' y=\'y\' />\n    </Plot>\n  );\n};\n\nconst data = LineMockData.Hover;\n\nexport default Demo;\n' },
};
export const Interpolation: StoryObj = {
  render: InterpolationExample,
  parameters: { sourceCode: 'import { Plot, Line, XAxis, YAxis, minMax } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport LineMockData from \'../../../__mocks__/line\';\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'x\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([0, 10]);\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks />\n      </XAxis>\n      <Line x=\'x\' y=\'line1\'>\n        <Line.Dots display />\n      </Line>\n      <Line x=\'x\' y=\'line2\'>\n        <Line.Dots display />\n      </Line>\n    </Plot>\n  );\n};\n\nconst data = LineMockData.Interpolation;\n\nexport default Demo;\n' },
};
export const LegendAndSymbolsForDot: StoryObj = {
  render: LegendAndSymbolsForDotExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport {\n  Line,\n  minMax,\n  Plot,\n  XAxis,\n  YAxis,\n  ChartLegend,\n  makeDataHintsContainer,\n} from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport LineMockData from \'../../../__mocks__/line\';\n\nconst dataHints = makeDataHintsContainer();\n\nconst Demo = () => {\n  const MARGIN = 30;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'x\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([0, 10]);\n\n  const [legendItems, setLegendItems] = React.useState(\n    Object.keys(data[0])\n      .filter((name) => name !== \'x\')\n      .map((item, index) => {\n        return {\n          id: item,\n          label: `Line ${index + 1}`,\n          checked: true,\n          color: `chart-palette-order-${index + 1}`,\n        };\n      }),\n  );\n\n  const [highlightedLine, setHighlightedLine] = React.useState(-1);\n\n  const handleChangeVisible = React.useCallback((id: string, isVisible: boolean) => {\n    setLegendItems((prevItems) => {\n      return prevItems.map((item) => {\n        if (item.id === id) {\n          item.checked = isVisible;\n        }\n\n        return item;\n      });\n    });\n  }, []);\n\n  const handleMouseEnter = React.useCallback((id: string) => {\n    setHighlightedLine(legendItems.findIndex((line) => line.id === id));\n  }, []);\n  const handleMouseLeave = React.useCallback(() => {\n    setHighlightedLine(-1);\n  }, []);\n\n  return (\n    <Flex direction=\'column\'>\n      <ChartLegend\n        dataHints={dataHints}\n        items={legendItems}\n        onChangeVisibleItem={handleChangeVisible}\n        onMouseEnterItem={handleMouseEnter}\n        onMouseLeaveItem={handleMouseLeave}\n        patterns\n        aria-label=\'Patterned chart legend\'\n      />\n      <Plot\n        data={data}\n        scale={[xScale, yScale]}\n        width={width}\n        height={height}\n        dataHints={dataHints}\n        patterns\n      >\n        <YAxis>\n          <YAxis.Ticks ticks={yScale.ticks(4)} />\n          <YAxis.Grid ticks={yScale.ticks(4)} />\n        </YAxis>\n        <XAxis>\n          <XAxis.Ticks ticks={xScale.ticks(5)} />\n        </XAxis>\n        {legendItems.map((item, index) => {\n          return (\n            item.checked && (\n              <Line\n                x=\'x\'\n                y={item.id}\n                key={item.id}\n                color={item.color}\n                transparent={highlightedLine !== -1 && highlightedLine !== index}\n              >\n                <Line.Dots display />\n              </Line>\n            )\n          );\n        })}\n      </Plot>\n    </Flex>\n  );\n};\n\nconst data = LineMockData.ThreeLines;\n\nexport default Demo;\n' },
};
export const LineWithArea: StoryObj = {
  render: LineWithAreaExample,
  parameters: { sourceCode: 'import { Plot, Line, XAxis, YAxis, minMax } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport LineMockData from \'../../../__mocks__/line\';\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'x\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([0, 10]);\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks />\n      </XAxis>\n      <Line x=\'x\' y=\'y\'>\n        <Line.Area y0=\'y0\' y1=\'y1\' />\n      </Line>\n    </Plot>\n  );\n};\n\nconst data = LineMockData.Area;\n\nexport default Demo;\n' },
};
export const Time: StoryObj = {
  render: TimeExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { Plot, Line, XAxis, YAxis, HoverLine, minMax } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport { scaleLinear, scaleTime } from \'d3-scale\';\nimport React from \'react\';\n\nimport LineMockData from \'../../../__mocks__/line\';\n\nfunction formatDate(value: any, options: any) {\n  return new Intl.DateTimeFormat(\'en\', options).format(value);\n}\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleTime()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'time\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([0, 10]);\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks>\n          {({ value }) => ({\n            children: formatDate(value, {\n              month: \'short\',\n              day: \'numeric\',\n            }),\n          })}\n        </XAxis.Ticks>\n      </XAxis>\n      <HoverLine.Tooltip x=\'time\' wMin={100}>\n        {({ xIndex }) => {\n          return {\n            children: (\n              <>\n                <HoverLine.Tooltip.Title>\n                  {formatDate(data[xIndex].time, {\n                    year: \'numeric\',\n                    month: \'long\',\n                    day: \'numeric\',\n                  })}\n                </HoverLine.Tooltip.Title>\n                <Flex justifyContent=\'space-between\'>\n                  <HoverLine.Tooltip.Dot mr={4}>Line</HoverLine.Tooltip.Dot>\n                  <Text bold>{data[xIndex].line}</Text>\n                </Flex>\n              </>\n            ),\n          };\n        }}\n      </HoverLine.Tooltip>\n      <Line x=\'time\' y=\'line\'>\n        <Line.Dots display />\n      </Line>\n    </Plot>\n  );\n};\n\nconst data = LineMockData.Time;\n\nexport default Demo;\n' },
};
export const Tooltip: StoryObj = {
  render: TooltipExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { Plot, Line, XAxis, YAxis, HoverLine, minMax } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport LineMockData from \'../../../__mocks__/line\';\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain(minMax(data, \'x\'));\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([0, 10]);\n\n  return (\n    <Plot data={data} scale={[xScale, yScale]} width={width} height={height}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks />\n      </XAxis>\n      <HoverLine.Tooltip x=\'x\' wMin={100}>\n        {({ xIndex }) => {\n          return {\n            children: (\n              <>\n                <HoverLine.Tooltip.Title>{data[xIndex].x}</HoverLine.Tooltip.Title>\n                <Flex justifyContent=\'space-between\'>\n                  <HoverLine.Tooltip.Dot mr={4}>Line</HoverLine.Tooltip.Dot>\n                  <Text bold>{data[xIndex].y}</Text>\n                </Flex>\n              </>\n            ),\n          };\n        }}\n      </HoverLine.Tooltip>\n      <Line x=\'x\' y=\'y\'>\n        <Line.Dots />\n      </Line>\n    </Plot>\n  );\n};\n\nconst data = LineMockData.Default;\n\nexport default Demo;\n' },
};
