import type { Meta, StoryObj } from '@storybook/react-vite';

import BackgroundColorExample from './examples/radar-chart/background-color';
import BasicUsageExample from './examples/radar-chart/basic-usage';
import CircleExample from './examples/radar-chart/circle';
import ColorExample from './examples/radar-chart/color';
import LabelCustomExample from './examples/radar-chart/label-custom';
import LabelLongExample from './examples/radar-chart/label-long';
import LegendAndPatternFillExample from './examples/radar-chart/legend-and-pattern-fill';
import RotatedExample from './examples/radar-chart/rotated';
import ScaleExample from './examples/radar-chart/scale';
import TickSizeExample from './examples/radar-chart/tick-size';
import TooltipExample from './examples/radar-chart/tooltip';
const meta: Meta = {
  title: 'Components/d3Charts/Documentation/Radar-Chart',
};
export default meta;
export const BackgroundColor: StoryObj = {
  render: BackgroundColorExample,
  parameters: { sourceCode: 'import { Plot, Radar, colors } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport RadarMockData from \'../../../__mocks__/radar\';\n\nconst Demo = () => {\n  const width = 500;\n  const height = 500;\n\n  const scale = scaleLinear().domain([0, 10]);\n\n  return (\n    <Plot data={data} width={width} height={height}>\n      <Radar scale={scale}>\n        <Radar.Axis dataKey=\'categories\'>\n          <Radar.Axis.Ticks />\n          <Radar.Axis.Labels />\n        </Radar.Axis>\n        <Radar.Polygon dataKey=\'data_1\' color=\'chart-palette-order-1\' fill=\'transparent\'>\n          <Radar.Polygon.Line />\n          <Radar.Polygon.Dots />\n        </Radar.Polygon>\n        <Radar.Polygon dataKey=\'data_2\' color=\'chart-palette-order-2\' fill=\'transparent\'>\n          <Radar.Polygon.Line />\n          <Radar.Polygon.Dots />\n        </Radar.Polygon>\n      </Radar>\n    </Plot>\n  );\n};\n\nconst data = RadarMockData.Default;\n\nexport default Demo;\n' },
};
export const BasicUsage: StoryObj = {
  render: BasicUsageExample,
  parameters: { sourceCode: 'import { Chart, colors } from \'@semcore/ui/d3-chart\';\nimport React from \'react\';\n\nimport RadarMockData from \'../../../__mocks__/radar\';\n\nconst Demo = () => {\n  return (\n    <Chart.Radar\n      data={data}\n      groupKey=\'categories\'\n      plotWidth={400}\n      plotHeight={400}\n      aria-label=\'Radar chart\'\n    />\n  );\n};\n\nconst data = RadarMockData.Default;\n\nexport default Demo;\n' },
};
export const Circle: StoryObj = {
  render: CircleExample,
  parameters: { sourceCode: 'import { Plot, Radar } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport { curveCardinalClosed } from \'d3-shape\';\nimport React from \'react\';\n\nimport RadarMockData from \'../../../__mocks__/radar\';\n\nconst Demo = () => {\n  const width = 500;\n  const height = 500;\n\n  const scale = scaleLinear().domain([0, 10]);\n\n  return (\n    <Plot data={data} width={width} height={height}>\n      <Radar scale={scale} type=\'circle\'>\n        <Radar.Axis dataKey=\'categories\'>\n          <Radar.Axis.Ticks />\n          <Radar.Axis.Labels />\n        </Radar.Axis>\n        <Radar.Tooltip wMin={100}>\n          {({ index }) => {\n            return {\n              children: (\n                <>\n                  <Radar.Tooltip.Title>{data.categories[index]}</Radar.Tooltip.Title>\n                  <Radar.Tooltip.Dot>{data[\'data_1\'][index]}</Radar.Tooltip.Dot>\n                  <Radar.Tooltip.Dot>{data[\'data_2\'][index]}</Radar.Tooltip.Dot>\n                </>\n              ),\n            };\n          }}\n        </Radar.Tooltip>\n        <Radar.Polygon dataKey=\'data_1\' curve={curveCardinalClosed}>\n          <Radar.Polygon.Line />\n          <Radar.Polygon.Dots />\n        </Radar.Polygon>\n        <Radar.Polygon dataKey=\'data_2\' curve={curveCardinalClosed}>\n          <Radar.Polygon.Line />\n          <Radar.Polygon.Dots />\n        </Radar.Polygon>\n      </Radar>\n    </Plot>\n  );\n};\n\nconst data = RadarMockData.Default;\n\nexport default Demo;\n' },
};
export const Color: StoryObj = {
  render: ColorExample,
  parameters: { sourceCode: 'import { Plot, Radar } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport RadarMockData from \'../../../__mocks__/radar\';\n\nconst Demo = () => {\n  const width = 500;\n  const height = 500;\n\n  const scale = scaleLinear().domain([0, 10]);\n\n  return (\n    <Plot data={data} width={width} height={height}>\n      <Radar scale={scale}>\n        <Radar.Axis dataKey=\'categories\'>\n          <Radar.Axis.Ticks />\n          <Radar.Axis.Labels />\n        </Radar.Axis>\n        <Radar.Polygon dataKey=\'data_1\' color=\'chart-palette-order-1\'>\n          <Radar.Polygon.Line />\n          <Radar.Polygon.Dots />\n        </Radar.Polygon>\n        <Radar.Polygon dataKey=\'data_2\' color=\'chart-palette-order-2\'>\n          <Radar.Polygon.Line />\n          <Radar.Polygon.Dots />\n        </Radar.Polygon>\n      </Radar>\n    </Plot>\n  );\n};\n\nconst data = RadarMockData.Default;\n\nexport default Demo;\n' },
};
export const LabelCustom: StoryObj = {
  render: LabelCustomExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { Plot, Radar, getLabelOffsetPosition } from \'@semcore/ui/d3-chart\';\nimport Tag from \'@semcore/ui/tag\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport RadarMockData from \'../../../__mocks__/radar\';\n\nconst Demo = () => {\n  const width = 250;\n  const height = 250;\n\n  const scale = scaleLinear().domain([0, 10]);\n  const maxLabelWidth = 50;\n\n  return (\n    <Flex>\n      <Plot data={data} width={width} height={height}>\n        <Radar scale={scale} offset={maxLabelWidth}>\n          <Radar.Axis dataKey=\'categories\'>\n            <Radar.Axis.Ticks />\n            <Radar.Axis.Labels>\n              {(props) => {\n                const width = maxLabelWidth;\n                const height = 20;\n                const [xOffset, yOffset] = getLabelOffsetPosition(\n                  props.xDirection,\n                  props.yDirection,\n                  width,\n                  height,\n                );\n                return {\n                  tag: \'g\',\n                  children: (\n                    <foreignObject\n                      x={props.x - xOffset}\n                      y={props.y - yOffset}\n                      width={width}\n                      height={height}\n                    >\n                      <Tag>{props.children}</Tag>\n                    </foreignObject>\n                  ),\n                };\n              }}\n            </Radar.Axis.Labels>\n          </Radar.Axis>\n          <Radar.Polygon dataKey=\'data_1\'>\n            <Radar.Polygon.Line />\n            <Radar.Polygon.Dots />\n          </Radar.Polygon>\n        </Radar>\n      </Plot>\n    </Flex>\n  );\n};\n\nconst data = RadarMockData.SingleData;\n\nexport default Demo;\n' },
};
export const LabelLong: StoryObj = {
  render: LabelLongExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { Plot, Radar } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport RadarMockData from \'../../../__mocks__/radar\';\n\nconst Demo = () => {\n  const width = 250;\n  const height = 250;\n\n  const scale = scaleLinear().domain([0, 10]);\n\n  return (\n    <Flex>\n      <Plot data={data} width={width} height={height}>\n        <Radar scale={scale}>\n          <Radar.Axis dataKey=\'categories\'>\n            <Radar.Axis.Ticks />\n            <Radar.Axis.Labels />\n          </Radar.Axis>\n          <Radar.Polygon dataKey=\'data_1\'>\n            <Radar.Polygon.Line />\n            <Radar.Polygon.Dots />\n          </Radar.Polygon>\n        </Radar>\n      </Plot>\n    </Flex>\n  );\n};\n\nconst data = RadarMockData.LongLabel;\n\nexport default Demo;\n' },
};
export const LegendAndPatternFill: StoryObj = {
  render: LegendAndPatternFillExample,
  parameters: { sourceCode: 'import { Plot, Radar, ChartLegend } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport RadarMockData from \'../../../__mocks__/radar\';\n\ntype DataKey = keyof typeof data;\n\nconst getDefaultLegendItems = () => {\n  return (Object.keys(data) as DataKey[])\n    .filter((name) => name !== \'categories\')\n    .map((item, index) => {\n      return {\n        id: item,\n        label: `Category ${index + 1}`,\n        data: data[item],\n        checked: true,\n        color: lineColors[item],\n      };\n    });\n};\n\nconst Demo = () => {\n  const [legendItems, setLegendItems] = React.useState(getDefaultLegendItems);\n\n  const handleChangeVisible = React.useCallback((id: string, isVisible: boolean) => {\n    setLegendItems((prevItems) =>\n      prevItems.map((item) =>\n        item.id === id ? { ...item, checked: isVisible } : item,\n      ),\n    );\n  }, []);\n\n  const width = 500;\n  const height = 500;\n\n  const scale = scaleLinear().domain([0, 10]);\n\n  return (\n    <>\n      <ChartLegend\n        items={legendItems}\n        patterns\n        aria-label=\'Radar chart legend\'\n        onChangeVisibleItem={handleChangeVisible}\n      />\n      <Plot data={data} width={width} height={height} patterns>\n        <Radar scale={scale}>\n          <Radar.Axis dataKey=\'categories\'>\n            <Radar.Axis.Ticks />\n            <Radar.Axis.Labels />\n          </Radar.Axis>\n\n          {legendItems.map(\n            (item) =>\n              item.checked && (\n                <Radar.Polygon key={item.id} dataKey={item.id} color={item.color}>\n                  <Radar.Polygon.Line />\n                  <Radar.Polygon.Dots />\n                </Radar.Polygon>\n              ),\n          )}\n        </Radar>\n      </Plot>\n    </>\n  );\n};\n\nconst data = RadarMockData.Default;\n\nconst lineColors: Record<keyof typeof data, string> = {\n  categories: \'\',\n  data_1: \'--intergalactic-chart-palette-order-3\',\n  data_2: \'--intergalactic-chart-palette-order-6\',\n};\n\nexport default Demo;\n' },
};
export const Rotated: StoryObj = {
  render: RotatedExample,
  parameters: { sourceCode: 'import { Plot, Radar } from \'@semcore/ui/d3-chart\';\nimport Slider from \'@semcore/ui/slider\';\nimport { scaleLinear } from \'d3-scale\';\nimport { curveCardinalClosed } from \'d3-shape\';\nimport React from \'react\';\n\nimport RadarMockData from \'../../../__mocks__/radar\';\n\nconst scale = scaleLinear().domain([0, 10]);\nconst Demo = () => {\n  const width = 500;\n  const height = 500;\n  const [angleDegOffset, setAngleDegOffset] = React.useState(45);\n\n  const angleOffset = React.useMemo(() => (angleDegOffset / 180) * Math.PI, [angleDegOffset]);\n\n  return (\n    <div>\n      <Slider\n        value={angleDegOffset}\n        onChange={setAngleDegOffset}\n        step={1}\n        min={-360}\n        max={360}\n        w={360}\n        id=\'angle-slider\'\n      />\n      <div>\n        <label htmlFor=\'angle-slider\'>Angle:</label>\n        {\' \'}\n        {angleOffset.toFixed(2)}\n        {\' \'}\n        rad (\n        {angleDegOffset.toFixed(0)}\n        {\' \'}\n        deg)\n      </div>\n      <Plot data={data} width={width} height={height}>\n        <Radar scale={scale} type=\'circle\' angleOffset={angleOffset}>\n          <Radar.Axis dataKey=\'categories\'>\n            <Radar.Axis.Ticks />\n            <Radar.Axis.Labels />\n          </Radar.Axis>\n          <Radar.Tooltip wMin={100}>\n            {({ index }) => {\n              return {\n                children: (\n                  <>\n                    <Radar.Tooltip.Title>{data.categories[index]}</Radar.Tooltip.Title>\n                    <Radar.Tooltip.Dot>{data[\'data_1\'][index]}</Radar.Tooltip.Dot>\n                    <Radar.Tooltip.Dot>{data[\'data_2\'][index]}</Radar.Tooltip.Dot>\n                  </>\n                ),\n              };\n            }}\n          </Radar.Tooltip>\n          <Radar.Polygon dataKey=\'data_1\' curve={curveCardinalClosed}>\n            <Radar.Polygon.Line />\n            <Radar.Polygon.Dots />\n          </Radar.Polygon>\n          <Radar.Polygon dataKey=\'data_2\' curve={curveCardinalClosed}>\n            <Radar.Polygon.Line />\n            <Radar.Polygon.Dots />\n          </Radar.Polygon>\n        </Radar>\n      </Plot>\n    </div>\n  );\n};\n\nconst data = RadarMockData.Default;\n\nexport default Demo;\n' },
};
export const Scale: StoryObj = {
  render: ScaleExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport { Plot, Radar } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport RadarMockData from \'../../../__mocks__/radar\';\n\nconst Demo = () => {\n  const width = 250;\n  const height = 250;\n\n  const scale_1 = scaleLinear().domain([0, 10]);\n  const scale_2 = scaleLinear().domain([0, 20]);\n\n  return (\n    <Flex>\n      <Plot data={data} width={width} height={height}>\n        <Radar scale={scale_1}>\n          <Radar.Axis dataKey=\'categories\'>\n            <Radar.Axis.Ticks />\n            <Radar.Axis.Labels />\n          </Radar.Axis>\n          <Radar.Polygon dataKey=\'data_1\'>\n            <Radar.Polygon.Line />\n            <Radar.Polygon.Dots />\n          </Radar.Polygon>\n        </Radar>\n      </Plot>\n      <Plot data={data} width={width} height={height}>\n        <Radar scale={scale_2}>\n          <Radar.Axis dataKey=\'categories\'>\n            <Radar.Axis.Ticks />\n            <Radar.Axis.Labels />\n          </Radar.Axis>\n          <Radar.Polygon dataKey=\'data_1\'>\n            <Radar.Polygon.Line />\n            <Radar.Polygon.Dots />\n          </Radar.Polygon>\n        </Radar>\n      </Plot>\n    </Flex>\n  );\n};\n\nconst data = RadarMockData.SingleData;\n\nexport default Demo;\n' },
};
export const Tooltip: StoryObj = {
  render: TooltipExample,
  parameters: { sourceCode: 'import { Plot, Radar } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport RadarMockData from \'../../../__mocks__/radar\';\n\nconst Demo = () => {\n  const width = 500;\n  const height = 500;\n\n  const scale = scaleLinear().domain([0, 10]);\n\n  return (\n    <Plot data={data} width={width} height={height}>\n      <Radar scale={scale}>\n        <Radar.Axis dataKey=\'categories\'>\n          <Radar.Axis.Ticks />\n          <Radar.Axis.Labels />\n        </Radar.Axis>\n        <Radar.Tooltip wMin={100}>\n          {({ index }) => {\n            return {\n              children: (\n                <>\n                  <Radar.Tooltip.Title>{data.categories[index]}</Radar.Tooltip.Title>\n                  <Radar.Tooltip.Dot>{data[\'data_1\'][index]}</Radar.Tooltip.Dot>\n                  <Radar.Tooltip.Dot>{data[\'data_2\'][index]}</Radar.Tooltip.Dot>\n                </>\n              ),\n            };\n          }}\n        </Radar.Tooltip>\n        <Radar.Polygon dataKey=\'data_1\'>\n          <Radar.Polygon.Line />\n          <Radar.Polygon.Dots />\n        </Radar.Polygon>\n        <Radar.Polygon dataKey=\'data_2\'>\n          <Radar.Polygon.Line />\n          <Radar.Polygon.Dots />\n        </Radar.Polygon>\n      </Radar>\n    </Plot>\n  );\n};\n\nconst data = RadarMockData.Default;\n\nexport default Demo;\n' },
};
export const TickSize: StoryObj = {
  render: TickSizeExample,
  parameters: { sourceCode: 'import { Plot, Radar } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport RadarMockData from \'../../../__mocks__/radar\';\n\nconst Demo = () => {\n  const width = 500;\n  const height = 500;\n\n  const scale = scaleLinear().domain([0, 10]);\n\n  return (\n    <Plot data={data} width={width} height={height}>\n      <Radar scale={scale}>\n        <Radar.Axis dataKey=\'categories\'>\n          <Radar.Axis.Ticks tickSize={30} />\n          <Radar.Axis.Labels />\n        </Radar.Axis>\n        <Radar.Polygon dataKey=\'data_1\'>\n          <Radar.Polygon.Line />\n          <Radar.Polygon.Dots />\n        </Radar.Polygon>\n        <Radar.Polygon dataKey=\'data_2\'>\n          <Radar.Polygon.Line />\n          <Radar.Polygon.Dots />\n        </Radar.Polygon>\n      </Radar>\n    </Plot>\n  );\n};\n\nconst data = RadarMockData.Default;\n\nexport default Demo;\n' },
};
