import type { Meta, StoryObj } from '@storybook/react-vite';

import BasicUsageExample from './examples/scatterplot-chart/basic-usage';
import ColorCustomizationExample from './examples/scatterplot-chart/color-customization';
import ColorCustomizationAndValuesInsideExample from './examples/scatterplot-chart/color-customization-and-values-inside';
import InitialDataLoadingExample from './examples/scatterplot-chart/initial-data-loading';
import LegendAndPatternFillExample from './examples/scatterplot-chart/legend-and-pattern-fill';
import ScatterPlotExample from './examples/scatterplot-chart/scatter-plot';
import ScatterPlotWithValuesInsideExample from './examples/scatterplot-chart/scatter-plot-with-values-inside';
const meta: Meta = {
  title: 'Components/d3Charts/Documentation/Scatterplot-Chart',
};
export default meta;
export const ColorCustomization: StoryObj = {
  render: ColorCustomizationExample,
  parameters: { sourceCode: 'import { Plot, ScatterPlot, XAxis, YAxis, minMax } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport ScatterplotMockData from \'../../../__mocks__/scatterplot\';\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain([-1, 21]);\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([-1, 11]);\n\n  return (\n    <Plot scale={[xScale, yScale]} width={width} height={height} data={data}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks />\n      </XAxis>\n      <ScatterPlot x=\'x\' y=\'y1\' color=\'#2BB3FF\' />\n      <ScatterPlot x=\'x\' y=\'y2\' color=\'#59DDAA\' />\n      <ScatterPlot.Tooltip>\n        {({ index, x, y, color }) => {\n          return {\n            children: (\n              <>\n                <ScatterPlot.Tooltip.Dot color={color}>Data</ScatterPlot.Tooltip.Dot>\n                <Text tag=\'div\'>\n                  X axis\n                  {/* @ts-ignore */}\n                  {data[index][x]}\n                </Text>\n                <Text tag=\'div\'>\n                  Y axis\n                  {/* @ts-ignore */}\n                  {data[index][y]}\n                </Text>\n              </>\n            ),\n          };\n        }}\n      </ScatterPlot.Tooltip>\n    </Plot>\n  );\n};\n\nconst data = ScatterplotMockData.TwoSetsWithValue;\n\nexport default Demo;\n' },
};
export const BasicUsage: StoryObj = {
  render: BasicUsageExample,
  parameters: { sourceCode: 'import { Chart } from \'@semcore/ui/d3-chart\';\nimport React from \'react\';\n\nimport ScatterplotMockData from \'../../../__mocks__/scatterplot\';\n\nconst Demo = () => {\n  return (\n    <Chart.ScatterPlot\n      data={data}\n      plotWidth={500}\n      plotHeight={300}\n      groupKey=\'x\'\n      aria-label=\'ScatterPlot chart\'\n    />\n  );\n};\n\nconst data = ScatterplotMockData.Default;\n\nexport default Demo;\n' },
};
export const ColorCustomizationAndValuesInside: StoryObj = {
  render: ColorCustomizationAndValuesInsideExample,
  parameters: { sourceCode: 'import { Plot, ScatterPlot, XAxis, YAxis } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport ScatterplotMockData from \'../../../__mocks__/scatterplot\';\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain([-1, 21]);\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([-1, 11]);\n\n  return (\n    <Plot scale={[xScale, yScale]} width={width} height={height} data={data}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks />\n      </XAxis>\n      <ScatterPlot x=\'x\' y=\'y1\' value=\'value\' color=\'#2BB3FF\' valueColor=\'#008ff8\' />\n      <ScatterPlot x=\'x\' y=\'y2\' value=\'value\' color=\'#59DDAA\' valueColor=\'#00C192\' />\n      <ScatterPlot.Tooltip>\n        {({ index, x, y, value }) => {\n          return {\n            children: (\n              <>\n                <ScatterPlot.Tooltip.Title>Data</ScatterPlot.Tooltip.Title>\n                <Text tag=\'div\'>\n                  X axis\n                  {/* @ts-ignore */}\n                  {data[index][x]}\n                </Text>\n                <Text tag=\'div\'>\n                  Y axis\n                  {/* @ts-ignore */}\n                  {data[index][y]}\n                </Text>\n                <Text tag=\'div\'>\n                  Value\n                  {/* @ts-ignore */}\n                  {data[index][value]}\n                </Text>\n              </>\n            ),\n          };\n        }}\n      </ScatterPlot.Tooltip>\n    </Plot>\n  );\n};\n\nconst data = ScatterplotMockData.TwoSetsWithValue;\n\nexport default Demo;\n' },
};
export const InitialDataLoading: StoryObj = {
  render: InitialDataLoadingExample,
  parameters: { sourceCode: 'import { ScatterPlotChartSkeleton } from \'@semcore/ui/skeleton\';\nimport React from \'react\';\n\nconst Demo = () => (\n  <React.Fragment>\n    <ScatterPlotChartSkeleton />\n  </React.Fragment>\n);\n\nexport default Demo;\n' },
};
export const LegendAndPatternFill: StoryObj = {
  render: LegendAndPatternFillExample,
  parameters: { sourceCode: 'import { Plot, ScatterPlot, XAxis, YAxis, minMax, ChartLegend } from \'@semcore/ui/d3-chart\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport ScatterplotMockData from \'../../../__mocks__/scatterplot\';\n\nconst getDegaultLegendItems = () => {\n  return Object.keys(data[0])\n    .filter((name) => name !== \'x\' && name !== \'value\')\n    .map((item, index) => {\n      return {\n        id: item,\n        label: `Dataset ${index + 1}`,\n        checked: true,\n        color: `chart-palette-order-${index + 1}`,\n      };\n    });\n};\n\nconst Demo = () => {\n  const [legendItems, setLegendItems] = React.useState(getDegaultLegendItems);\n\n  const handleChangeVisible = React.useCallback((id: string, isVisible: boolean) => {\n    setLegendItems((prevItems) => {\n      const newItems = prevItems.map((item) => {\n        if (item.id === id) {\n          item.checked = isVisible;\n        }\n\n        return item;\n      });\n\n      return newItems;\n    });\n  }, []);\n\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain([-1, 11]);\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([-1, 11]);\n\n  return (\n    <>\n      <ChartLegend\n        items={legendItems}\n        shape=\'Checkbox\'\n        patterns\n        onChangeVisibleItem={handleChangeVisible}\n        aria-label=\'Scatterplot legend\'\n      />\n      <Plot scale={[xScale, yScale]} width={width} height={height} data={data} patterns={true}>\n        <YAxis>\n          <YAxis.Ticks />\n          <YAxis.Grid />\n        </YAxis>\n        <XAxis>\n          <XAxis.Ticks />\n        </XAxis>\n        {legendItems\n          .filter((item) => item.checked)\n          .map((item) => {\n            return (\n              <ScatterPlot key={item.id} x=\'x\' y={item.id} value=\'value\' color={item.color} />\n            );\n          })}\n      </Plot>\n    </>\n  );\n};\n\nconst data = ScatterplotMockData.ThreeSetsWithValue;\n\nexport default Demo;\n' },
};
export const ScatterPlot: StoryObj = {
  render: ScatterPlotExample,
  parameters: { sourceCode: 'import { Plot, ScatterPlot, XAxis, YAxis, minMax } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport ScatterplotMockData from \'../../../__mocks__/scatterplot\';\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain([-1, 21]);\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([-1, 11]);\n\n  return (\n    <Plot scale={[xScale, yScale]} width={width} height={height} data={data}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks />\n      </XAxis>\n      <ScatterPlot x=\'x\' y=\'y\' />\n      <ScatterPlot.Tooltip>\n        {({ index }) => {\n          return {\n            children: (\n              <>\n                <ScatterPlot.Tooltip.Title>Data</ScatterPlot.Tooltip.Title>\n                <Text tag=\'div\'>\n                  X axis\n                  {data[index].x}\n                </Text>\n                <Text tag=\'div\'>\n                  Y axis\n                  {data[index].y}\n                </Text>\n              </>\n            ),\n          };\n        }}\n      </ScatterPlot.Tooltip>\n    </Plot>\n  );\n};\n\nconst data = ScatterplotMockData.Default;\n\nexport default Demo;\n' },
};
export const ScatterPlotWithValuesInside: StoryObj = {
  render: ScatterPlotWithValuesInsideExample,
  parameters: { sourceCode: 'import { Plot, ScatterPlot, XAxis, YAxis, minMax } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport { scaleLinear } from \'d3-scale\';\nimport React from \'react\';\n\nimport ScatterplotMockData from \'../../../__mocks__/scatterplot\';\n\nconst Demo = () => {\n  const MARGIN = 40;\n  const width = 500;\n  const height = 300;\n\n  const xScale = scaleLinear()\n    .range([MARGIN, width - MARGIN])\n    .domain([-1, 21]);\n\n  const yScale = scaleLinear()\n    .range([height - MARGIN, MARGIN])\n    .domain([-1, 11]);\n\n  return (\n    <Plot scale={[xScale, yScale]} width={width} height={height} data={data}>\n      <YAxis>\n        <YAxis.Ticks />\n        <YAxis.Grid />\n      </YAxis>\n      <XAxis>\n        <XAxis.Ticks />\n      </XAxis>\n      <ScatterPlot x=\'x\' y=\'y\' value=\'value\' />\n      <ScatterPlot.Tooltip>\n        {({ index, x, y, value }) => {\n          return {\n            children: (\n              <>\n                <ScatterPlot.Tooltip.Title>Data</ScatterPlot.Tooltip.Title>\n                <Text tag=\'div\'>\n                  X axis\n                  {/* @ts-ignore */}\n                  {data[index][x]}\n                </Text>\n                <Text tag=\'div\'>\n                  Y axis\n                  {/* @ts-ignore */}\n                  {data[index][y]}\n                </Text>\n                <Text tag=\'div\'>\n                  Value\n                  {/* @ts-ignore */}\n                  {data[index][value]}\n                </Text>\n              </>\n            ),\n          };\n        }}\n      </ScatterPlot.Tooltip>\n    </Plot>\n  );\n};\n\nconst data = ScatterplotMockData.DefaultWithValue;\n\nexport default Demo;\n' },
};
