import type { Meta, StoryObj } from '@storybook/react-vite';

import BasicUsageExample from './examples/venn-chart/basic-usage';
import CustomIntersectionsStylesExample from './examples/venn-chart/custom-intersection-styles';
import LegendAndPatternFillExample from './examples/venn-chart/legend-and-pattern-fill';
import SettingOrientationExample from './examples/venn-chart/setting-orientation';
import VennExample from './examples/venn-chart/venn';
const meta: Meta = {
  title: 'Components/d3Charts/Documentation/Venn-Chart',
};
export default meta;
export const BasicUsage: StoryObj = {
  render: BasicUsageExample,
  parameters: { sourceCode: 'import { Chart } from \'@semcore/ui/d3-chart\';\nimport React from \'react\';\n\nimport VennMockData from \'../../../__mocks__/venn\';\n\nconst Demo = () => {\n  return (\n    <div style={{ width: \'500px\' }}>\n      <Chart.Venn\n        data={data}\n        plotWidth={300}\n        plotHeight={300}\n        legendProps={legendProps}\n        aria-label=\'Venn chart\'\n      />\n    </div>\n  );\n};\n\nconst data = VennMockData.Default;\n\nconst legendProps = {\n  legendMap: {\n    G: { label: \'Good\' },\n    F: { label: \'Fast\' },\n    C: { label: \'Clean\' },\n  },\n};\n\nexport default Demo;\n' },
};
export const LegendAndPatternFill: StoryObj = {
  render: LegendAndPatternFillExample,
  parameters: { sourceCode: 'import { Plot, Venn, ChartLegend } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport React from \'react\';\n\nimport VennMockData from \'../../../__mocks__/venn\';\n\nconst Demo = () => {\n  const [legendItems, setLegendItems] = React.useState(() => defaultLegendItems);\n  const intersectionItems = defaultIntersections.filter((intersection) => {\n    const intersectionKeys = intersection.id.split(\'/\');\n    const disabled = intersectionKeys.some((key: string) => {\n      return !legendItems.find((item) => item.id === key)?.checked;\n    });\n\n    return !disabled;\n  });\n\n  const handleChangeVisible = React.useCallback((id: string, isVisible: boolean) => {\n    setLegendItems((prevItems) => {\n      const newItems = prevItems.map((item) => {\n        if (item.id === id) {\n          item.checked = isVisible;\n        }\n\n        return item;\n      });\n\n      return newItems;\n    });\n  }, []);\n\n  return (\n    <>\n      <ChartLegend\n        items={legendItems}\n        patterns\n        aria-label=\'Venn chart legend\'\n        onChangeVisibleItem={handleChangeVisible}\n      />\n      <Plot height={300} width={400} data={data} patterns>\n        <Venn>\n          {legendItems.map(({ id, label, checked, color }) => {\n            return checked && <Venn.Circle key={id} dataKey={id} name={label} color={color} />;\n          })}\n          {intersectionItems.map(({ id, label }) => (\n            <Venn.Intersection key={id} dataKey={id} name={label} />\n          ))}\n        </Venn>\n        <Venn.Tooltip>\n          {({ name, dataKey }) => {\n            return {\n              children: (\n                <>\n                  <Venn.Tooltip.Title>{name}</Venn.Tooltip.Title>\n                  {/* @ts-ignore */}\n                  <Text bold>{data[dataKey]}</Text>\n                </>\n              ),\n            };\n          }}\n        </Venn.Tooltip>\n      </Plot>\n    </>\n  );\n};\n\nconst data = VennMockData.Default;\n\nconst defaultLegendItems = [\n  {\n    id: \'G\',\n    label: \'Good\',\n    checked: true,\n    color: \'chart-palette-order-1\',\n  },\n  {\n    id: \'F\',\n    label: \'Fast\',\n    checked: true,\n    color: \'chart-palette-order-2\',\n  },\n  {\n    id: \'C\',\n    label: \'Cheap\',\n    checked: true,\n    color: \'chart-palette-order-3\',\n  },\n];\n\nconst defaultIntersections = [\n  {\n    id: \'G/F\',\n    label: \'Good & Fast\',\n    visible: true,\n  },\n  {\n    id: \'G/C\',\n    label: \'Good & Cheap\',\n    visible: true,\n  },\n  {\n    id: \'F/C\',\n    label: \'Fast & Cheap\',\n    visible: true,\n  },\n  {\n    id: \'G/F/C\',\n    label: \'Good & Fast & Cheap\',\n    visible: true,\n  },\n];\n\nexport default Demo;\n' },
};
export const CustomIntersectionsStyles: StoryObj = {
  render: CustomIntersectionsStylesExample,
  parameters: { sourceCode: 'import { Plot, Venn } from \'@semcore/ui/d3-chart\';\nimport React from \'react\';\n\nimport VennMockData from \'../../../__mocks__/venn\';\n\nconst Demo = () => {\n  return (\n    <Plot height={300} width={400} data={data}>\n      <Venn>\n        <Venn.Circle dataKey=\'G\' name=\'G\' />\n        <Venn.Circle dataKey=\'F\' name=\'F\' />\n        <Venn.Circle dataKey=\'C\' name=\'C\' />\n        <Venn.Intersection dataKey=\'G/F\' name=\'G/F\' />\n        <Venn.Intersection dataKey=\'G/C\' name=\'G/C\' />\n        <Venn.Intersection dataKey=\'F/C\' name=\'F/C\' />\n        <Venn.Intersection\n          dataKey=\'G/F/C\'\n          name=\'G/F/C\'\n          style={{\n            stroke: \'#F00\',\n            fill: \'#0F0\',\n            fillOpacity: 0.3,\n          }}\n        />\n      </Venn>\n    </Plot>\n  );\n};\n\nconst data = VennMockData.Default;\n\nexport default Demo;\n' },
};
export const SettingOrientation: StoryObj = {
  render: SettingOrientationExample,
  parameters: { sourceCode: 'import { Flex } from \'@semcore/ui/base-components\';\nimport Button from \'@semcore/ui/button\';\nimport { Plot, Venn } from \'@semcore/ui/d3-chart\';\nimport React from \'react\';\n\nimport VennMockData from \'../../../__mocks__/venn\';\n\nconst orders = [\n  (val1: any, val2: any) => val2.radius - val1.radius,\n  (val1: any, val2: any) => val1.radius - val2.radius,\n];\n\nconst orientations = [Math.PI / 2, Math.PI];\n\nconst Demo = () => {\n  const [orientation, setOrientation] = React.useState(0);\n  const [order, setOrder] = React.useState(0);\n\n  return (\n    <Flex alignItems=\'flex-start\' direction=\'column\'>\n      <Plot height={300} width={400} data={data}>\n        <Venn orientation={orientations[orientation]} orientationOrder={orders[order]}>\n          <Venn.Circle dataKey=\'F\' name=\'F\' />\n          <Venn.Circle dataKey=\'S\' name=\'S\' />\n          <Venn.Intersection dataKey=\'F/S\' name=\'F/S\' />\n        </Venn>\n      </Plot>\n      <Flex direction=\'row\'>\n        <Button onClick={() => setOrientation(Number(!orientation))} mr={2}>\n          Switch orientation\n        </Button>\n        <Button onClick={() => setOrder(Number(!order))}>Switch order</Button>\n      </Flex>\n    </Flex>\n  );\n};\n\nconst data = VennMockData.SwitchOrder;\n\nexport default Demo;\n' },
};
export const Venn: StoryObj = {
  render: VennExample,
  parameters: { sourceCode: 'import { Plot, Venn } from \'@semcore/ui/d3-chart\';\nimport { Text } from \'@semcore/ui/typography\';\nimport React from \'react\';\n\nimport VennMockData from \'../../../__mocks__/venn\';\n\nconst Demo = () => {\n  return (\n    <Plot height={300} width={400} data={data}>\n      <Venn>\n        <Venn.Circle dataKey=\'G\' name=\'Good\' />\n        <Venn.Circle dataKey=\'F\' name=\'Fast\' />\n        <Venn.Circle dataKey=\'C\' name=\'Cheap\' />\n        <Venn.Intersection dataKey=\'G/F\' name=\'Good & Fast\' />\n        <Venn.Intersection dataKey=\'G/C\' name=\'Good & Cheap\' />\n        <Venn.Intersection dataKey=\'F/C\' name=\'Fast & Cheap\' />\n        <Venn.Intersection dataKey=\'G/F/C\' name=\'Good & Fast & Cheap\' />\n      </Venn>\n      <Venn.Tooltip>\n        {({ name, dataKey }) => {\n          return {\n            children: (\n              <>\n                <Venn.Tooltip.Title>{name}</Venn.Tooltip.Title>\n                {/* @ts-ignore */}\n                <Text bold>{data[dataKey]}</Text>\n              </>\n            ),\n          };\n        }}\n      </Venn.Tooltip>\n    </Plot>\n  );\n};\n\nconst data = VennMockData.Default;\n\nexport default Demo;\n' },
};
