substitutions:
  _APP_VERSION: 0.0.2
steps:
  - name: node:16
    entrypoint: yarn
    args: ['--immutable']
  - name: node:16
    entrypoint: yarn
    args: ['build:icons']
  - name: node:16
    entrypoint: yarn
    args: ['--immutable', '--cwd', 'website']
  - name: node:16
    entrypoint: yarn
    args: ['build']
    dir: 'website'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'APP_VERSION=${_APP_VERSION}'
      - '-t'
      - 'us-east4-docker.pkg.dev/intergalactic-prod-tf/intergalactic-docker/intergalactic:${_APP_VERSION}'
      - '-f'
      - 'website/Dockerfile'
      - 'website/'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'APP_VERSION=${_APP_VERSION}'
      - '-t'
      - 'us-east4-docker.pkg.dev/intergalactic-prod-tf/intergalactic-docker/intergalactic:${_APP_VERSION}-${SHORT_SHA}'
      - '-f'
      - 'website/Dockerfile'
      - 'website/'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east4-docker.pkg.dev/intergalactic-prod-tf/intergalactic-docker/intergalactic:${_APP_VERSION}'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east4-docker.pkg.dev/intergalactic-prod-tf/intergalactic-docker/intergalactic:${_APP_VERSION}-${SHORT_SHA}'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'beta',
        'run',
        'deploy',
        'intergalactic-docker',
        '--image',
        'us-east4-docker.pkg.dev/intergalactic-prod-tf/intergalactic-docker/intergalactic:${_APP_VERSION}-${SHORT_SHA}',
        '--region',
        'us-east4',
        '--platform',
        'managed',
        '--min-instances',
        '1',
        '--max-instances',
        '5',
        '--ingress',
        'internal-and-cloud-load-balancing',
      ]
  - name: node:16
    entrypoint: yarn
    args: ['upload-search-index']
    dir: 'website'
    env:
      - 'ALGOLIA_SECRET_KEY=$_ALGOLIA_SECRET_KEY'

timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_8'
