substitutions:
  _APP_VERSION: 0.0.1
steps:
  - name: node:16
    entrypoint: yarn
    args: ['--non-interactive', '--frozen-lockfile']
  - name: node:16
    entrypoint: yarn
    args: ['build']
  - name: node:16
    entrypoint: yarn
    args: ['--non-interactive', '--frozen-lockfile', '--cwd', 'website']
  - name: node:16
    entrypoint: yarn
    args: ['--cwd', 'website', 'build:client']
  - name: node:16
    entrypoint: yarn
    args: ['--cwd', 'website', 'build:server']
  - name: node:16
    entrypoint: yarn
    args: ['--cwd', 'website', 'build:interface']
  - name: node:16
    entrypoint: yarn
    args: ['--cwd', 'website', 'lint:md']
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "ROOT_PATH=${_ROOT_PATH}" >> website/.env
        echo "POSTGRES_URL=${_POSTGRES_URL}" >> website/.env
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'APP_VERSION=${_APP_VERSION}'
      - '-t'
      - 'us-east4-docker.pkg.dev/intergalactic-prod-tf/intergalactic-docker/intergalactic:${_APP_VERSION}'
      - '-f'
      - 'website/docker/intergalactic/Dockerfile'
      - 'website/'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'APP_VERSION=${_APP_VERSION}'
      - '-t'
      - 'us-east4-docker.pkg.dev/intergalactic-prod-tf/intergalactic-docker/intergalactic:${_APP_VERSION}-${SHORT_SHA}'
      - '-f'
      - 'website/docker/intergalactic/Dockerfile'
      - 'website/'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east4-docker.pkg.dev/intergalactic-prod-tf/intergalactic-docker/intergalactic:${_APP_VERSION}'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east4-docker.pkg.dev/intergalactic-prod-tf/intergalactic-docker/intergalactic:${_APP_VERSION}-${SHORT_SHA}'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'beta',
        'run',
        'deploy',
        'intergalactic-docker',
        '--image',
        'us-east4-docker.pkg.dev/intergalactic-prod-tf/intergalactic-docker/intergalactic:${_APP_VERSION}-${SHORT_SHA}',
        '--region',
        'us-east4',
        '--platform',
        'managed',
        '--min-instances',
        '1',
        '--max-instances',
        '5',
        '--ingress',
        'internal-and-cloud-load-balancing',
      ]
  - name: node:16
    entrypoint: node
    args: ['algoliaPublish.js']
    dir: 'website'
    env:
      - 'ALGOLIA_SECRET_KEY=$_ALGOLIA_SECRET_KEY'

timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_8'
