substitutions:
  _SERVICE_NAME: intergalactic
  _GCR_HOSTNAME: us-east4-docker.pkg.dev

steps:
  - id: 'Unshallow git history'
    name: gcr.io/cloud-builders/git
    args: ["fetch", "--unshallow", "--tags"]
  - id: 'Build docker'
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg="ALGOLIA_SECRET_KEY=$_ALGOLIA_SECRET_KEY" --tag=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA --file=website/Dockerfile .']
    env:
      - ALGOLIA_SECRET_KEY=$_ALGOLIA_SECRET_KEY
  - id: 'Push docker'
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  - id: 'Deploy docker'
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --region=$_DEPLOY_REGION
      - --labels=gcb-trigger-id=$_TRIGGER_ID
images:
  - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
timeout: 3600s
options:
  machineType: E2_HIGHCPU_8
