substitutions:
  _SERVICE_NAME: intergalactic
  _GCR_HOSTNAME: us-east4-docker.pkg.dev

steps:
  - id: 'Build docker'
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --file=website/Dockerfile
      - .
  - id: 'Push docker'
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  - id: 'Deploy docker'
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --region=$_DEPLOY_REGION
      - --labels=gcb-trigger-id=$_TRIGGER_ID
  - id: 'Install dependency'
    name: node:16
    entrypoint: yarn
    dir: website
  - id: 'Update search'
    name: node:16
    entrypoint: yarn
    args: ['upload-search-index']
    dir: website
    env:
      - ALGOLIA_SECRET_KEY=$_ALGOLIA_SECRET_KEY
images:
  - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
timeout: 3600s
options:
  machineType: E2_HIGHCPU_8
