substitutions:
  _SERVICE_NAME: intergalactic
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: us.gcr.io

steps:
  - id: 'Build'
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --file=website/Dockerfile
      - .
  - id: 'Push'
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  - id: 'Deploy'
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --region=$_DEPLOY_REGION
      - --labels=gcb-trigger-id=$_TRIGGER_ID
images:
  - $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_8'
