import Serp from '@semcore/icon/Serp/m';
import { Box, Col, Row } from '@semcore/ui/base-components';
import Card from '@semcore/ui/card';
import type { DataTableData } from '@semcore/ui/data-table';
import { DataTable } from '@semcore/ui/data-table';
import Ellipsis from '@semcore/ui/ellipsis';
import React from 'react';

const Demo = () => {
  return (
    <Box
      wMin={980}
      wMax={1606}
      mx={8}
      mt={4}
    >
      <Card tag='section'>
        <Card.Body px={0} pt={0}>
          <Box>
            <DataTable
              aria-label='real table'
              data={data}
              columns={columns}
              sideIndents='wide'
              compact
              headerProps={{
                sticky: true,
                withScrollBar: true,
              }}
              w='auto'
            />
          </Box>

        </Card.Body>
      </Card>
    </Box>

  );
};

const TableHeaderCell = ({ children }: any) => {
  return (
    <Ellipsis tooltip='false'>
      {children}
    </Ellipsis>
  );
};

const columns = [
  {
    name: 'keyword',
    children: <TableHeaderCell>Keyword</TableHeaderCell>,
    gtcWidth: 'minmax(139px, auto)',
    fixed: 'left' as const,
  },
  {
    name: 'intent',
    children: <TableHeaderCell>Intent</TableHeaderCell>,
    gtcWidth: '52px',
  },
  {
    name: 'previous',
    children: <TableHeaderCell>Previous</TableHeaderCell>,
    gtcWidth: 'minmax(60px, 90px)',
  },
  {
    name: 'current',
    children: <TableHeaderCell>Current</TableHeaderCell>,
    gtcWidth: 'minmax(60px, 90px)',
  },
  {
    name: 'diff',
    children: <TableHeaderCell>Diff.</TableHeaderCell>,
    gtcWidth: 'minmax(48px, 60px)',
  },
  {
    name: 'trafficDiff',
    children: <TableHeaderCell>Traffic Diff.</TableHeaderCell>,
    gtcWidth: 'minmax(80px, 100px)',
  },
  {
    name: 'traffic',
    children: <TableHeaderCell>Traffic %</TableHeaderCell>,
    gtcWidth: 'minmax(66px, 80px)',
  },
  {
    name: 'changesSerp',
    children: <TableHeaderCell>Changes on SERP</TableHeaderCell>,
    gtcWidth: '120px',
  },
  {
    name: 'volume',
    children: <TableHeaderCell>Volume</TableHeaderCell>,
    gtcWidth: 'minmax(69px, 80px)',
  },
  {
    name: 'kd',
    children: <TableHeaderCell>KD %</TableHeaderCell>,
    gtcWidth: 'minmax(64px, 80px)',
  },
  {
    name: 'cpc',
    children: <TableHeaderCell>CPC</TableHeaderCell>,
    gtcWidth: 'minmax(68px, 80px)',
  },
  {
    name: 'url',
    children: <TableHeaderCell>URL</TableHeaderCell>,
    gtcWidth: 'minmax(200px, auto)',
  },
  {
    name: 'updated',
    children: <TableHeaderCell>Updated</TableHeaderCell>,
    gtcWidth: '80px',
  },
];

const data: DataTableData = [
  {
    keyword: 'monarch',
    intent: 'N',
    previous: 1,
    current: 2,
    diff: -1,
    trafficDiff: '+8,2K',
    traffic: 0.78,
    changesSerp: <Serp />,
    volume: '165K',
    kd: '100',
    cpc: '5.39',
    url: 'www.worldwildlife.org/species/monarch-butterfly/',
    updated: '2 days',
  },
  {
    keyword: 'amur leopard',
    intent: 'I T',
    previous: 7,
    current: 5,
    diff: 2,
    trafficDiff: '-10K',
    traffic: 0.01,
    changesSerp: <Serp />,
    volume: '40.5K',
    kd: '62',
    cpc: '0.69',
    url: 'www.worldwildlife.org/species/amur-leopard/',
    updated: '2 days',
  },
  {
    keyword: 'giant panda',
    intent: 'I',
    previous: 3,
    current: 3,
    diff: 0,
    trafficDiff: '+1.2K',
    traffic: 0.45,
    changesSerp: <Serp />,
    volume: '201K',
    kd: '85',
    cpc: '1.20',
    url: 'www.worldwildlife.org/species/giant-panda/',
    updated: '1 day',
  },
  {
    keyword: 'sea turtle conservation',
    intent: 'I C',
    previous: 12,
    current: 8,
    diff: 4,
    trafficDiff: '+500',
    traffic: 0.12,
    changesSerp: <Serp />,
    volume: '12.1K',
    kd: '55',
    cpc: '2.45',
    url: 'www.worldwildlife.org/species/sea-turtle/',
    updated: '3 days',
  },
  {
    keyword: 'blue whale facts',
    intent: 'I',
    previous: 2,
    current: 4,
    diff: -2,
    trafficDiff: '-2.1K',
    traffic: 0.33,
    changesSerp: <Serp />,
    volume: '90.5K',
    kd: '70',
    cpc: '0.15',
    url: 'www.worldwildlife.org/species/blue-whale/',
    updated: '5 hours',
  },
  {
    keyword: 'african elephant',
    intent: 'I N',
    previous: 15,
    current: 10,
    diff: 5,
    trafficDiff: '+3.4K',
    traffic: 0.22,
    changesSerp: <Serp />,
    volume: '110K',
    kd: '78',
    cpc: '1.10',
    url: 'www.worldwildlife.org/species/african-elephant/',
    updated: '2 days',
  },
  {
    keyword: 'snow leopard habitat',
    intent: 'I',
    previous: 20,
    current: 18,
    diff: 2,
    trafficDiff: '+200',
    traffic: 0.05,
    changesSerp: <Serp />,
    volume: '18.1K',
    kd: '48',
    cpc: '0.85',
    url: 'www.worldwildlife.org/species/snow-leopard/',
    updated: '4 days',
  },
  {
    keyword: 'adopt a tiger',
    intent: 'T C',
    previous: 5,
    current: 4,
    diff: 1,
    trafficDiff: '+4.2K',
    traffic: 0.56,
    changesSerp: <Serp />,
    volume: '33.1K',
    kd: '92',
    cpc: '12.50',
    url: 'www.worldwildlife.org/species/tiger/',
    updated: '1 day',
  },
  {
    keyword: 'mountain gorilla',
    intent: 'I',
    previous: 8,
    current: 11,
    diff: -3,
    trafficDiff: '-1.5K',
    traffic: 0.09,
    changesSerp: <Serp />,
    volume: '27.1K',
    kd: '60',
    cpc: '0.40',
    url: 'www.worldwildlife.org/species/mountain-gorilla/',
    updated: '2 days',
  },
  {
    keyword: 'rhino poaching statistics',
    intent: 'I',
    previous: 25,
    current: 15,
    diff: 10,
    trafficDiff: '+1.8K',
    traffic: 0.15,
    changesSerp: <Serp />,
    volume: '14.8K',
    kd: '42',
    cpc: '0.00',
    url: 'www.worldwildlife.org/species/rhino/',
    updated: '6 days',
  },
  {
    keyword: 'amazon rainforest birds',
    intent: 'I',
    previous: 14,
    current: 14,
    diff: 0,
    trafficDiff: '0',
    traffic: 0.08,
    changesSerp: <Serp />,
    volume: '22.2K',
    kd: '51',
    cpc: '0.35',
    url: 'www.worldwildlife.org/habitats/amazon/',
    updated: '3 days',
  },
  {
    keyword: 'polar bear melting ice',
    intent: 'I',
    previous: 4,
    current: 9,
    diff: -5,
    trafficDiff: '-5.2K',
    traffic: 0.18,
    changesSerp: <Serp />,
    volume: '60.5K',
    kd: '77',
    cpc: '0.10',
    url: 'www.worldwildlife.org/species/polar-bear/',
    updated: '2 days',
  },
  {
    keyword: 'red panda diet',
    intent: 'I',
    previous: 6,
    current: 6,
    diff: 0,
    trafficDiff: '+100',
    traffic: 0.25,
    changesSerp: <Serp />,
    volume: '49.5K',
    kd: '35',
    cpc: '0.22',
    url: 'www.worldwildlife.org/species/red-panda/',
    updated: '1 day',
  },
  {
    keyword: 'pangolin scales',
    intent: 'I',
    previous: 30,
    current: 22,
    diff: 8,
    trafficDiff: '+1.1K',
    traffic: 0.04,
    changesSerp: <Serp />,
    volume: '12.5K',
    kd: '58',
    cpc: '0.05',
    url: 'www.worldwildlife.org/species/pangolin/',
    updated: '7 days',
  },
  {
    keyword: 'black rhino',
    intent: 'N I',
    previous: 10,
    current: 7,
    diff: 3,
    trafficDiff: '+2.9K',
    traffic: 0.19,
    changesSerp: <Serp />,
    volume: '33.1K',
    kd: '65',
    cpc: '0.90',
    url: 'www.worldwildlife.org/species/black-rhino/',
    updated: '2 days',
  },
  {
    keyword: 'save the vaquita',
    intent: 'I C',
    previous: 2,
    current: 1,
    diff: 1,
    trafficDiff: '+15K',
    traffic: 0.95,
    changesSerp: <Serp />,
    volume: '18.1K',
    kd: '40',
    cpc: '1.50',
    url: 'www.worldwildlife.org/species/vaquita/',
    updated: '12 hours',
  },
  {
    keyword: 'coral reef bleaching',
    intent: 'I',
    previous: 18,
    current: 25,
    diff: -7,
    trafficDiff: '-3.1K',
    traffic: 0.07,
    changesSerp: <Serp />,
    volume: '27.1K',
    kd: '69',
    cpc: '0.45',
    url: 'www.worldwildlife.org/habitats/coral-reefs/',
    updated: '3 days',
  },
  {
    keyword: 'borneo orangutan',
    intent: 'I N',
    previous: 9,
    current: 10,
    diff: -1,
    trafficDiff: '-400',
    traffic: 0.14,
    changesSerp: <Serp />,
    volume: '14.8K',
    kd: '53',
    cpc: '0.70',
    url: 'www.worldwildlife.org/species/orangutan/',
    updated: '4 days',
  },
  {
    keyword: 'galapagos tortoise',
    intent: 'I',
    previous: 13,
    current: 12,
    diff: 1,
    trafficDiff: '+800',
    traffic: 0.20,
    changesSerp: <Serp />,
    volume: '40.5K',
    kd: '44',
    cpc: '0.30',
    url: 'www.worldwildlife.org/species/galapagos-tortoise/',
    updated: '2 days',
  },
  {
    keyword: 'whale shark size',
    intent: 'I',
    previous: 5,
    current: 8,
    diff: -3,
    trafficDiff: '-2.5K',
    traffic: 0.31,
    changesSerp: <Serp />,
    volume: '74K',
    kd: '61',
    cpc: '0.12',
    url: 'www.worldwildlife.org/species/whale-shark/',
    updated: '1 day',
  },
  {
    keyword: 'how to stop deforestation',
    intent: 'I',
    previous: 40,
    current: 31,
    diff: 9,
    trafficDiff: '+1.9K',
    traffic: 0.03,
    changesSerp: <Serp />,
    volume: '22.2K',
    kd: '82',
    cpc: '3.10',
    url: 'www.worldwildlife.org/threats/deforestation/',
    updated: '5 days',
  },
  {
    keyword: 'koala endangered status',
    intent: 'I',
    previous: 11,
    current: 6,
    diff: 5,
    trafficDiff: '+6.2K',
    traffic: 0.28,
    changesSerp: <Serp />,
    volume: '60.5K',
    kd: '57',
    cpc: '0.55',
    url: 'www.worldwildlife.org/species/koala/',
    updated: '2 days',
  },
  {
    keyword: 'bengal tiger vs siberian tiger',
    intent: 'I',
    previous: 16,
    current: 16,
    diff: 0,
    trafficDiff: '0',
    traffic: 0.11,
    changesSerp: <Serp />,
    volume: '33.1K',
    kd: '39',
    cpc: '0.00',
    url: 'www.worldwildlife.org/species/tiger/',
    updated: '1 week',
  },
  {
    keyword: 'arctic fox winter coat',
    intent: 'I',
    previous: 22,
    current: 19,
    diff: 3,
    trafficDiff: '+450',
    traffic: 0.06,
    changesSerp: <Serp />,
    volume: '12.1K',
    kd: '31',
    cpc: '0.05',
    url: 'www.worldwildlife.org/species/arctic-fox/',
    updated: '4 days',
  },
  {
    keyword: 'jaguar range map',
    intent: 'I',
    previous: 7,
    current: 13,
    diff: -6,
    trafficDiff: '-3.8K',
    traffic: 0.17,
    changesSerp: <Serp />,
    volume: '18.1K',
    kd: '50',
    cpc: '0.40',
    url: 'www.worldwildlife.org/species/jaguar/',
    updated: '2 days',
  },
  {
    keyword: 'sustainable fishing practices',
    intent: 'I C',
    previous: 35,
    current: 28,
    diff: 7,
    trafficDiff: '+1.3K',
    traffic: 0.04,
    changesSerp: <Serp />,
    volume: '9.9K',
    kd: '72',
    cpc: '4.80',
    url: 'www.worldwildlife.org/industries/sustainable-fishing/',
    updated: '6 days',
  },
  {
    keyword: 'beluga whale sounds',
    intent: 'I',
    previous: 3,
    current: 5,
    diff: -2,
    trafficDiff: '-1.1K',
    traffic: 0.40,
    changesSerp: <Serp />,
    volume: '40.5K',
    kd: '43',
    cpc: '0.20',
    url: 'www.worldwildlife.org/species/beluga/',
    updated: '3 days',
  },
  {
    keyword: 'narwhal tusk purpose',
    intent: 'I',
    previous: 1,
    current: 1,
    diff: 0,
    trafficDiff: '+500',
    traffic: 0.82,
    changesSerp: <Serp />,
    volume: '49.5K',
    kd: '38',
    cpc: '0.15',
    url: 'www.worldwildlife.org/species/narwhal/',
    updated: '1 day',
  },
  {
    keyword: 'platypus venomous',
    intent: 'I',
    previous: 19,
    current: 24,
    diff: -5,
    trafficDiff: '-900',
    traffic: 0.05,
    changesSerp: <Serp />,
    volume: '33.1K',
    kd: '47',
    cpc: '0.00',
    url: 'www.worldwildlife.org/species/platypus/',
    updated: '4 days',
  },
  {
    keyword: 'okapi habitat',
    intent: 'I',
    previous: 14,
    current: 10,
    diff: 4,
    trafficDiff: '+2.2K',
    traffic: 0.13,
    changesSerp: <Serp />,
    volume: '12.1K',
    kd: '34',
    cpc: '0.25',
    url: 'www.worldwildlife.org/species/okapi/',
    updated: '2 days',
  },
  {
    keyword: 'save the bees donation',
    intent: 'T',
    previous: 8,
    current: 4,
    diff: 4,
    trafficDiff: '+7.8K',
    traffic: 0.51,
    changesSerp: <Serp />,
    volume: '27.1K',
    kd: '88',
    cpc: '8.40',
    url: 'www.worldwildlife.org/species/bees/',
    updated: '12 hours',
  },
  {
    keyword: 'leatherback turtle size',
    intent: 'I',
    previous: 12,
    current: 12,
    diff: 0,
    trafficDiff: '-50',
    traffic: 0.18,
    changesSerp: <Serp />,
    volume: '18.1K',
    kd: '41',
    cpc: '0.10',
    url: 'www.worldwildlife.org/species/leatherback-turtle/',
    updated: '3 days',
  },
  {
    keyword: 'humpback whale migration',
    intent: 'I',
    previous: 6,
    current: 3,
    diff: 3,
    trafficDiff: '+4.5K',
    traffic: 0.44,
    changesSerp: <Serp />,
    volume: '40.5K',
    kd: '59',
    cpc: '0.35',
    url: 'www.worldwildlife.org/species/humpback-whale/',
    updated: '1 day',
  },
  {
    keyword: 'sumatran rhino count',
    intent: 'I',
    previous: 45,
    current: 38,
    diff: 7,
    trafficDiff: '+300',
    traffic: 0.02,
    changesSerp: <Serp />,
    volume: '8.1K',
    kd: '46',
    cpc: '0.00',
    url: 'www.worldwildlife.org/species/sumatran-rhino/',
    updated: '5 days',
  },
  {
    keyword: 'elephant ivory trade',
    intent: 'I C',
    previous: 21,
    current: 17,
    diff: 4,
    trafficDiff: '+1.2K',
    traffic: 0.09,
    changesSerp: <Serp />,
    volume: '14.8K',
    kd: '71',
    cpc: '1.25',
    url: 'www.worldwildlife.org/threats/ivory-trade/',
    updated: '2 days',
  },
  {
    keyword: 'manatee protection act',
    intent: 'I N',
    previous: 4,
    current: 6,
    diff: -2,
    trafficDiff: '-800',
    traffic: 0.36,
    changesSerp: <Serp />,
    volume: '12.1K',
    kd: '52',
    cpc: '0.60',
    url: 'www.worldwildlife.org/species/manatee/',
    updated: '4 days',
  },
  {
    keyword: 'cheetah speed facts',
    intent: 'I',
    previous: 2,
    current: 2,
    diff: 0,
    trafficDiff: '+150',
    traffic: 0.65,
    changesSerp: <Serp />,
    volume: '110K',
    kd: '66',
    cpc: '0.18',
    url: 'www.worldwildlife.org/species/cheetah/',
    updated: '1 day',
  },
  {
    keyword: 'wildlife photography tips',
    intent: 'I C',
    previous: 55,
    current: 42,
    diff: 13,
    trafficDiff: '+2.1K',
    traffic: 0.04,
    changesSerp: <Serp />,
    volume: '33.1K',
    kd: '75',
    cpc: '4.20',
    url: 'www.worldwildlife.org/magazine/photography/',
    updated: '6 days',
  },
  {
    keyword: 'red-eyed tree frog',
    intent: 'I N',
    previous: 10,
    current: 14,
    diff: -4,
    trafficDiff: '-1.4K',
    traffic: 0.12,
    changesSerp: <Serp />,
    volume: '27.1K',
    kd: '49',
    cpc: '0.30',
    url: 'www.worldwildlife.org/species/tree-frog/',
    updated: '2 days',
  },
  {
    keyword: 'climate change impacts',
    intent: 'I',
    previous: 8,
    current: 5,
    diff: 3,
    trafficDiff: '+12.5K',
    traffic: 0.58,
    changesSerp: <Serp />,
    volume: '301K',
    kd: '94',
    cpc: '2.80',
    url: 'www.worldwildlife.org/threats/climate-change/',
    updated: '1 day',
  },
  {
    keyword: 'tarsier monkey',
    intent: 'I',
    previous: 18,
    current: 18,
    diff: 0,
    trafficDiff: '0',
    traffic: 0.07,
    changesSerp: <Serp />,
    volume: '14.8K',
    kd: '33',
    cpc: '0.05',
    url: 'www.worldwildlife.org/species/tarsier/',
    updated: '5 days',
  },
  {
    keyword: 'plastic in the ocean',
    intent: 'I',
    previous: 5,
    current: 9,
    diff: -4,
    trafficDiff: '-6.7K',
    traffic: 0.29,
    changesSerp: <Serp />,
    volume: '135K',
    kd: '81',
    cpc: '1.45',
    url: 'www.worldwildlife.org/threats/pollution/',
    updated: '2 days',
  },
  {
    keyword: 'gray wolf packs',
    intent: 'I',
    previous: 12,
    current: 11,
    diff: 1,
    trafficDiff: '+600',
    traffic: 0.15,
    changesSerp: <Serp />,
    volume: '40.5K',
    kd: '56',
    cpc: '0.25',
    url: 'www.worldwildlife.org/species/gray-wolf/',
    updated: '3 days',
  },
  {
    keyword: 'saola rare sighting',
    intent: 'I',
    previous: 50,
    current: 30,
    diff: 20,
    trafficDiff: '+900',
    traffic: 0.03,
    changesSerp: <Serp />,
    volume: '6.6K',
    kd: '45',
    cpc: '0.00',
    url: 'www.worldwildlife.org/species/saola/',
    updated: '1 week',
  },
  {
    keyword: 'snowy owl migration',
    intent: 'I',
    previous: 7,
    current: 12,
    diff: -5,
    trafficDiff: '-2.3K',
    traffic: 0.11,
    changesSerp: <Serp />,
    volume: '22.2K',
    kd: '41',
    cpc: '0.12',
    url: 'www.worldwildlife.org/species/snowy-owl/',
    updated: '4 days',
  },
  {
    keyword: 'borneo pygmy elephant',
    intent: 'I',
    previous: 20,
    current: 15,
    diff: 5,
    trafficDiff: '+1.1K',
    traffic: 0.08,
    changesSerp: <Serp />,
    volume: '9.9K',
    kd: '37',
    cpc: '0.40',
    url: 'www.worldwildlife.org/species/pygmy-elephant/',
    updated: '2 days',
  },
  {
    keyword: 'endangered species list',
    intent: 'I N',
    previous: 1,
    current: 1,
    diff: 0,
    trafficDiff: '+18K',
    traffic: 0.92,
    changesSerp: <Serp />,
    volume: '246K',
    kd: '98',
    cpc: '3.50',
    url: 'www.worldwildlife.org/species/directory/',
    updated: '1 day',
  },
  {
    keyword: 'hawkbill turtle shell',
    intent: 'I',
    previous: 33,
    current: 35,
    diff: -2,
    trafficDiff: '-100',
    traffic: 0.02,
    changesSerp: <Serp />,
    volume: '8.1K',
    kd: '54',
    cpc: '0.20',
    url: 'www.worldwildlife.org/species/hawksbill-turtle/',
    updated: '6 days',
  },
  {
    keyword: 'mountain lion tracks',
    intent: 'I',
    previous: 14,
    current: 10,
    diff: 4,
    trafficDiff: '+1.8K',
    traffic: 0.14,
    changesSerp: <Serp />,
    volume: '33.1K',
    kd: '47',
    cpc: '0.10',
    url: 'www.worldwildlife.org/species/mountain-lion/',
    updated: '2 days',
  },
  {
    keyword: 'greenhouse effect explanation',
    intent: 'I',
    previous: 3,
    current: 2,
    diff: 1,
    trafficDiff: '+5.4K',
    traffic: 0.62,
    changesSerp: <Serp />,
    volume: '110K',
    kd: '89',
    cpc: '1.95',
    url: 'www.worldwildlife.org/threats/climate-change/',
    updated: '1 day',
  },
  {
    keyword: 'sloth sleeping habits',
    intent: 'I',
    previous: 9,
    current: 11,
    diff: -2,
    trafficDiff: '-600',
    traffic: 0.19,
    changesSerp: <Serp />,
    volume: '49.5K',
    kd: '32',
    cpc: '0.05',
    url: 'www.worldwildlife.org/species/sloth/',
    updated: '4 days',
  },
  {
    keyword: 'how to help wildlife',
    intent: 'I T',
    previous: 22,
    current: 14,
    diff: 8,
    trafficDiff: '+2.8K',
    traffic: 0.10,
    changesSerp: <Serp />,
    volume: '12.1K',
    kd: '73',
    cpc: '6.20',
    url: 'www.worldwildlife.org/how-to-help/',
    updated: '2 days',
  },
  {
    keyword: 'mexican wolf recovery',
    intent: 'I',
    previous: 40,
    current: 25,
    diff: 15,
    trafficDiff: '+1.4K',
    traffic: 0.05,
    changesSerp: <Serp />,
    volume: '6.6K',
    kd: '43',
    cpc: '0.15',
    url: 'www.worldwildlife.org/species/mexican-wolf/',
    updated: '5 days',
  },
  {
    keyword: 'duck-billed platypus facts',
    intent: 'I',
    previous: 6,
    current: 7,
    diff: -1,
    trafficDiff: '-300',
    traffic: 0.21,
    changesSerp: <Serp />,
    volume: '40.5K',
    kd: '40',
    cpc: '0.00',
    url: 'www.worldwildlife.org/species/platypus/',
    updated: '3 days',
  },
  {
    keyword: 'black-footed ferret',
    intent: 'I N',
    previous: 15,
    current: 13,
    diff: 2,
    trafficDiff: '+400',
    traffic: 0.09,
    changesSerp: <Serp />,
    volume: '18.1K',
    kd: '51',
    cpc: '0.35',
    url: 'www.worldwildlife.org/species/black-footed-ferret/',
    updated: '1 week',
  },
  {
    keyword: 'arctic ice minimum',
    intent: 'I',
    previous: 4,
    current: 8,
    diff: -4,
    trafficDiff: '-2.9K',
    traffic: 0.25,
    changesSerp: <Serp />,
    volume: '27.1K',
    kd: '76',
    cpc: '0.80',
    url: 'www.worldwildlife.org/pages/arctic-sea-ice/',
    updated: '2 days',
  },
  {
    keyword: 'conservation volunteer abroad',
    intent: 'T C',
    previous: 65,
    current: 51,
    diff: 14,
    trafficDiff: '+2.2K',
    traffic: 0.03,
    changesSerp: <Serp />,
    volume: '14.8K',
    kd: '84',
    cpc: '11.00',
    url: 'www.worldwildlife.org/about/careers/',
    updated: '4 days',
  },
  {
    keyword: 'bamboo forest preservation',
    intent: 'I',
    previous: 28,
    current: 30,
    diff: -2,
    trafficDiff: '-150',
    traffic: 0.02,
    changesSerp: <Serp />,
    volume: '5.4K',
    kd: '48',
    cpc: '1.20',
    url: 'www.worldwildlife.org/habitats/forests/',
    updated: '6 days',
  },
  {
    keyword: 'koala vs eucalyptus',
    intent: 'I',
    previous: 17,
    current: 17,
    diff: 0,
    trafficDiff: '0',
    traffic: 0.08,
    changesSerp: <Serp />,
    volume: '12.1K',
    kd: '36',
    cpc: '0.00',
    url: 'www.worldwildlife.org/species/koala/',
    updated: '3 days',
  },
  {
    keyword: 'global warming solutions',
    intent: 'I',
    previous: 10,
    current: 7,
    diff: 3,
    trafficDiff: '+9.1K',
    traffic: 0.47,
    changesSerp: <Serp />,
    volume: '165K',
    kd: '91',
    cpc: '4.15',
    url: 'www.worldwildlife.org/threats/climate-change/',
    updated: '1 day',
  },
  {
    keyword: 'how do dolphins sleep',
    intent: 'I',
    previous: 2,
    current: 5,
    diff: -3,
    trafficDiff: '-4.3K',
    traffic: 0.38,
    changesSerp: <Serp />,
    volume: '90.5K',
    kd: '53',
    cpc: '0.10',
    url: 'www.worldwildlife.org/species/dolphin/',
    updated: '2 days',
  },
  {
    keyword: 'wwf gift shop',
    intent: 'T N',
    previous: 1,
    current: 1,
    diff: 0,
    trafficDiff: '+25K',
    traffic: 0.88,
    changesSerp: <Serp />,
    volume: '74K',
    kd: '80',
    cpc: '2.50',
    url: 'www.worldwildlife.org/shop/',
    updated: '5 hours',
  },
];

export default Demo;
