import Accrordion from '@semcore/ui/accordion';
import type { Meta, StoryObj } from '@storybook/react-vite';

import AccordionAnimationExample from './examples/accordion-collapse-duration';
import ButtonsOnToggleExample from './examples/button-on-toggle';
import DefaultValuesExample from './examples/default-values';
import ValuesExample from './examples/values';
const meta: Meta<typeof Accrordion> = {
  title: 'Components/Accordion/Tests',
  component: Accrordion,
};
export default meta;
type Story = StoryObj<typeof Accrordion>;
export const ButtonsOnToggle: Story = {
  render: ButtonsOnToggleExample,
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport Button from \'@semcore/ui/button\';\nimport React from \'react\';\n\nconst Demo = () => {\n  const [value, onChange] = React.useState([0]);\n\n  return (\n    <Accordion>\n      {[...new Array(2)].map((_, index) => {\n        return (\n          <Accordion.Item value={index} key={index}>\n            <Accordion.Item.Toggle>\n              <Accordion.Item.Chevron />\n              <div>{`Toggle ${index + 1}`}</div>\n              <Button\n                data-testid={`button_in_toggle_${index + 1}`}\n                onClick={(e) => {\n                  e.stopPropagation();\n                }}\n              >\n                Just button\n              </Button>\n            </Accordion.Item.Toggle>\n            <Accordion.Item.Collapse>\n              <div>{`Accordion content ${index + 1}`}</div>\n              <Button>\n                Just button\n              </Button>\n            </Accordion.Item.Collapse>\n          </Accordion.Item>\n        );\n      })}\n    </Accordion>\n  );\n};\n\nexport default Demo;\n' },
};
export const Values: Story = {
  render: ValuesExample,
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\ntype ValueType = null | number | string | Array<number | string | null>;\n\nconst Demo = () => {\n  const [value, setValue] = React.useState<ValueType>([0, \'one\', null]);\n\n  return (\n    <Accordion\n      value={value}\n      onChange={(newValue: ValueType) => setValue(newValue)}\n    >\n      <Accordion.Item value={0}>\n        <Accordion.Item.Toggle pb={2}>\n          <Accordion.Item.ToggleButton>\n            <Accordion.Item.Chevron mr={2} />\n            Number: 0\n          </Accordion.Item.ToggleButton>\n        </Accordion.Item.Toggle>\n        <Accordion.Item.Collapse data-test-id=\'number\'>\n          <Box p=\'12px 24px 24px\'>Section with value = 0 (number)</Box>\n        </Accordion.Item.Collapse>\n      </Accordion.Item>\n\n      <Accordion.Item value=\'one\'>\n        <Accordion.Item.Toggle pb={2}>\n          <Accordion.Item.ToggleButton>\n            <Accordion.Item.Chevron mr={2} />\n            String: "one"\n          </Accordion.Item.ToggleButton>\n        </Accordion.Item.Toggle>\n        <Accordion.Item.Collapse data-test-id=\'string\'>\n          <Box p=\'12px 24px 24px\'>Section with value = "one" (string)</Box>\n        </Accordion.Item.Collapse>\n      </Accordion.Item>\n    </Accordion>\n  );\n};\n\nexport default Demo;\n' },
};
export const DefaultValues: Story = {
  render: DefaultValuesExample,
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst Demo = () => {\n  return (\n    <Accordion defaultValue={1}>\n      <Accordion.Item value={1}>\n        <Accordion.Item.Toggle pb={2}>\n          <Accordion.Item.ToggleButton>\n            <Accordion.Item.Chevron mr={2} />\n            Section 1\n          </Accordion.Item.ToggleButton>\n        </Accordion.Item.Toggle>\n        <Accordion.Item.Collapse data-test-id=\'default-value\'>\n          <Box p=\'12px 24px 24px\'>Hello Section 1</Box>\n        </Accordion.Item.Collapse>\n      </Accordion.Item>\n\n      <Accordion.Item value=\'two\'>\n        <Accordion.Item.Toggle pb={2}>\n          <Accordion.Item.ToggleButton>\n            <Accordion.Item.Chevron mr={2} />\n            Section "two"\n          </Accordion.Item.ToggleButton>\n        </Accordion.Item.Toggle>\n        <Accordion.Item.Collapse>\n          <Box p=\'12px 24px 24px\'>Hello Section "two"</Box>\n        </Accordion.Item.Collapse>\n      </Accordion.Item>\n    </Accordion>\n  );\n};\n\nexport default Demo;\n' },
};
export const AccordionAnimation: StoryObj = {
  render: AccordionAnimationExample,
  parameters: { sourceCode: 'import Accordion from \'@semcore/ui/accordion\';\nimport { Box } from \'@semcore/ui/base-components\';\nimport React from \'react\';\n\nconst Demo = () => {\n  const [value, onChange] = React.useState<number | null>(null);\n\n  return (\n    <>\n      <Accordion pb={4} value={value} onChange={onChange}>\n        <Accordion.Item value={11}>\n          <Accordion.Item.Toggle pb={2}>\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Duration 500\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse duration={500}>\n            <Box p=\'12px 12px \'>Hello Section</Box>\n            <Box p=\'24px\'> Hello Section</Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n\n        <Accordion.Item value={1}>\n          <Accordion.Item.Toggle\n            pb={2}\n            onClick={() => {\n              setTimeout(() => {\n                if (value === 1) {\n                  onChange(null);\n                } else {\n                  onChange(1);\n                }\n              }, 500);\n\n              return false;\n            }}\n          >\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Duration 500 Delay 500\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse duration={500}>\n            <Box p=\'12px 12px \'>Hello Section</Box>\n            <Box p=\'24px\'> Hello Section</Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n\n        <Accordion.Item value={2}>\n          <Accordion.Item.Toggle pb={2}>\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Duration 0\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse duration={0}>\n            <Box p=\'12px 12px \'>Hello Section</Box>\n            <Box p=\'24px\'> Hello Section</Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n\n        <Accordion.Item value={3}>\n          <Accordion.Item.Toggle pb={2}>\n            <Accordion.Item.ToggleButton>\n              <Accordion.Item.Chevron mr={2} />\n              Default\n            </Accordion.Item.ToggleButton>\n          </Accordion.Item.Toggle>\n          <Accordion.Item.Collapse>\n            <Box p=\'12px 12px \'>Hello Section</Box>\n            <Box p=\'24px\'> Hello Section</Box>\n          </Accordion.Item.Collapse>\n        </Accordion.Item>\n      </Accordion>\n    </>\n  );\n};\n\nexport default Demo;\n' },
};
