name: slack-updates-pre-broadcast

on:
  schedule:
    - cron: '0 14 * * 5'
  workflow_dispatch:
jobs:
  # 1 lvl
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-modules
        with:
          path: |
            node_modules
            */*/node_modules
            website/node_modules
          key: modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}--${{ hashFiles('website/yarn.lock') }}
      - name: Install dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn --non-interactive --frozen-lockfile

  slack-updates-pre-broadcast:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Restore cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            website/node_modules
          key: modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}--${{ hashFiles('website/yarn.lock') }}
      - name: Notification
        env:
          SLACK_API_ENDPOINTS: ${{ secrets.SLACK_WEBHOOK_URL_DEV }}
        run: |
          yarn slack-updates-broadcast
